/-
# Tasaki §7.1.3 (AKLT uniqueness), stage C2: local bond divisibility (`L = 2`)

The uniqueness proof of the AKLT ground state (Kennedy–Lieb–Tasaki [41], Tasaki §7.1.3,
pp. 186–188) passes through the Weyl (Schwinger-boson) polynomial representation
`weylMap : ((Fin L → Fin 3) → ℂ) →ₗ[ℂ] MvPolynomial (Fin L × Fin 2) ℂ`
(`LatticeSystem.Math.WeylSpinOneMap`).  The heart of the argument is that a state whose bond slice
carries the valence-bond singlet is mapped into the ideal generated by the bond factor
`f₂ = u₀ v₁ − v₀ u₁ = X(0,0) X(1,1) − X(0,1) X(1,0)`.

This file proves the **two-site (`L = 2`) local half** of that bridge (`U3a`, the `⟹` direction):

  `φ ∈ vbsBondSubspace  ⟹  f₂ ∣ weylMap φ`.

Concretely, each of the four VBS bond generators `Ψ_{σσ'}` (`Quantum.vbsBondVec σ σ'`) has Weyl image
an explicit multiple of `f₂`:

  `weylMap Ψ_{↑↑} = (√2/2)·u₀ u₁·f₂`,   `weylMap Ψ_{↑↓} = 2·u₀ v₁·f₂`,
  `weylMap Ψ_{↓↑} = 2·v₀ u₁·f₂`,        `weylMap Ψ_{↓↓} = (√2/2)·v₀ v₁·f₂`.

The middle Clebsch–Gordan weight `c(1) = √2` (`cgSite 1`) is **essential**: `cgNorm ![1,1] = √2·√2 = 2`
is exactly the cross-term weight that makes the mixed generators land in `(f₂)` (with naive unit
weights the images would not be divisible).  The four generators lie in the preimage submodule
`weylMap⁻¹ (f₂)`, hence so does their span `W = vbsBondSubspace`, giving the stated implication for
every `φ ∈ W`.

The global (general-`L`) split identity that lifts this local statement to the full chain (`U3b`)
lives in a later stage.

Reference: Hal Tasaki, *Physics and Mathematics of Quantum Many-Body Systems* (Springer, 2020),
§7.1.3 "The Uniqueness of the Ground State", pp. 186–188, eqs. (7.1.22)–(7.1.25); polynomial
representation due to Arovas–Auerbach–Haldane [10]; proof due to Kennedy–Lieb–Tasaki [41].
-/
import LatticeSystem.Quantum.SpinS.AKLTBondProjection
import LatticeSystem.Math.MvPolynomial.WeylSpinOneMap
import LatticeSystem.Math.MvPolynomial.BilinearFactorCoprime

open MvPolynomial

namespace LatticeSystem.Quantum.AKLTUniqueness

open LatticeSystem.Quantum LatticeSystem.Math

/-- The Weyl image of a standard basis vector `Pi.single σ 1` is the single Weyl monomial
`weylMono σ` (the Weyl map is the linear combination of the `weylMono σ`). -/
theorem weylMap_single {L : ℕ} (σ : Fin L → Fin 3) :
    weylMap (Pi.single σ (1 : ℂ)) = weylMono σ := by
  classical
  simp only [weylMap, Fintype.linearCombination_apply]
  rw [Finset.sum_eq_single σ]
  · rw [Pi.single_eq_same, one_smul]
  · intro b _ hb
    rw [Pi.single_eq_of_ne hb, zero_smul]
  · intro h; exact absurd (Finset.mem_univ σ) h

/-- The `L = 2` **bond factor** `f₂ = u₀ v₁ − v₀ u₁ = X(0,0) X(1,1) − X(0,1) X(1,0)`, the
bilinear singlet factor on the four Weyl variables of a two-site bond (`bondFactor`). -/
noncomputable def f2 : MvPolynomial (Fin 2 × Fin 2) ℂ :=
  bondFactor ((0 : Fin 2), (0 : Fin 2)) (1, 1) (0, 1) (1, 0)

/-! ## Basis decompositions of the four VBS bond generators

Each `Ψ_{σσ'}` is a two-term combination of standard basis vectors `Pi.single`; splitting it this
way lets the Weyl image be computed through linearity of `weylMap` and `weylMap_single`. -/

/-- `Ψ_{↑↑} = ½·e_{[0,1]} − ½·e_{[1,0]}` (`vbsBondVec 0 0`). -/
theorem vbsBondVec_00_eq :
    (vbsBondVec 0 0 : (Fin 2 → Fin 3) → ℂ)
      = (1 / 2 : ℂ) • (Pi.single (![0, 1] : Fin 2 → Fin 3) (1 : ℂ) : (Fin 2 → Fin 3) → ℂ)
        - (1 / 2 : ℂ) • (Pi.single (![1, 0] : Fin 2 → Fin 3) (1 : ℂ) : (Fin 2 → Fin 3) → ℂ) := by
  funext a
  obtain ⟨a0, a1, rfl⟩ : ∃ a0 a1 : Fin 3, a = ![a0, a1] :=
    ⟨a 0, a 1, by funext k; fin_cases k <;> rfl⟩
  simp only [vbsBondVec, Fin.isValue, Pi.sub_apply, Pi.smul_apply, smul_eq_mul,
    Matrix.cons_val_zero, Matrix.cons_val_one, if_true]
  by_cases h01 : (![a0, a1] : Fin 2 → Fin 3) = ![0, 1]
  · have e0 : a0 = 0 := congrFun h01 0
    have e1 : a1 = 1 := congrFun h01 1
    subst e0 e1
    simp
  · rw [Pi.single_eq_of_ne (by simpa using h01)]
    by_cases h10 : (![a0, a1] : Fin 2 → Fin 3) = ![1, 0]
    · have e0 : a0 = 1 := congrFun h10 0
      have e1 : a1 = 0 := congrFun h10 1
      subst e0 e1
      simp
    · rw [Pi.single_eq_of_ne (by simpa using h10)]
      have n01 : ¬ (a0 = 0 ∧ a1 = 1) := by rintro ⟨rfl, rfl⟩; exact h01 rfl
      have n10 : ¬ (a0 = 1 ∧ a1 = 0) := by rintro ⟨rfl, rfl⟩; exact h10 rfl
      simp [n01, n10]

/-- `Ψ_{↑↓} = 2·e_{[0,2]} − e_{[1,1]}` (`vbsBondVec 0 1`). -/
theorem vbsBondVec_01_eq :
    (vbsBondVec 0 1 : (Fin 2 → Fin 3) → ℂ)
      = (2 : ℂ) • (Pi.single (![0, 2] : Fin 2 → Fin 3) (1 : ℂ) : (Fin 2 → Fin 3) → ℂ)
        - (Pi.single (![1, 1] : Fin 2 → Fin 3) (1 : ℂ) : (Fin 2 → Fin 3) → ℂ) := by
  funext a
  obtain ⟨a0, a1, rfl⟩ : ∃ a0 a1 : Fin 3, a = ![a0, a1] :=
    ⟨a 0, a 1, by funext k; fin_cases k <;> rfl⟩
  simp only [vbsBondVec, Fin.isValue, Pi.sub_apply, Pi.smul_apply, smul_eq_mul,
    Matrix.cons_val_zero, Matrix.cons_val_one, if_true]
  by_cases h02 : (![a0, a1] : Fin 2 → Fin 3) = ![0, 2]
  · have e0 : a0 = 0 := congrFun h02 0
    have e1 : a1 = 2 := congrFun h02 1
    subst e0 e1
    simp
  · rw [Pi.single_eq_of_ne (by simpa using h02)]
    by_cases h11 : (![a0, a1] : Fin 2 → Fin 3) = ![1, 1]
    · have e0 : a0 = 1 := congrFun h11 0
      have e1 : a1 = 1 := congrFun h11 1
      subst e0 e1
      simp
    · rw [Pi.single_eq_of_ne (by simpa using h11)]
      have n02 : ¬ (a0 = 0 ∧ a1 = 2) := by rintro ⟨rfl, rfl⟩; exact h02 rfl
      have n11 : ¬ (a0 = 1 ∧ a1 = 1) := by rintro ⟨rfl, rfl⟩; exact h11 rfl
      simp [n02, n11]

/-- `Ψ_{↓↑} = e_{[1,1]} − 2·e_{[2,0]}` (`vbsBondVec 1 0`). -/
theorem vbsBondVec_10_eq :
    (vbsBondVec 1 0 : (Fin 2 → Fin 3) → ℂ)
      = (Pi.single (![1, 1] : Fin 2 → Fin 3) (1 : ℂ) : (Fin 2 → Fin 3) → ℂ)
        - (2 : ℂ) • (Pi.single (![2, 0] : Fin 2 → Fin 3) (1 : ℂ) : (Fin 2 → Fin 3) → ℂ) := by
  funext a
  obtain ⟨a0, a1, rfl⟩ : ∃ a0 a1 : Fin 3, a = ![a0, a1] :=
    ⟨a 0, a 1, by funext k; fin_cases k <;> rfl⟩
  simp only [vbsBondVec, Fin.isValue, Pi.sub_apply, Pi.smul_apply, smul_eq_mul,
    Matrix.cons_val_zero, Matrix.cons_val_one]
  by_cases h11 : (![a0, a1] : Fin 2 → Fin 3) = ![1, 1]
  · have e0 : a0 = 1 := congrFun h11 0
    have e1 : a1 = 1 := congrFun h11 1
    subst e0 e1
    simp
  · rw [Pi.single_eq_of_ne (by simpa using h11)]
    by_cases h20 : (![a0, a1] : Fin 2 → Fin 3) = ![2, 0]
    · have e0 : a0 = 2 := congrFun h20 0
      have e1 : a1 = 0 := congrFun h20 1
      subst e0 e1
      simp
    · rw [Pi.single_eq_of_ne (by simpa using h20)]
      have n11 : ¬ (a0 = 1 ∧ a1 = 1) := by rintro ⟨rfl, rfl⟩; exact h11 rfl
      have n20 : ¬ (a0 = 2 ∧ a1 = 0) := by rintro ⟨rfl, rfl⟩; exact h20 rfl
      simp [n11, n20]

/-- `Ψ_{↓↓} = ½·e_{[1,2]} − ½·e_{[2,1]}` (`vbsBondVec 1 1`). -/
theorem vbsBondVec_11_eq :
    (vbsBondVec 1 1 : (Fin 2 → Fin 3) → ℂ)
      = (1 / 2 : ℂ) • (Pi.single (![1, 2] : Fin 2 → Fin 3) (1 : ℂ) : (Fin 2 → Fin 3) → ℂ)
        - (1 / 2 : ℂ) • (Pi.single (![2, 1] : Fin 2 → Fin 3) (1 : ℂ) : (Fin 2 → Fin 3) → ℂ) := by
  funext a
  obtain ⟨a0, a1, rfl⟩ : ∃ a0 a1 : Fin 3, a = ![a0, a1] :=
    ⟨a 0, a 1, by funext k; fin_cases k <;> rfl⟩
  simp only [vbsBondVec, Fin.isValue, Pi.sub_apply, Pi.smul_apply, smul_eq_mul,
    Matrix.cons_val_zero, Matrix.cons_val_one]
  by_cases h12 : (![a0, a1] : Fin 2 → Fin 3) = ![1, 2]
  · have e0 : a0 = 1 := congrFun h12 0
    have e1 : a1 = 2 := congrFun h12 1
    subst e0 e1
    simp
  · rw [Pi.single_eq_of_ne (by simpa using h12)]
    by_cases h21 : (![a0, a1] : Fin 2 → Fin 3) = ![2, 1]
    · have e0 : a0 = 2 := congrFun h21 0
      have e1 : a1 = 1 := congrFun h21 1
      subst e0 e1
      simp
    · rw [Pi.single_eq_of_ne (by simpa using h21)]
      have n12 : ¬ (a0 = 1 ∧ a1 = 2) := by rintro ⟨rfl, rfl⟩; exact h12 rfl
      have n21 : ¬ (a0 = 2 ∧ a1 = 1) := by rintro ⟨rfl, rfl⟩; exact h21 rfl
      simp [n12, n21]

/-! ## Per-generator divisibility `f₂ ∣ weylMap Ψ_{σσ'}`

Each proof: decompose the generator into two basis vectors, push through `weylMap` linearity, expand
each `weylMono` into an explicit monomial via its multidegree `md` and Clebsch–Gordan weight
`cgNorm`, then match against the explicit quotient times `f₂`. -/

/-- `f₂ ∣ weylMap Ψ_{↑↑}`: `weylMap Ψ_{↑↑} = (√2/2)·u₀ u₁·f₂`
(`cgNorm ![0,1] = cgNorm ![1,0] = √2`). -/
theorem f2_dvd_weylMap_vbsBondVec_00 :
    f2 ∣ weylMap (L := 2) (vbsBondVec 0 0) := by
  refine ⟨monomial (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
      + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1) ((1 / 2 : ℂ) * (Real.sqrt 2 : ℂ)), ?_⟩
  rw [vbsBondVec_00_eq, map_sub, map_smul, map_smul, weylMap_single, weylMap_single]
  have hmd01 : md (![0, 1] : Fin 2 → Fin 3)
      = Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 2
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1 := by
    ext i; fin_cases i <;> simp [md, Fin.sum_univ_two, mdSite]
  have hcg01 : cgNorm (![0, 1] : Fin 2 → Fin 3) = (Real.sqrt 2 : ℂ) := by
    simp [cgNorm, Fin.prod_univ_two, cgSite]
  have hmd10 : md (![1, 0] : Fin 2 → Fin 3)
      = Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 2 := by
    ext i; fin_cases i <;> simp [md, Fin.sum_univ_two, mdSite]
  have hcg10 : cgNorm (![1, 0] : Fin 2 → Fin 3) = (Real.sqrt 2 : ℂ) := by
    simp [cgNorm, Fin.prod_univ_two, cgSite]
  simp only [weylMono, hmd01, hcg01, hmd10, hcg10, smul_monomial, smul_eq_mul]
  rw [f2, bondFactor, sub_mul, MvPolynomial.X, MvPolynomial.X, MvPolynomial.X, MvPolynomial.X,
    monomial_mul, monomial_mul, monomial_mul, monomial_mul]
  have hE1 : (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 2
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1 : (Fin 2 × Fin 2) →₀ ℕ)
      = Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1 + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1
        + (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
          + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1) := by
    ext i; fin_cases i <;> simp
  have hE2 : (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 2 : (Fin 2 × Fin 2) →₀ ℕ)
      = Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1 + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
          + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1) := by
    ext i; fin_cases i <;> simp
  rw [hE1, hE2]; norm_num

/-- `f₂ ∣ weylMap Ψ_{↑↓}`: `weylMap Ψ_{↑↓} = 2·u₀ v₁·f₂`.  The `√2` middle weight is essential —
`cgNorm ![1,1] = √2·√2 = 2` matches the cross term so the mixed singlet lands in `(f₂)`. -/
theorem f2_dvd_weylMap_vbsBondVec_01 :
    f2 ∣ weylMap (L := 2) (vbsBondVec 0 1) := by
  refine ⟨monomial (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
      + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1) 2, ?_⟩
  rw [vbsBondVec_01_eq, map_sub, map_smul, weylMap_single, weylMap_single]
  have hmd02 : md (![0, 2] : Fin 2 → Fin 3)
      = Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 2
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 2 := by
    ext i; fin_cases i <;> simp [md, Fin.sum_univ_two, mdSite]
  have hcg02 : cgNorm (![0, 2] : Fin 2 → Fin 3) = 1 := by
    simp [cgNorm, Fin.prod_univ_two, cgSite]
  have hmd11 : md (![1, 1] : Fin 2 → Fin 3)
      = Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1 := by
    ext i; fin_cases i <;> simp [md, Fin.sum_univ_two, mdSite]
  have hcg11 : cgNorm (![1, 1] : Fin 2 → Fin 3) = 2 := by
    simp only [cgNorm, Fin.prod_univ_two, cgSite, Matrix.cons_val_zero, Matrix.cons_val_one,
      Fin.isValue]
    rw [← Complex.ofReal_mul, Real.mul_self_sqrt (by norm_num)]
    norm_num
  simp only [weylMono, hmd02, hcg02, hmd11, hcg11, smul_monomial, smul_eq_mul, mul_one]
  rw [f2, bondFactor, sub_mul, MvPolynomial.X, MvPolynomial.X, MvPolynomial.X, MvPolynomial.X,
    monomial_mul, monomial_mul, monomial_mul, monomial_mul]
  have hE1 : (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 2
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 2 : (Fin 2 × Fin 2) →₀ ℕ)
      = Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1 + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1
        + (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
          + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1) := by
    ext i; fin_cases i <;> simp
  have hE2 : (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1 : (Fin 2 × Fin 2) →₀ ℕ)
      = Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1 + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
          + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1) := by
    ext i; fin_cases i <;> simp
  rw [hE1, hE2]; norm_num

/-- `f₂ ∣ weylMap Ψ_{↓↑}`: `weylMap Ψ_{↓↑} = 2·v₀ u₁·f₂`
(`cgNorm ![1,1] = 2`, `cgNorm ![2,0] = 1`). -/
theorem f2_dvd_weylMap_vbsBondVec_10 :
    f2 ∣ weylMap (L := 2) (vbsBondVec 1 0) := by
  refine ⟨monomial (Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
      + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1) 2, ?_⟩
  rw [vbsBondVec_10_eq, map_sub, map_smul, weylMap_single, weylMap_single]
  have hmd11 : md (![1, 1] : Fin 2 → Fin 3)
      = Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1 := by
    ext i; fin_cases i <;> simp [md, Fin.sum_univ_two, mdSite]
  have hcg11 : cgNorm (![1, 1] : Fin 2 → Fin 3) = 2 := by
    simp only [cgNorm, Fin.prod_univ_two, cgSite, Matrix.cons_val_zero, Matrix.cons_val_one,
      Fin.isValue]
    rw [← Complex.ofReal_mul, Real.mul_self_sqrt (by norm_num)]
    norm_num
  have hmd20 : md (![2, 0] : Fin 2 → Fin 3)
      = Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 2
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 2 := by
    ext i; fin_cases i <;> simp [md, Fin.sum_univ_two, mdSite]
  have hcg20 : cgNorm (![2, 0] : Fin 2 → Fin 3) = 1 := by
    simp [cgNorm, Fin.prod_univ_two, cgSite]
  simp only [weylMono, hmd11, hcg11, hmd20, hcg20, smul_monomial, smul_eq_mul, mul_one]
  rw [f2, bondFactor, sub_mul, MvPolynomial.X, MvPolynomial.X, MvPolynomial.X, MvPolynomial.X,
    monomial_mul, monomial_mul, monomial_mul, monomial_mul]
  have hE1 : (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1 : (Fin 2 × Fin 2) →₀ ℕ)
      = Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1 + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1
        + (Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
          + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1) := by
    ext i; fin_cases i <;> simp
  have hE2 : (Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 2
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 2 : (Fin 2 × Fin 2) →₀ ℕ)
      = Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1 + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + (Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
          + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1) := by
    ext i; fin_cases i <;> simp
  rw [hE1, hE2]; norm_num

/-- `f₂ ∣ weylMap Ψ_{↓↓}`: `weylMap Ψ_{↓↓} = (√2/2)·v₀ v₁·f₂`
(`cgNorm ![1,2] = cgNorm ![2,1] = √2`). -/
theorem f2_dvd_weylMap_vbsBondVec_11 :
    f2 ∣ weylMap (L := 2) (vbsBondVec 1 1) := by
  refine ⟨monomial (Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
      + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1) ((1 / 2 : ℂ) * (Real.sqrt 2 : ℂ)), ?_⟩
  rw [vbsBondVec_11_eq, map_sub, map_smul, map_smul, weylMap_single, weylMap_single]
  have hmd12 : md (![1, 2] : Fin 2 → Fin 3)
      = Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 2 := by
    ext i; fin_cases i <;> simp [md, Fin.sum_univ_two, mdSite]
  have hcg12 : cgNorm (![1, 2] : Fin 2 → Fin 3) = (Real.sqrt 2 : ℂ) := by
    simp [cgNorm, Fin.prod_univ_two, cgSite]
  have hmd21 : md (![2, 1] : Fin 2 → Fin 3)
      = Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 2
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1 := by
    ext i; fin_cases i <;> simp [md, Fin.sum_univ_two, mdSite]
  have hcg21 : cgNorm (![2, 1] : Fin 2 → Fin 3) = (Real.sqrt 2 : ℂ) := by
    simp [cgNorm, Fin.prod_univ_two, cgSite]
  simp only [weylMono, hmd12, hcg12, hmd21, hcg21, smul_monomial, smul_eq_mul]
  rw [f2, bondFactor, sub_mul, MvPolynomial.X, MvPolynomial.X, MvPolynomial.X, MvPolynomial.X,
    monomial_mul, monomial_mul, monomial_mul, monomial_mul]
  have hE1 : (Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 2 : (Fin 2 × Fin 2) →₀ ℕ)
      = Finsupp.single ((0 : Fin 2), (0 : Fin 2)) 1 + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1
        + (Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
          + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1) := by
    ext i; fin_cases i <;> simp
  have hE2 : (Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 2
        + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1 : (Fin 2 × Fin 2) →₀ ℕ)
      = Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1 + Finsupp.single ((1 : Fin 2), (0 : Fin 2)) 1
        + (Finsupp.single ((0 : Fin 2), (1 : Fin 2)) 1
          + Finsupp.single ((1 : Fin 2), (1 : Fin 2)) 1) := by
    ext i; fin_cases i <;> simp
  rw [hE1, hE2]; norm_num

/-- Each of the four VBS bond generators `Ψ_{σσ'}` maps into the ideal `(f₂)` under `weylMap`
(Tasaki §7.1.3, the four singlet-form generators of eq. (7.1.20)). -/
theorem f2_dvd_weylMap_vbsBondVec (s s' : Fin 2) :
    f2 ∣ weylMap (L := 2) (vbsBondVec s s') := by
  fin_cases s <;> fin_cases s'
  · exact f2_dvd_weylMap_vbsBondVec_00
  · exact f2_dvd_weylMap_vbsBondVec_01
  · exact f2_dvd_weylMap_vbsBondVec_10
  · exact f2_dvd_weylMap_vbsBondVec_11

/-- **U3a (local, `L = 2`), span level (Tasaki §7.1.3, `⟹` direction).**  Every element of the VBS
bond subspace `W = vbsBondSubspace` has Weyl image divisible by the bond factor `f₂`.

Proof: the preimage `weylMap⁻¹ (f₂)` is a `ℂ`-submodule (the `comap` of the ideal `(f₂)` restricted
to `ℂ`-scalars); it contains the four generators `Ψ_{σσ'}` by `f2_dvd_weylMap_vbsBondVec`, hence
contains their span `W`. -/
theorem f2_dvd_weylMap_of_mem_vbsBondSubspace
    (φ : (Fin 2 → Fin 3) → ℂ) (hφ : φ ∈ vbsBondSubspace) :
    f2 ∣ weylMap (L := 2) φ := by
  have hmem : φ ∈ Submodule.comap (weylMap (L := 2))
      ((Ideal.span {f2}).restrictScalars ℂ) := by
    refine (Submodule.span_le.mpr ?_) hφ
    rintro _ ⟨p, rfl⟩
    simp only [SetLike.mem_coe, Submodule.mem_comap, Submodule.restrictScalars_mem,
      Ideal.mem_span_singleton]
    exact f2_dvd_weylMap_vbsBondVec p.1 p.2
  simpa only [Submodule.mem_comap, Submodule.restrictScalars_mem, Ideal.mem_span_singleton]
    using hmem

end LatticeSystem.Quantum.AKLTUniqueness
