/-
Copyright (c) 2026 lattice-system contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import LatticeSystem.Quantum.ManyBody
import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse

/-!
# Gibbs state for finite-volume quantum systems

Following Tasaki *Physics and Mathematics of Quantum Many-Body Systems*,
§3.3, this module defines the finite-volume quantum Gibbs state

  `ρ_β = exp(-β H) / Z`,   `Z = Tr(exp(-β H))`,

for a Hermitian Hamiltonian `H : ManyBodyOp Λ` and inverse temperature
`β : ℝ`. We prove:

* `gibbsExp_isHermitian` — `exp(-β H)` is Hermitian.
* `gibbsState_trace` — `Tr(ρ_β) = 1` (given `Z ≠ 0`).
* `gibbsState_isHermitian` — `ρ_β` is Hermitian.
* `gibbsExpectation_one` — `⟨1⟩_β = 1` (given `Z ≠ 0`).
* `gibbsExpectation_neg`, `gibbsExpectation_sub`, `gibbsExpectation_sum`
  — full linearity API: negation, subtraction, finite sums commute
  with `gibbsExpectation`.
* `gibbsExp_commute_hamiltonian`, `gibbsState_commute_hamiltonian` —
  `[exp(-β H), H] = 0` and `[ρ_β, H] = 0`, i.e. the Gibbs state is
  stationary under the dynamics generated by `H` (Tasaki §3.3, p. 80).
* `Matrix.trace_mul_star_of_isHermitian` — generic auxiliary:
  for Hermitian matrices `A`, `B`, `star (Tr(A · B)) = Tr(A · B)`.
* `gibbsExpectation_star_of_isHermitian`,
  `gibbsExpectation_im_of_isHermitian`,
  `gibbsExpectation_ofReal_re_eq_of_isHermitian` — for Hermitian `H`
  and Hermitian observable `O`, the expectation `⟨O⟩_β` is real
  (in three equivalent forms: fixed by `star`, vanishing imaginary
  part, equal to its real part cast to `ℂ`).
* `gibbsExpectation_mul_hamiltonian_comm`,
  `gibbsExpectation_commutator_hamiltonian` — conservation laws:
  `⟨H · A⟩_β = ⟨A · H⟩_β` and `⟨[H, A]⟩_β = 0` (Tasaki §3.3, p. 80).
* `gibbsExpectation_sq_im_of_isHermitian` — for Hermitian `H, O`,
  `(⟨O · O⟩_β).im = 0` (variance precursor).
* `gibbsExpectation_pow_im_of_isHermitian` — for Hermitian `H, O` and
  any `n : ℕ`, `(⟨O ^ n⟩_β).im = 0` (all natural-power moments real).
* `gibbsVariance β H O` — canonical-ensemble variance
  `⟨O²⟩_β − (⟨O⟩_β)²` and its realness for Hermitian observables
  (`gibbsVariance_im_of_isHermitian`).
* `gibbsCovariance β H A B` — canonical-ensemble (complex) covariance
  `⟨A · B⟩_β − ⟨A⟩_β · ⟨B⟩_β`; `gibbsCovariance_self_eq_variance`
  recovers the variance at `A = B`.
* `gibbsCovarianceSymm β H A B` — symmetric (real-valued for Hermitian
  observables) covariance
  `(1/2) · ⟨A · B + B · A⟩_β − ⟨A⟩_β · ⟨B⟩_β`. Self-equals-variance
  at `A = B` and realness for Hermitian `A, B`
  (`gibbsCovarianceSymm_im_of_isHermitian`).
* `Matrix.trace_mul_conjTranspose_swap_of_isHermitian` — generic
  helper: for Hermitian `ρ`, `star Tr(ρ · X) = Tr(ρ · Xᴴ)`.
* `gibbsExpectation_star_swap_of_isHermitian` — for Hermitian `H, A, B`,
  `star ⟨A · B⟩_β = ⟨B · A⟩_β`.
* `gibbsExpectation_anticommutator_im`,
  `gibbsExpectation_commutator_re` — under Hermitian `H, A, B`,
  the anticommutator expectation is real and the commutator expectation
  is purely imaginary.
* `gibbsExpectation_mul_hamiltonian_im` — for Hermitian `H, O`,
  `(⟨H · O⟩_β).im = 0` (energy-mode expectation reality).
* `gibbsState_zero`, `gibbsState_zero_inv`, `gibbsExpectation_zero` —
  high-temperature limit `ρ_0 = (1/dim) · I`, its matrix inverse
  `ρ_0⁻¹ = dim · I`, and `⟨A⟩_0 = (1/dim) · Tr A` (Tasaki §3.3, p. 78).
* `gibbsExp_add`, `gibbsExp_neg_mul_self`, `gibbsExp_self_mul_neg`,
  `gibbsExp_isUnit`, `gibbsExp_ne_zero` — one-parameter group property
  in `β`: `e^{-(β₁+β₂)H} = e^{-β₁H} · e^{-β₂H}`,
  `e^{βH} · e^{-βH} = 1`, hence `e^{-βH}` is invertible (and in
  particular nonzero). Foundation for KMS / Wick rotation.
* `gibbsState_ne_zero` — `ρ_β ≠ 0` whenever `Z(β) ≠ 0`.
* `gibbsState_inv` — when `Z(β) ≠ 0`,
  `(ρ_β)⁻¹ = Z(β) · e^{β H}`. Generalises `gibbsState_zero_inv`
  beyond β = 0.
* `partitionFn_smul_gibbsState_eq_gibbsExp`,
  `partitionFn_mul_gibbsExpectation_eq` — when `Z(β) ≠ 0`,
  `Z(β) · ρ_β = e^{-β H}` (canonical rescaled identity) and
  `Z(β) · ⟨A⟩_β = Tr(e^{-β H} · A)` (canonical normalisation).
* `gibbsExp_natCast_mul`, `gibbsExp_two_mul` — exact discrete
  semigroup identity `gibbsExp ((n : ℝ) · β) H = (gibbsExp β H)^n`
  for `n : ℕ`.
* `gibbsExp_inv`, `gibbsExp_intCast_mul` — explicit matrix inverse
  `(gibbsExp β H)⁻¹ = gibbsExp (-β) H` and the integer-power extension
  to `n : ℤ`.
-/

namespace LatticeSystem.Quantum

open Matrix

variable {Λ : Type*} [Fintype Λ] [DecidableEq Λ]

/-- Negation of a real cast to `ℂ` is self-adjoint. -/
private lemma negReal_isSelfAdjoint (β : ℝ) : IsSelfAdjoint (-(β : ℂ)) := by
  rw [IsSelfAdjoint, star_neg, RCLike.star_def, Complex.conj_ofReal]

/-! ## Gibbs exponential -/

/-- The Gibbs exponential `exp(-β H)` for inverse temperature `β : ℝ`
and Hamiltonian `H : ManyBodyOp Λ`. -/
noncomputable def gibbsExp (β : ℝ) (H : ManyBodyOp Λ) : ManyBodyOp Λ :=
  NormedSpace.exp ((-(β : ℂ)) • H)

/-- `exp(-β H)` is Hermitian when `H` is Hermitian. -/
theorem gibbsExp_isHermitian {H : ManyBodyOp Λ} (hH : H.IsHermitian) (β : ℝ) :
    (gibbsExp β H).IsHermitian := by
  exact Matrix.IsHermitian.exp (hH.smul (negReal_isSelfAdjoint β))

/-! ## Partition function -/

/-- The partition function `Z(β) = Tr(exp(-β H))`. -/
noncomputable def partitionFn (β : ℝ) (H : ManyBodyOp Λ) : ℂ :=
  (gibbsExp β H).trace

/-! ## Gibbs state (density matrix)

Note: `partitionFn β H ≠ 0` (the partition function is nonzero) is
NOT proved here because the CFC-based proof
(`IsSelfAdjoint.exp_nonneg` under `open scoped MatrixOrder` +
`PosSemidef.trace_eq_zero_iff` + `Matrix.isUnit_exp`) causes
deterministic timeout in Lean's typeclass resolution. All downstream
theorems take `hZ : partitionFn β H ≠ 0` as an explicit hypothesis. -/

/-- The Gibbs state (density matrix) `ρ_β = (1/Z) exp(-β H)`. -/
noncomputable def gibbsState (β : ℝ) (H : ManyBodyOp Λ) : ManyBodyOp Λ :=
  (1 / partitionFn β H) • gibbsExp β H

/-- The Gibbs state has unit trace: `Tr(ρ_β) = 1`. -/
theorem gibbsState_trace {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) :
    (gibbsState β H).trace = 1 := by
  simp only [gibbsState, Matrix.trace_smul, smul_eq_mul, one_div]
  exact inv_mul_cancel₀ hZ

/-- The Gibbs state is Hermitian. -/
theorem gibbsState_isHermitian {H : ManyBodyOp Λ} (hH : H.IsHermitian) (β : ℝ) :
    (gibbsState β H).IsHermitian := by
  apply Matrix.IsHermitian.smul (gibbsExp_isHermitian hH β)
  have htr : star (partitionFn β H) = partitionFn β H := by
    simp only [partitionFn, ← Matrix.trace_conjTranspose, (gibbsExp_isHermitian hH β).eq]
  rw [IsSelfAdjoint, one_div, star_inv₀, htr]

/-! ## Expectation value -/

/-- The Gibbs expectation value `⟨O⟩_β = Tr(ρ_β O)`. -/
noncomputable def gibbsExpectation (β : ℝ) (H O : ManyBodyOp Λ) : ℂ :=
  ((gibbsState β H) * O).trace

/-- `⟨1⟩_β = 1`. -/
theorem gibbsExpectation_one {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) :
    gibbsExpectation β H 1 = 1 := by
  simp only [gibbsExpectation, mul_one]
  exact gibbsState_trace β hZ

/-! ## Properties at β = 0 -/

/-- At `β = 0`, `exp(-0 · H) = 1` (the identity matrix). -/
theorem gibbsExp_zero (H : ManyBodyOp Λ) : gibbsExp 0 H = 1 := by
  simp only [gibbsExp, neg_zero, Complex.ofReal_zero, zero_smul, NormedSpace.exp_zero]

/-! ## One-parameter group property in `β` -/

/-- The Gibbs exponential is additive in the inverse temperature:
`gibbsExp (β₁ + β₂) H = gibbsExp β₁ H * gibbsExp β₂ H`. The two factors
commute because both are functions of the same `H`. -/
theorem gibbsExp_add (β₁ β₂ : ℝ) (H : ManyBodyOp Λ) :
    gibbsExp (β₁ + β₂) H = gibbsExp β₁ H * gibbsExp β₂ H := by
  unfold gibbsExp
  have hcomm : Commute (-(β₁ : ℂ) • H) (-(β₂ : ℂ) • H) :=
    ((Commute.refl H).smul_left _).smul_right _
  have hsum : -((β₁ + β₂ : ℝ) : ℂ) • H = -(β₁ : ℂ) • H + -(β₂ : ℂ) • H := by
    push_cast; module
  rw [hsum, Matrix.exp_add_of_commute _ _ hcomm]

/-- For commuting Hamiltonians `H₁, H₂`, the Gibbs exponential
factorises: `e^{-β(H₁+H₂)} = e^{-βH₁} · e^{-βH₂}`. This is the basic
identity behind exact decoupling, mean-field block decompositions, and
the simplest cases of the Suzuki–Trotter formula (where the
commutator-correction terms vanish). -/
theorem gibbsExp_add_of_commute_hamiltonians (β : ℝ)
    {H₁ H₂ : ManyBodyOp Λ} (h : Commute H₁ H₂) :
    gibbsExp β (H₁ + H₂) = gibbsExp β H₁ * gibbsExp β H₂ := by
  unfold gibbsExp
  have hcomm : Commute (-(β : ℂ) • H₁) (-(β : ℂ) • H₂) :=
    (h.smul_left _).smul_right _
  rw [smul_add, Matrix.exp_add_of_commute _ _ hcomm]

/-- `exp(βH) · exp(-βH) = 1`: the Gibbs exponential at `-β` is a left
inverse of the one at `β`. -/
theorem gibbsExp_neg_mul_self (β : ℝ) (H : ManyBodyOp Λ) :
    gibbsExp (-β) H * gibbsExp β H = 1 := by
  rw [← gibbsExp_add, neg_add_cancel, gibbsExp_zero]

/-- `exp(-βH) · exp(βH) = 1`: the Gibbs exponential at `β` is a left
inverse of the one at `-β`. -/
theorem gibbsExp_self_mul_neg (β : ℝ) (H : ManyBodyOp Λ) :
    gibbsExp β H * gibbsExp (-β) H = 1 := by
  rw [← gibbsExp_add, add_neg_cancel, gibbsExp_zero]

/-- The Gibbs exponential is a unit (invertible) for every `β` and `H`. -/
theorem gibbsExp_isUnit (β : ℝ) (H : ManyBodyOp Λ) :
    IsUnit (gibbsExp β H) :=
  IsUnit.of_mul_eq_one _ (gibbsExp_self_mul_neg β H)

/-- The Gibbs exponential is nonzero. Direct corollary of
`gibbsExp_isUnit` via `IsUnit.ne_zero`. -/
theorem gibbsExp_ne_zero (β : ℝ) (H : ManyBodyOp Λ) :
    gibbsExp β H ≠ 0 :=
  (gibbsExp_isUnit β H).ne_zero

/-- The Gibbs state is nonzero whenever the partition function is.
Follows from `gibbsExp_ne_zero` and nonzero scalar multiplication. -/
theorem gibbsState_ne_zero {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) :
    gibbsState β H ≠ 0 := by
  unfold gibbsState
  exact smul_ne_zero (one_div_ne_zero hZ) (gibbsExp_ne_zero β H)

/-- Explicit matrix inverse of the Gibbs state when the partition function
is nonzero: `(ρ_β)⁻¹ = Z(β) · e^{β H}`. Note that
`gibbsExp (-β) H = e^{β H}` in our convention. -/
theorem gibbsState_inv {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) :
    (gibbsState β H)⁻¹ = partitionFn β H • gibbsExp (-β) H := by
  unfold gibbsState
  apply Matrix.inv_eq_left_inv
  rw [smul_mul_smul_comm, gibbsExp_neg_mul_self, mul_one_div_cancel hZ, one_smul]

/-- Canonical rescaled identity: when `Z(β) ≠ 0`,
`Z(β) · ρ_β = e^{-β H}`. Inverts the defining relation
`ρ_β = (1/Z) · e^{-β H}` to express the Gibbs exponential as the
partition function times the density matrix. -/
theorem partitionFn_smul_gibbsState_eq_gibbsExp {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) :
    partitionFn β H • gibbsState β H = gibbsExp β H := by
  unfold gibbsState
  rw [smul_smul, mul_one_div_cancel hZ, one_smul]

/-- Canonical normalisation identity: when `Z(β) ≠ 0`,
`Z(β) · ⟨A⟩_β = Tr(e^{-β H} · A)`. The "unnormalised" expectation on
the right is the form that appears throughout canonical-ensemble
derivations. -/
theorem partitionFn_mul_gibbsExpectation_eq {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) (A : ManyBodyOp Λ) :
    partitionFn β H * gibbsExpectation β H A = (gibbsExp β H * A).trace := by
  unfold gibbsExpectation
  calc partitionFn β H * (gibbsState β H * A).trace
      = (partitionFn β H • (gibbsState β H * A)).trace := by
        rw [Matrix.trace_smul, smul_eq_mul]
    _ = ((partitionFn β H • gibbsState β H) * A).trace := by
        rw [Matrix.smul_mul]
    _ = (gibbsExp β H * A).trace := by
        rw [partitionFn_smul_gibbsState_eq_gibbsExp β hZ]

/-- Exact discrete semigroup identity: for `n : ℕ`,
`gibbsExp ((n : ℝ) * β) H = (gibbsExp β H) ^ n`. -/
theorem gibbsExp_natCast_mul (n : ℕ) (β : ℝ) (H : ManyBodyOp Λ) :
    gibbsExp ((n : ℝ) * β) H = (gibbsExp β H) ^ n := by
  induction n with
  | zero => simp [gibbsExp_zero]
  | succ k ih =>
    have hsplit : ((k + 1 : ℕ) : ℝ) * β = (k : ℝ) * β + β := by push_cast; ring
    rw [hsplit, gibbsExp_add, ih, pow_succ]

/-- Specialisation at `n = 2`:
`gibbsExp (2β) H = gibbsExp β H · gibbsExp β H`. -/
theorem gibbsExp_two_mul (β : ℝ) (H : ManyBodyOp Λ) :
    gibbsExp (2 * β) H = gibbsExp β H * gibbsExp β H := by
  have := gibbsExp_natCast_mul 2 β H
  simpa [pow_two] using this

/-- The matrix inverse of `gibbsExp β H` is `gibbsExp (-β) H`,
making the inverse provided abstractly by `gibbsExp_isUnit` explicit. -/
theorem gibbsExp_inv (β : ℝ) (H : ManyBodyOp Λ) :
    (gibbsExp β H)⁻¹ = gibbsExp (-β) H :=
  Matrix.inv_eq_left_inv (gibbsExp_neg_mul_self β H)

/-- Integer-power identity: for `n : ℤ`,
`gibbsExp ((n : ℝ) * β) H = (gibbsExp β H) ^ n`. Extends
`gibbsExp_natCast_mul` to negative powers using `gibbsExp_inv`. -/
theorem gibbsExp_intCast_mul (n : ℤ) (β : ℝ) (H : ManyBodyOp Λ) :
    gibbsExp ((n : ℝ) * β) H = (gibbsExp β H) ^ n := by
  obtain ⟨m, rfl | rfl⟩ := n.eq_nat_or_neg
  · push_cast
    rw [zpow_natCast, gibbsExp_natCast_mul]
  · have hM : IsUnit (gibbsExp β H).det :=
      (Matrix.isUnit_iff_isUnit_det _).mp (gibbsExp_isUnit β H)
    push_cast
    rw [Matrix.zpow_neg hM, zpow_natCast,
        show -((m : ℝ)) * β = -((m : ℝ) * β) from by ring,
        ← gibbsExp_inv ((m : ℝ) * β) H,
        gibbsExp_natCast_mul]

/-- At `β = 0`, the partition function equals the dimension of the
Hilbert space: `Z(0) = |Λ → Fin 2|`. -/
theorem partitionFn_zero (H : ManyBodyOp Λ) :
    partitionFn 0 H = Fintype.card (Λ → Fin 2) := by
  simp only [partitionFn, gibbsExp_zero, Matrix.trace_one]

/-- The partition function at `β = 0` is nonzero (the dimension is positive).
The configuration space `Λ → Fin 2` is automatically nonempty since
`Fin 2` is nonempty, so no extra hypothesis is needed. -/
theorem partitionFn_zero_ne_zero (H : ManyBodyOp Λ) :
    partitionFn 0 H ≠ 0 := by
  rw [partitionFn_zero]
  exact_mod_cast Fintype.card_pos.ne'

/-- For any Hermitian matrix `A : Matrix n n ℂ`, the trace is real. -/
theorem _root_.Matrix.IsHermitian.trace_im
    {n : Type*} [Fintype n] {A : Matrix n n ℂ} (hA : A.IsHermitian) :
    A.trace.im = 0 := by
  have : star A.trace = A.trace := by
    rw [← Matrix.trace_conjTranspose, hA.eq]
  exact Complex.conj_eq_iff_im.mp this

/-- For a Hermitian Hamiltonian `H`, the partition function
`Z(β) = Tr(e^{-βH})` is real. -/
theorem partitionFn_im_of_isHermitian {H : ManyBodyOp Λ}
    (hH : H.IsHermitian) (β : ℝ) :
    (partitionFn β H).im = 0 :=
  (gibbsExp_isHermitian hH β).trace_im

/-- The Gibbs state purity equals `Z(2β) / Z(β)²`:
`Tr(ρ_β²) = partitionFn (2 β) H / (partitionFn β H)²`. The "purity"
measure of the canonical density matrix; equal to 1 for pure states,
less than 1 for mixed states. The `Z = 0` edge case is handled by
Lean's `1/0 = 0` convention: both sides collapse to zero. -/
theorem gibbsState_mul_self_trace (β : ℝ) (H : ManyBodyOp Λ) :
    (gibbsState β H * gibbsState β H).trace
      = partitionFn (2 * β) H / (partitionFn β H) ^ 2 := by
  unfold gibbsState
  rw [Matrix.smul_mul, Matrix.mul_smul, smul_smul, ← gibbsExp_two_mul,
    Matrix.trace_smul, smul_eq_mul]
  unfold partitionFn
  field_simp

/-- The Gibbs state higher-moment trace identity:
`Tr(ρ_β^n) = Z(nβ) / Z(β)^n` for any `n : ℕ`. The Rényi-n entropy
precursor; expresses the trace of the n-th power of the density matrix
entirely in terms of partition functions evaluated at temperature `n β`.

Edge cases: at `n = 0`, both sides equal `Tr(1) = dim`. At `Z = 0`,
the identity holds by Lean's `1/0 = 0` convention (both sides
collapse to zero for `n ≥ 1`). -/
theorem gibbsState_pow_trace (β : ℝ) (H : ManyBodyOp Λ) (n : ℕ) :
    ((gibbsState β H) ^ n).trace
      = partitionFn ((n : ℝ) * β) H / (partitionFn β H) ^ n := by
  unfold gibbsState partitionFn
  rw [smul_pow, ← gibbsExp_natCast_mul, Matrix.trace_smul, smul_eq_mul,
    one_div, inv_pow, div_eq_inv_mul]

/-- At `β = 0`, the Gibbs state is the maximally mixed state
`ρ_0 = (1 / dim) · I`. -/
theorem gibbsState_zero (H : ManyBodyOp Λ) :
    gibbsState 0 H = ((Fintype.card (Λ → Fin 2) : ℂ))⁻¹ • (1 : ManyBodyOp Λ) := by
  simp only [gibbsState, gibbsExp_zero, partitionFn_zero, one_div]

/-- At `β = 0`, the matrix inverse of the Gibbs state is the dimension
times the identity: `ρ_0⁻¹ = dim · I`. -/
theorem gibbsState_zero_inv (H : ManyBodyOp Λ) :
    (gibbsState 0 H)⁻¹ =
      (Fintype.card (Λ → Fin 2) : ℂ) • (1 : ManyBodyOp Λ) := by
  rw [gibbsState_zero]
  apply Matrix.inv_eq_left_inv
  rw [smul_mul_smul_comm, mul_inv_cancel₀, Matrix.one_mul, one_smul]
  exact_mod_cast Fintype.card_pos.ne'

/-- At `β = 0`, the Gibbs expectation reduces to the normalised trace
`⟨A⟩_0 = (1 / dim) · Tr(A)`. -/
theorem gibbsExpectation_zero (H A : ManyBodyOp Λ) :
    gibbsExpectation 0 H A = ((Fintype.card (Λ → Fin 2) : ℂ))⁻¹ * A.trace := by
  simp only [gibbsExpectation, gibbsState_zero, Matrix.smul_mul, Matrix.one_mul,
    Matrix.trace_smul, smul_eq_mul]

/-! ## Linearity of expectation -/

/-- Expectation is additive: `⟨O₁ + O₂⟩ = ⟨O₁⟩ + ⟨O₂⟩`. -/
theorem gibbsExpectation_add {H : ManyBodyOp Λ} (β : ℝ) (O₁ O₂ : ManyBodyOp Λ) :
    gibbsExpectation β H (O₁ + O₂) = gibbsExpectation β H O₁ + gibbsExpectation β H O₂ := by
  simp only [gibbsExpectation, mul_add, Matrix.trace_add]

/-- Expectation is homogeneous: `⟨c • O⟩ = c • ⟨O⟩`. -/
theorem gibbsExpectation_smul {H : ManyBodyOp Λ} (β : ℝ) (c : ℂ) (O : ManyBodyOp Λ) :
    gibbsExpectation β H (c • O) = c * gibbsExpectation β H O := by
  simp only [gibbsExpectation, Matrix.mul_smul, Matrix.trace_smul, smul_eq_mul]

/-- Expectation negates with the observable: `⟨-O⟩ = -⟨O⟩`. -/
theorem gibbsExpectation_neg {H : ManyBodyOp Λ} (β : ℝ) (O : ManyBodyOp Λ) :
    gibbsExpectation β H (-O) = -gibbsExpectation β H O := by
  simp only [gibbsExpectation, Matrix.mul_neg, Matrix.trace_neg]

/-- Expectation distributes over subtraction: `⟨A - B⟩ = ⟨A⟩ - ⟨B⟩`. -/
theorem gibbsExpectation_sub {H : ManyBodyOp Λ} (β : ℝ) (A B : ManyBodyOp Λ) :
    gibbsExpectation β H (A - B) = gibbsExpectation β H A - gibbsExpectation β H B := by
  rw [sub_eq_add_neg, gibbsExpectation_add, gibbsExpectation_neg, sub_eq_add_neg]

/-- Expectation distributes over a finite sum:
`⟨∑ i ∈ s, f i⟩ = ∑ i ∈ s, ⟨f i⟩`. -/
theorem gibbsExpectation_sum {H : ManyBodyOp Λ} (β : ℝ) {ι : Type*}
    (s : Finset ι) (f : ι → ManyBodyOp Λ) :
    gibbsExpectation β H (∑ i ∈ s, f i) = ∑ i ∈ s, gibbsExpectation β H (f i) := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    simp only [Finset.sum_empty, gibbsExpectation, Matrix.mul_zero, Matrix.trace_zero]
  | @insert a t hat ih =>
    rw [Finset.sum_insert hat, gibbsExpectation_add, ih, Finset.sum_insert hat]

/-! ## Commutativity of the Gibbs state with `H`

The density matrix `ρ_β = exp(-β H)/Z` is a function of `H` (a power
series in `H`), hence commutes with `H`. Equivalently, `ρ_β` is
stationary under the unitary dynamics generated by `H`. See Tasaki
§3.3, p. 80. -/

/-- The Gibbs exponential commutes with the Hamiltonian:
`exp(-β H) · H = H · exp(-β H)`. -/
theorem gibbsExp_commute_hamiltonian (β : ℝ) (H : ManyBodyOp Λ) :
    Commute (gibbsExp β H) H := by
  unfold gibbsExp
  exact (((Commute.refl H).smul_left (-(β : ℂ))).exp_left)

/-- The Gibbs state commutes with the Hamiltonian: `ρ_β · H = H · ρ_β`. -/
theorem gibbsState_commute_hamiltonian (β : ℝ) (H : ManyBodyOp Λ) :
    Commute (gibbsState β H) H := by
  unfold gibbsState
  exact (gibbsExp_commute_hamiltonian β H).smul_left _

/-! ## Reality of expectation for Hermitian observables

For a Hermitian Hamiltonian `H` and Hermitian observable `O`, the
expectation `⟨O⟩_β = Tr(ρ_β O)` is real:
`star ⟨O⟩_β = Tr((ρ_β O)ᴴ) = Tr(Oᴴ ρ_β ᴴ) = Tr(O ρ_β) = Tr(ρ_β O)
            = ⟨O⟩_β`,
combining `Matrix.trace_conjTranspose`, Hermiticity of `ρ_β` and `O`,
and the cyclic property `Matrix.trace_mul_comm`. See Tasaki §3.3, p. 80. -/

/-- For Hermitian matrices `A`, `B` over `ℂ`, the trace `Tr(A · B)`
is invariant under complex conjugation. This is the algebraic core of
the reality of Gibbs expectations and is independent of the Gibbs
construction. -/
theorem _root_.Matrix.trace_mul_star_of_isHermitian
    {n : Type*} [Fintype n] {A B : Matrix n n ℂ}
    (hA : A.IsHermitian) (hB : B.IsHermitian) :
    star (A * B).trace = (A * B).trace := by
  rw [← Matrix.trace_conjTranspose, Matrix.conjTranspose_mul, hB.eq, hA.eq,
    Matrix.trace_mul_comm]

/-- For Hermitian `H` and Hermitian observable `O`, the Gibbs expectation
is invariant under complex conjugation, i.e. `star ⟨O⟩_β = ⟨O⟩_β`. -/
theorem gibbsExpectation_star_of_isHermitian {H O : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hO : O.IsHermitian) (β : ℝ) :
    star (gibbsExpectation β H O) = gibbsExpectation β H O :=
  Matrix.trace_mul_star_of_isHermitian (gibbsState_isHermitian hH β) hO

/-- For Hermitian `H` and Hermitian observable `O`, the imaginary part of
the Gibbs expectation vanishes: `(⟨O⟩_β).im = 0`. -/
theorem gibbsExpectation_im_of_isHermitian {H O : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hO : O.IsHermitian) (β : ℝ) :
    (gibbsExpectation β H O).im = 0 :=
  Complex.conj_eq_iff_im.mp (gibbsExpectation_star_of_isHermitian hH hO β)

/-- For Hermitian `H` and Hermitian observable `O`, the Gibbs expectation
equals the complex embedding of its real part:
`((⟨O⟩_β).re : ℂ) = ⟨O⟩_β`. The imaginary part vanishes by
`gibbsExpectation_im_of_isHermitian`; `Complex.ext` then reduces
the goal to its real and imaginary components, both discharged
by `simp` after rewriting with the realness hypothesis. -/
theorem gibbsExpectation_ofReal_re_eq_of_isHermitian {H O : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hO : O.IsHermitian) (β : ℝ) :
    ((gibbsExpectation β H O).re : ℂ) = gibbsExpectation β H O := by
  have him := gibbsExpectation_im_of_isHermitian hH hO β
  apply Complex.ext <;> simp [him]

/-! ## Conservation laws

Since `[ρ_β, H] = 0`, the Gibbs expectation of any commutator with the
Hamiltonian vanishes:

  `⟨[H, A]⟩_β = Tr(ρ (HA - AH)) = Tr(Hρ A) - Tr(ρ AH)
              = Tr(ρ AH) - Tr(ρ AH) = 0`,

using `gibbsState_commute_hamiltonian` and the cyclic property of the
trace `Matrix.trace_mul_comm`. Equivalently, `⟨HA⟩_β = ⟨AH⟩_β` for any
observable `A`. See Tasaki §3.3, p. 80. -/

/-- The Hamiltonian and any observable can be exchanged inside the
Gibbs expectation: `⟨H · A⟩_β = ⟨A · H⟩_β`. -/
theorem gibbsExpectation_mul_hamiltonian_comm (β : ℝ) (H A : ManyBodyOp Λ) :
    gibbsExpectation β H (H * A) = gibbsExpectation β H (A * H) := by
  unfold gibbsExpectation
  rw [← Matrix.mul_assoc, (gibbsState_commute_hamiltonian β H).eq,
    Matrix.mul_assoc, Matrix.trace_mul_comm, Matrix.mul_assoc]

/-- Generalisation of `gibbsExpectation_mul_hamiltonian_comm` to any
conserved quantity `A`: when `[A, H] = 0`, `⟨A · O⟩_β = ⟨O · A⟩_β`
for any observable `O`. The Gibbs state inherits the commutativity:
`A` commutes with `gibbsExp β H` (via `Commute.exp_right`), and a
fortiori with `gibbsState β H = (1/Z) • gibbsExp β H`. -/
theorem gibbsExpectation_mul_comm_of_commute_hamiltonian (β : ℝ)
    {H A : ManyBodyOp Λ} (hA : Commute A H) (O : ManyBodyOp Λ) :
    gibbsExpectation β H (A * O) = gibbsExpectation β H (O * A) := by
  have hρ : Commute A (gibbsState β H) :=
    ((hA.smul_right (-(β : ℂ))).exp_right).smul_right _
  unfold gibbsExpectation
  rw [← Matrix.mul_assoc, hρ.eq.symm, Matrix.mul_assoc,
    Matrix.trace_mul_comm, Matrix.mul_assoc]

/-- The Gibbs expectation of any commutator with the Hamiltonian vanishes:
`⟨[H, A]⟩_β = 0`. -/
theorem gibbsExpectation_commutator_hamiltonian (β : ℝ) (H A : ManyBodyOp Λ) :
    gibbsExpectation β H (H * A - A * H) = 0 := by
  rw [sub_eq_add_neg, ← neg_one_smul ℂ (A * H), gibbsExpectation_add,
    gibbsExpectation_smul, gibbsExpectation_mul_hamiltonian_comm]
  ring

/-- For a Hermitian Hamiltonian `H`, the energy expectation `⟨H⟩_β` is real. -/
theorem gibbsExpectation_hamiltonian_im {H : ManyBodyOp Λ}
    (hH : H.IsHermitian) (β : ℝ) :
    (gibbsExpectation β H H).im = 0 :=
  gibbsExpectation_im_of_isHermitian hH hH β

/-- For Hermitian `H` and Hermitian observable `O`, the second-moment
expectation `⟨O · O⟩_β` is real. The product `O · O` is Hermitian
because `O` commutes with itself; the result then specialises
`gibbsExpectation_im_of_isHermitian`. -/
theorem gibbsExpectation_sq_im_of_isHermitian {H O : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hO : O.IsHermitian) (β : ℝ) :
    (gibbsExpectation β H (O * O)).im = 0 :=
  gibbsExpectation_im_of_isHermitian hH
    (Matrix.IsHermitian.mul_of_commute hO hO (Commute.refl O)) β

/-- For Hermitian `H`, Hermitian `O`, and any `n : ℕ`,
`(⟨O ^ n⟩_β).im = 0`. Generalises `gibbsExpectation_sq_im_of_isHermitian`
to arbitrary natural powers via `Matrix.IsHermitian.pow`. -/
theorem gibbsExpectation_pow_im_of_isHermitian {H O : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hO : O.IsHermitian) (β : ℝ) (n : ℕ) :
    (gibbsExpectation β H (O ^ n)).im = 0 :=
  gibbsExpectation_im_of_isHermitian hH (hO.pow n) β

/-! ## Variance -/

/-- The canonical-ensemble variance of an observable `O` at inverse
temperature `β` under Hamiltonian `H`:
`Var_β(O) := ⟨O²⟩_β − (⟨O⟩_β)²`. -/
noncomputable def gibbsVariance (β : ℝ) (H O : ManyBodyOp Λ) : ℂ :=
  gibbsExpectation β H (O * O) - (gibbsExpectation β H O) ^ 2

/-- Unfolding lemma: `Var_β(O) = ⟨O · O⟩_β − ⟨O⟩_β²`. -/
theorem gibbsVariance_eq (β : ℝ) (H O : ManyBodyOp Λ) :
    gibbsVariance β H O =
      gibbsExpectation β H (O * O) - (gibbsExpectation β H O) ^ 2 :=
  rfl

/-- For Hermitian Gibbs `H` and Hermitian observable `O`, the variance
is real. The second moment is real by `gibbsExpectation_sq_im_of_isHermitian`,
the squared first moment by squaring a real complex number, and the
difference of two reals is real. -/
theorem gibbsVariance_im_of_isHermitian {H O : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hO : O.IsHermitian) (β : ℝ) :
    (gibbsVariance β H O).im = 0 := by
  unfold gibbsVariance
  have h1 : (gibbsExpectation β H (O * O)).im = 0 :=
    gibbsExpectation_sq_im_of_isHermitian hH hO β
  have h2 : (gibbsExpectation β H O).im = 0 :=
    gibbsExpectation_im_of_isHermitian hH hO β
  have h2sq : ((gibbsExpectation β H O) ^ 2).im = 0 := by
    rw [pow_two, Complex.mul_im, h2, zero_mul, mul_zero, add_zero]
  rw [Complex.sub_im, h1, h2sq, sub_zero]

/-- At `β = 0`, the variance reduces to the normalised-trace formula
`Var_0(O) = (1/dim) · Tr(O²) − ((1/dim) · Tr O)²`. -/
theorem gibbsVariance_zero (H O : ManyBodyOp Λ) :
    gibbsVariance 0 H O =
      ((Fintype.card (Λ → Fin 2) : ℂ))⁻¹ * (O * O).trace
        - (((Fintype.card (Λ → Fin 2) : ℂ))⁻¹ * O.trace) ^ 2 := by
  unfold gibbsVariance
  rw [gibbsExpectation_zero, gibbsExpectation_zero]

/-- The variance equals the second moment of the centered observable
`Ô := O − ⟨O⟩ · 1`:
`Var_β(O) = ⟨(O − ⟨O⟩_β · 1) · (O − ⟨O⟩_β · 1)⟩_β` (when `Z(β) ≠ 0`). -/
theorem gibbsVariance_eq_centered_sq {H O : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) :
    gibbsExpectation β H ((O - (gibbsExpectation β H O) • (1 : ManyBodyOp Λ)) *
        (O - (gibbsExpectation β H O) • 1)) = gibbsVariance β H O := by
  set c := gibbsExpectation β H O with hc
  have hsq : (O - c • (1 : ManyBodyOp Λ)) * (O - c • 1) =
             O * O - c • O - c • O + (c * c) • (1 : ManyBodyOp Λ) := by
    simp only [sub_mul, mul_sub, Matrix.smul_mul, Matrix.mul_smul,
      Matrix.one_mul, Matrix.mul_one, smul_smul]
    abel
  rw [hsq]
  simp only [gibbsExpectation_add, gibbsExpectation_sub, gibbsExpectation_smul]
  rw [show gibbsExpectation β H 1 = 1 from gibbsExpectation_one β hZ]
  unfold gibbsVariance
  rw [pow_two, ← hc]
  ring

/-! ## Covariance -/

/-- The canonical-ensemble covariance of two observables `A`, `B` at
inverse temperature `β` under Hamiltonian `H`:
`Cov_β(A, B) := ⟨A · B⟩_β − ⟨A⟩_β · ⟨B⟩_β`. -/
noncomputable def gibbsCovariance (β : ℝ) (H A B : ManyBodyOp Λ) : ℂ :=
  gibbsExpectation β H (A * B) - gibbsExpectation β H A * gibbsExpectation β H B

/-- Unfolding lemma:
`Cov_β(A, B) = ⟨A · B⟩_β − ⟨A⟩_β · ⟨B⟩_β`. -/
theorem gibbsCovariance_eq (β : ℝ) (H A B : ManyBodyOp Λ) :
    gibbsCovariance β H A B =
      gibbsExpectation β H (A * B)
        - gibbsExpectation β H A * gibbsExpectation β H B :=
  rfl

/-- Self-covariance is the variance:
`Cov_β(O, O) = Var_β(O)`. -/
theorem gibbsCovariance_self_eq_variance (β : ℝ) (H O : ManyBodyOp Λ) :
    gibbsCovariance β H O O = gibbsVariance β H O := by
  unfold gibbsCovariance gibbsVariance
  rw [pow_two]

/-- The antisymmetric part of the complex covariance equals the
commutator expectation:
`Cov_β(A, B) − Cov_β(B, A) = ⟨A · B − B · A⟩_β`.
The product terms `⟨A⟩ · ⟨B⟩` cancel, isolating the noncommutativity
of `A` and `B`. -/
theorem gibbsCovariance_sub_swap_eq_commutator (β : ℝ) (H A B : ManyBodyOp Λ) :
    gibbsCovariance β H A B - gibbsCovariance β H B A
      = gibbsExpectation β H (A * B - B * A) := by
  unfold gibbsCovariance
  rw [gibbsExpectation_sub]
  ring

/-! ### Bilinearity of the complex covariance -/

/-- Additivity in the left argument:
`Cov_β(A₁ + A₂, B) = Cov_β(A₁, B) + Cov_β(A₂, B)`. -/
theorem gibbsCovariance_add_left (β : ℝ) (H A₁ A₂ B : ManyBodyOp Λ) :
    gibbsCovariance β H (A₁ + A₂) B
      = gibbsCovariance β H A₁ B + gibbsCovariance β H A₂ B := by
  unfold gibbsCovariance
  rw [add_mul, gibbsExpectation_add, gibbsExpectation_add]
  ring

/-- Additivity in the right argument:
`Cov_β(A, B₁ + B₂) = Cov_β(A, B₁) + Cov_β(A, B₂)`. -/
theorem gibbsCovariance_add_right (β : ℝ) (H A B₁ B₂ : ManyBodyOp Λ) :
    gibbsCovariance β H A (B₁ + B₂)
      = gibbsCovariance β H A B₁ + gibbsCovariance β H A B₂ := by
  unfold gibbsCovariance
  rw [mul_add, gibbsExpectation_add, gibbsExpectation_add]
  ring

/-- Scalar pull-out from the left argument:
`Cov_β(c • A, B) = c · Cov_β(A, B)`. -/
theorem gibbsCovariance_smul_left (β : ℝ) (H : ManyBodyOp Λ) (c : ℂ)
    (A B : ManyBodyOp Λ) :
    gibbsCovariance β H (c • A) B = c * gibbsCovariance β H A B := by
  unfold gibbsCovariance
  rw [Matrix.smul_mul, gibbsExpectation_smul, gibbsExpectation_smul]
  ring

/-- Scalar pull-out from the right argument:
`Cov_β(A, c • B) = c · Cov_β(A, B)`. -/
theorem gibbsCovariance_smul_right (β : ℝ) (H A : ManyBodyOp Λ) (c : ℂ)
    (B : ManyBodyOp Λ) :
    gibbsCovariance β H A (c • B) = c * gibbsCovariance β H A B := by
  unfold gibbsCovariance
  rw [Matrix.mul_smul, gibbsExpectation_smul, gibbsExpectation_smul]
  ring

/-! #### Vanishing on constant-scalar arguments -/

/-- The complex covariance vanishes when its left argument is a scalar
multiple of the identity, provided `Z(β) ≠ 0`. -/
theorem gibbsCovariance_const_smul_one_left_eq_zero {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) (c : ℂ) (B : ManyBodyOp Λ) :
    gibbsCovariance β H (c • (1 : ManyBodyOp Λ)) B = 0 := by
  unfold gibbsCovariance
  rw [Matrix.smul_mul, Matrix.one_mul, gibbsExpectation_smul,
    gibbsExpectation_smul, gibbsExpectation_one β hZ, mul_one]
  ring

/-- The complex covariance vanishes when its right argument is a scalar
multiple of the identity, provided `Z(β) ≠ 0`. -/
theorem gibbsCovariance_const_smul_one_right_eq_zero {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) (A : ManyBodyOp Λ) (c : ℂ) :
    gibbsCovariance β H A (c • (1 : ManyBodyOp Λ)) = 0 := by
  unfold gibbsCovariance
  rw [Matrix.mul_smul, Matrix.mul_one, gibbsExpectation_smul,
    gibbsExpectation_smul, gibbsExpectation_one β hZ, mul_one]
  ring

/-! ## Anticommutator real, commutator purely imaginary

For Hermitian `ρ` and arbitrary `X`,
  `star Tr(ρ · X) = Tr((ρ · X)ᴴ) = Tr(Xᴴ · ρ) = Tr(ρ · Xᴴ)`,
combining `trace_conjTranspose`, `conjTranspose_mul`, Hermiticity of
`ρ`, and the cyclic property `Matrix.trace_mul_comm`. Specialising
`X = A · B` with `A, B` Hermitian gives
`star ⟨A · B⟩_β = ⟨B · A⟩_β`. From this, `⟨A·B + B·A⟩_β` (an "anti-
commutator") is `z + star z = 2·Re z`, hence real, and `⟨A·B − B·A⟩_β`
is `z − star z = 2 i·Im z`, hence purely imaginary. -/

/-- For Hermitian `ρ : Matrix n n ℂ` and arbitrary `X`,
`star Tr(ρ · X) = Tr(ρ · Xᴴ)`. -/
theorem _root_.Matrix.trace_mul_conjTranspose_swap_of_isHermitian
    {n : Type*} [Fintype n] {ρ : Matrix n n ℂ} (hρ : ρ.IsHermitian)
    (X : Matrix n n ℂ) :
    star (ρ * X).trace = (ρ * X.conjTranspose).trace := by
  rw [← Matrix.trace_conjTranspose, Matrix.conjTranspose_mul, hρ.eq,
    Matrix.trace_mul_comm]

/-- For Hermitian `H` and Hermitian `A, B`,
`star ⟨A · B⟩_β = ⟨B · A⟩_β`. -/
theorem gibbsExpectation_star_swap_of_isHermitian {H A B : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hA : A.IsHermitian) (hB : B.IsHermitian) (β : ℝ) :
    star (gibbsExpectation β H (A * B)) = gibbsExpectation β H (B * A) := by
  unfold gibbsExpectation
  rw [Matrix.trace_mul_conjTranspose_swap_of_isHermitian
        (gibbsState_isHermitian hH β) (A * B),
      Matrix.conjTranspose_mul, hA.eq, hB.eq]

/-- For Hermitian `H` and Hermitian `A, B`, the anticommutator
expectation `⟨A · B + B · A⟩_β` is real. -/
theorem gibbsExpectation_anticommutator_im {H A B : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hA : A.IsHermitian) (hB : B.IsHermitian) (β : ℝ) :
    (gibbsExpectation β H (A * B + B * A)).im = 0 := by
  rw [gibbsExpectation_add, ← gibbsExpectation_star_swap_of_isHermitian hH hA hB β,
    Complex.add_im, Complex.star_def, Complex.conj_im, add_neg_cancel]

/-- For Hermitian `H` and Hermitian `A, B`, the commutator expectation
`⟨A · B − B · A⟩_β` is purely imaginary. -/
theorem gibbsExpectation_commutator_re {H A B : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hA : A.IsHermitian) (hB : B.IsHermitian) (β : ℝ) :
    (gibbsExpectation β H (A * B - B * A)).re = 0 := by
  rw [sub_eq_add_neg, ← neg_one_smul ℂ (B * A), gibbsExpectation_add,
    gibbsExpectation_smul,
    ← gibbsExpectation_star_swap_of_isHermitian hH hA hB β]
  simp [Complex.add_re, Complex.conj_re]

/-- For Hermitian `H` and Hermitian observable `O`,
`(⟨H · O⟩_β).im = 0`, i.e.\ the expectation of the (generally
non-Hermitian) product `H · O` is real. -/
theorem gibbsExpectation_mul_hamiltonian_im {H O : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hO : O.IsHermitian) (β : ℝ) :
    (gibbsExpectation β H (H * O)).im = 0 := by
  have hcomm := gibbsExpectation_mul_hamiltonian_comm β H O
  have hstar := gibbsExpectation_star_swap_of_isHermitian hH hH hO β
  have : star (gibbsExpectation β H (H * O)) = gibbsExpectation β H (H * O) := by
    rw [hstar, ← hcomm]
  exact Complex.conj_eq_iff_im.mp this

/-! ## Symmetric covariance (real-valued for Hermitian observables) -/

/-- The symmetric (real-valued for Hermitian observables) canonical
covariance: `Cov^s_β(A, B) := (1/2) · ⟨A · B + B · A⟩_β − ⟨A⟩_β · ⟨B⟩_β`.
The complex covariance `gibbsCovariance` for non-commuting Hermitian
observables generally has a nonzero imaginary part; averaging over the
anticommutator restores realness. -/
noncomputable def gibbsCovarianceSymm (β : ℝ) (H A B : ManyBodyOp Λ) : ℂ :=
  (2 : ℂ)⁻¹ * gibbsExpectation β H (A * B + B * A)
    - gibbsExpectation β H A * gibbsExpectation β H B

/-- Unfolding lemma:
`Cov^s_β(A, B) = (1/2) · ⟨A · B + B · A⟩_β − ⟨A⟩_β · ⟨B⟩_β`. -/
theorem gibbsCovarianceSymm_eq (β : ℝ) (H A B : ManyBodyOp Λ) :
    gibbsCovarianceSymm β H A B =
      (2 : ℂ)⁻¹ * gibbsExpectation β H (A * B + B * A)
        - gibbsExpectation β H A * gibbsExpectation β H B :=
  rfl

/-- Self symmetric-covariance is the variance:
`Cov^s_β(O, O) = Var_β(O)`. The anticommutator `O · O + O · O = 2(O · O)`
collapses the (1/2) prefactor. -/
theorem gibbsCovarianceSymm_self_eq_variance (β : ℝ) (H O : ManyBodyOp Λ) :
    gibbsCovarianceSymm β H O O = gibbsVariance β H O := by
  unfold gibbsCovarianceSymm gibbsVariance
  have h2 : O * O + O * O = (2 : ℂ) • (O * O) := by
    rw [two_smul]
  rw [h2, gibbsExpectation_smul, ← mul_assoc, inv_mul_cancel₀ two_ne_zero,
    one_mul, pow_two]

/-- The symmetric covariance is symmetric in its observable arguments:
`Cov^s_β(A, B) = Cov^s_β(B, A)`. The anticommutator
`A · B + B · A = B · A + A · B` is unchanged under swap, and the product
`⟨A⟩ · ⟨B⟩ = ⟨B⟩ · ⟨A⟩` is commutative in `ℂ`. -/
theorem gibbsCovarianceSymm_comm (β : ℝ) (H A B : ManyBodyOp Λ) :
    gibbsCovarianceSymm β H A B = gibbsCovarianceSymm β H B A := by
  unfold gibbsCovarianceSymm
  rw [add_comm (A * B) (B * A), mul_comm (gibbsExpectation β H A)]

/-! #### Bilinearity of the symmetric covariance -/

/-- Additivity in the left argument:
`Cov^s_β(A₁ + A₂, B) = Cov^s_β(A₁, B) + Cov^s_β(A₂, B)`. -/
theorem gibbsCovarianceSymm_add_left (β : ℝ) (H A₁ A₂ B : ManyBodyOp Λ) :
    gibbsCovarianceSymm β H (A₁ + A₂) B
      = gibbsCovarianceSymm β H A₁ B + gibbsCovarianceSymm β H A₂ B := by
  unfold gibbsCovarianceSymm
  have hexp : (A₁ + A₂) * B + B * (A₁ + A₂)
              = (A₁ * B + B * A₁) + (A₂ * B + B * A₂) := by
    rw [add_mul, mul_add]; abel
  rw [hexp, gibbsExpectation_add, gibbsExpectation_add,
      gibbsExpectation_add (β := β) (H := H) A₁ A₂]
  ring

/-- Additivity in the right argument:
`Cov^s_β(A, B₁ + B₂) = Cov^s_β(A, B₁) + Cov^s_β(A, B₂)`. -/
theorem gibbsCovarianceSymm_add_right (β : ℝ) (H A B₁ B₂ : ManyBodyOp Λ) :
    gibbsCovarianceSymm β H A (B₁ + B₂)
      = gibbsCovarianceSymm β H A B₁ + gibbsCovarianceSymm β H A B₂ := by
  rw [gibbsCovarianceSymm_comm β H A (B₁ + B₂),
      gibbsCovarianceSymm_add_left,
      gibbsCovarianceSymm_comm β H B₁ A, gibbsCovarianceSymm_comm β H B₂ A]

/-- Scalar pull-out from the left argument:
`Cov^s_β(c • A, B) = c · Cov^s_β(A, B)`. -/
theorem gibbsCovarianceSymm_smul_left (β : ℝ) (H : ManyBodyOp Λ) (c : ℂ)
    (A B : ManyBodyOp Λ) :
    gibbsCovarianceSymm β H (c • A) B = c * gibbsCovarianceSymm β H A B := by
  unfold gibbsCovarianceSymm
  have hexp : (c • A) * B + B * (c • A) = c • (A * B + B * A) := by
    rw [Matrix.smul_mul, Matrix.mul_smul, smul_add]
  rw [hexp, gibbsExpectation_smul, gibbsExpectation_smul]
  ring

/-- Scalar pull-out from the right argument:
`Cov^s_β(A, c • B) = c · Cov^s_β(A, B)`. -/
theorem gibbsCovarianceSymm_smul_right (β : ℝ) (H A : ManyBodyOp Λ) (c : ℂ)
    (B : ManyBodyOp Λ) :
    gibbsCovarianceSymm β H A (c • B) = c * gibbsCovarianceSymm β H A B := by
  rw [gibbsCovarianceSymm_comm β H A (c • B),
      gibbsCovarianceSymm_smul_left,
      gibbsCovarianceSymm_comm β H B A]

/-- The sum-of-observables variance identity:
`Var_β(A + B) = Var_β(A) + Var_β(B) + 2 · Cov^s_β(A, B)`.
The cross term is the symmetric covariance (averaged anticommutator);
for commuting `A, B` it reduces to `2·Cov(A, B)`. -/
theorem gibbsVariance_add (β : ℝ) (H A B : ManyBodyOp Λ) :
    gibbsVariance β H (A + B)
      = gibbsVariance β H A + gibbsVariance β H B
        + 2 * gibbsCovarianceSymm β H A B := by
  unfold gibbsVariance gibbsCovarianceSymm
  have hexpand : (A + B) * (A + B) = A * A + A * B + B * A + B * B := by
    rw [add_mul, mul_add, mul_add]; abel
  rw [hexpand]
  simp only [gibbsExpectation_add]
  ring

/-! #### Variance under scalar / negation / constant shift -/

/-- Variance of the identity is zero when `Z ≠ 0`:
`Var_β(1) = ⟨1⟩ - ⟨1⟩² = 1 - 1 = 0`. -/
theorem gibbsVariance_one {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) :
    gibbsVariance β H 1 = 0 := by
  unfold gibbsVariance
  rw [Matrix.one_mul, gibbsExpectation_one β hZ]
  ring

/-- Variance scales as the square: `Var_β(c • A) = c² · Var_β(A)`. -/
theorem gibbsVariance_smul (β : ℝ) (H : ManyBodyOp Λ) (c : ℂ) (A : ManyBodyOp Λ) :
    gibbsVariance β H (c • A) = c ^ 2 * gibbsVariance β H A := by
  unfold gibbsVariance
  rw [Matrix.smul_mul, Matrix.mul_smul, smul_smul, gibbsExpectation_smul,
    gibbsExpectation_smul]
  ring

/-- Variance of a scalar multiple of the identity is zero
(when `Z ≠ 0`): `Var_β(c • 1) = c² · 0 = 0`. -/
theorem gibbsVariance_smul_one {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) (c : ℂ) :
    gibbsVariance β H (c • (1 : ManyBodyOp Λ)) = 0 := by
  rw [gibbsVariance_smul, gibbsVariance_one β hZ, mul_zero]

/-- Variance is invariant under negation: `Var_β(−A) = Var_β(A)`.
Specialisation of `gibbsVariance_smul` at `c = −1`. -/
theorem gibbsVariance_neg (β : ℝ) (H A : ManyBodyOp Λ) :
    gibbsVariance β H (-A) = gibbsVariance β H A := by
  rw [show -A = ((-1 : ℂ)) • A by simp]
  rw [gibbsVariance_smul]
  ring

/-- Variance is invariant under a constant additive shift
(when `Z ≠ 0`): `Var_β(A + c • 1) = Var_β(A)`. -/
theorem gibbsVariance_add_const_smul_one {H : ManyBodyOp Λ} (β : ℝ)
    (hZ : partitionFn β H ≠ 0) (A : ManyBodyOp Λ) (c : ℂ) :
    gibbsVariance β H (A + c • (1 : ManyBodyOp Λ)) = gibbsVariance β H A := by
  unfold gibbsVariance
  have hexp_self : (A + c • (1 : ManyBodyOp Λ)) * (A + c • 1)
                 = A * A + c • A + c • A + (c * c) • (1 : ManyBodyOp Λ) := by
    simp only [add_mul, mul_add, Matrix.smul_mul, Matrix.mul_smul,
      Matrix.one_mul, Matrix.mul_one, smul_smul]
    abel
  rw [hexp_self]
  simp only [gibbsExpectation_add, gibbsExpectation_smul,
    gibbsExpectation_one β hZ]
  ring

/-! #### Symmetric / antisymmetric decomposition -/

/-- The complex covariance decomposes into its symmetric part plus
half the commutator expectation:
`Cov_β(A, B) = Cov^s_β(A, B) + (1/2) · ⟨A · B − B · A⟩_β`. -/
theorem gibbsCovariance_eq_symm_add_half_commutator
    (β : ℝ) (H A B : ManyBodyOp Λ) :
    gibbsCovariance β H A B
      = gibbsCovarianceSymm β H A B
        + (2 : ℂ)⁻¹ * gibbsExpectation β H (A * B - B * A) := by
  unfold gibbsCovariance gibbsCovarianceSymm
  rw [gibbsExpectation_sub, gibbsExpectation_add]
  ring

/-- The symmetric covariance is the symmetrisation of the complex
covariance:
`Cov^s_β(A, B) = (1/2) · (Cov_β(A, B) + Cov_β(B, A))`. -/
theorem gibbsCovarianceSymm_eq_half_add_swap
    (β : ℝ) (H A B : ManyBodyOp Λ) :
    gibbsCovarianceSymm β H A B
      = (2 : ℂ)⁻¹ * (gibbsCovariance β H A B + gibbsCovariance β H B A) := by
  unfold gibbsCovariance gibbsCovarianceSymm
  rw [gibbsExpectation_add]
  ring

/-- For commuting observables `A, B`, the complex covariance equals
the symmetric covariance: `Cov_β(A, B) = Cov^s_β(A, B)`. The
commutator-based antisymmetric part vanishes when `[A, B] = 0`. -/
theorem gibbsCovariance_eq_symm_of_commute (β : ℝ) (H : ManyBodyOp Λ)
    {A B : ManyBodyOp Λ} (h : Commute A B) :
    gibbsCovariance β H A B = gibbsCovarianceSymm β H A B := by
  rw [gibbsCovariance_eq_symm_add_half_commutator]
  have hzero : A * B - B * A = 0 := by rw [h.eq, sub_self]
  rw [hzero]
  unfold gibbsExpectation
  rw [Matrix.mul_zero, Matrix.trace_zero, mul_zero, add_zero]

/-- The symmetric covariance vanishes when its left argument is a
scalar multiple of the identity, provided `Z(β) ≠ 0`. Direct
corollary of `gibbsCovariance_const_smul_one_left_eq_zero` /
`_right_eq_zero` via the symmetrisation identity. -/
theorem gibbsCovarianceSymm_const_smul_one_left_eq_zero {H : ManyBodyOp Λ}
    (β : ℝ) (hZ : partitionFn β H ≠ 0) (c : ℂ) (B : ManyBodyOp Λ) :
    gibbsCovarianceSymm β H (c • (1 : ManyBodyOp Λ)) B = 0 := by
  rw [gibbsCovarianceSymm_eq_half_add_swap,
    gibbsCovariance_const_smul_one_left_eq_zero β hZ,
    gibbsCovariance_const_smul_one_right_eq_zero β hZ]
  ring

/-- The symmetric covariance vanishes when its right argument is a
scalar multiple of the identity, provided `Z(β) ≠ 0`. -/
theorem gibbsCovarianceSymm_const_smul_one_right_eq_zero {H : ManyBodyOp Λ}
    (β : ℝ) (hZ : partitionFn β H ≠ 0) (A : ManyBodyOp Λ) (c : ℂ) :
    gibbsCovarianceSymm β H A (c • (1 : ManyBodyOp Λ)) = 0 := by
  rw [gibbsCovarianceSymm_comm,
    gibbsCovarianceSymm_const_smul_one_left_eq_zero β hZ]

/-- For Hermitian `H` and Hermitian `A, B`, the symmetric covariance
is real. The anticommutator term is real by
`gibbsExpectation_anticommutator_im` (the (1/2) prefactor preserves
realness), and `⟨A⟩ · ⟨B⟩` is the product of two real complex numbers. -/
theorem gibbsCovarianceSymm_im_of_isHermitian {H A B : ManyBodyOp Λ}
    (hH : H.IsHermitian) (hA : A.IsHermitian) (hB : B.IsHermitian) (β : ℝ) :
    (gibbsCovarianceSymm β H A B).im = 0 := by
  unfold gibbsCovarianceSymm
  have h_anti : (gibbsExpectation β H (A * B + B * A)).im = 0 :=
    gibbsExpectation_anticommutator_im hH hA hB β
  have h_a : (gibbsExpectation β H A).im = 0 :=
    gibbsExpectation_im_of_isHermitian hH hA β
  have h_b : (gibbsExpectation β H B).im = 0 :=
    gibbsExpectation_im_of_isHermitian hH hB β
  have h_prod : (gibbsExpectation β H A * gibbsExpectation β H B).im = 0 := by
    rw [Complex.mul_im, h_a, h_b, zero_mul, mul_zero, add_zero]
  have h_inv : ((2 : ℂ)⁻¹).im = 0 := by simp
  have h_half : ((2 : ℂ)⁻¹ * gibbsExpectation β H (A * B + B * A)).im = 0 := by
    rw [Complex.mul_im, h_inv, h_anti, mul_zero, zero_mul, add_zero]
  rw [Complex.sub_im, h_half, h_prod, sub_zero]

end LatticeSystem.Quantum
