import LatticeSystem.Quantum.SU2Integral
import LatticeSystem.Quantum.TotalSpin.Rotation
import LatticeSystem.Quantum.SpinHalfRotation.Conjugation

/-!
# Tasaki Problem 2.2.c: the rotated `|↑⟩₁|↓⟩₂` is determined by `n` alone (pp. 23-24)

Tasaki *Physics and Mathematics of Quantum Many-Body Systems* (1st ed., Springer, 2020), §2.2,
Problem 2.2.c, pp. 23-24 (footnote 16, p. 23; footnote 17, p. 24; solution p. 496, eq. (S.16)).

Fix a unit vector `n ∈ ℝ³` and let `Û` be *any* uniform rotation of the two-spin system in the
class of footnote 16 — an arbitrary finite product of the global rotations
`Û_θ^{(α)} = exp(−iθ Ŝ_tot^{(α)})` (eq. (2.2.11), p. 22) over axes `α = 1, 2, 3` and angles `θ` —
such that `Û Ŝ_x^{(3)} Û† = Ŝ_x · n` at both sites `x = 1, 2`. Problem 2.2.c asks to show that
`Û |↑⟩₁|↓⟩₂` is determined solely by `n`, i.e. does not depend on the particular choice of `Û`
within that class. This module states that conclusion pairwise: any two admissible rotations `U`,
`V` with the same `n` send `|↑⟩₁|↓⟩₂` to the same vector. The printed hypothesis `‖n‖ = 1` is not
used by the proof; only the doc comment records that it is unused, the theorem statement does not
drop it as a stated conclusion.
-/

namespace LatticeSystem.Quantum

/-- Every element of the footnote-16 class of Tasaki's Problem 2.2.c (pp. 23-24; footnote 16,
p. 23), the submonoid generated by the global rotations `exp(−iθ Ŝ_tot^{(α)})` of eq. (2.2.11),
p. 22, on two sites, is a uniform product `u ⊗ u = onSite 0 u * onSite 1 u` with `u ∈ SU(2)`:
each generator factors site by site into the single-spin rotation, and site-`0` and site-`1`
factors commute, so products of such operators stay of this form. -/
private theorem mem_uniformRotClosure_exists_su2 {U : ManyBodyOp (Fin 2)}
    (hU : U ∈ Submonoid.closure (Set.range fun p : Fin 3 × ℝ =>
      NormedSpace.exp ((-(Complex.I * (p.2 : ℂ))) •
        ![totalSpinHalfOp1 (Fin 2), totalSpinHalfOp2 (Fin 2), totalSpinHalfOp3 (Fin 2)] p.1))) :
    ∃ u ∈ SU2, U = onSite (0 : Fin 2) u * onSite (1 : Fin 2) u := by
  induction hU using Submonoid.closure_induction with
  | mem x hx =>
    obtain ⟨⟨α, θ⟩, rfl⟩ := hx
    fin_cases α
    · change ∃ u ∈ SU2, NormedSpace.exp ((-(Complex.I * (θ : ℂ))) • totalSpinHalfOp1 (Fin 2)) =
        onSite (0 : Fin 2) u * onSite (1 : Fin 2) u
      rw [← totalSpinHalfRot1_eq_exp, totalSpinHalfRot1_two_site]
      exact ⟨_, spinHalfRot1_mem_SU2 θ, rfl⟩
    · change ∃ u ∈ SU2, NormedSpace.exp ((-(Complex.I * (θ : ℂ))) • totalSpinHalfOp2 (Fin 2)) =
        onSite (0 : Fin 2) u * onSite (1 : Fin 2) u
      rw [← totalSpinHalfRot2_eq_exp, totalSpinHalfRot2_two_site]
      exact ⟨_, spinHalfRot2_mem_SU2 θ, rfl⟩
    · change ∃ u ∈ SU2, NormedSpace.exp ((-(Complex.I * (θ : ℂ))) • totalSpinHalfOp3 (Fin 2)) =
        onSite (0 : Fin 2) u * onSite (1 : Fin 2) u
      rw [← totalSpinHalfRot3_eq_exp, totalSpinHalfRot3_two_site]
      exact ⟨_, spinHalfRot3_mem_SU2 θ, rfl⟩
  | one => exact ⟨1, one_mem _, by rw [onSite_one, onSite_one, one_mul]⟩
  | mul a b _ _ ha hb =>
    obtain ⟨u, hu, rfl⟩ := ha
    obtain ⟨v, hv, rfl⟩ := hb
    refine ⟨u * v, mul_mem hu hv, ?_⟩
    rw [mul_assoc (onSite (0 : Fin 2) u), ← mul_assoc (onSite (1 : Fin 2) u),
      onSite_mul_onSite_of_ne (by decide : (1 : Fin 2) ≠ 0) u v,
      mul_assoc (onSite (0 : Fin 2) v), ← mul_assoc (onSite (0 : Fin 2) u),
      onSite_mul_onSite_same, onSite_mul_onSite_same]

/-- Conjugating a site-`0` operator `A₁` by a uniform two-site operator `u ⊗ u` with `u` unitary
gives the site-`0` copy of `u A u†`: the site-`1` factors cancel. This is how the hypothesis
`Û Ŝ_1^{(3)} Û† = Ŝ_1 · n` of Tasaki's Problem 2.2.c (pp. 23-24) reduces to a single-spin
equation. -/
private theorem onSite_zero_conj_twoSite {u : Matrix (Fin 2) (Fin 2) ℂ}
    (hu : u ∈ unitary (Matrix (Fin 2) (Fin 2) ℂ)) (A : Matrix (Fin 2) (Fin 2) ℂ) :
    onSite (0 : Fin 2) u * onSite (1 : Fin 2) u * onSite (0 : Fin 2) A *
        Matrix.conjTranspose (onSite (0 : Fin 2) u * onSite (1 : Fin 2) u) =
      onSite (0 : Fin 2) (u * A * Matrix.conjTranspose u) := by
  have huu : u * Matrix.conjTranspose u = 1 := by
    rw [← Matrix.star_eq_conjTranspose]
    exact Unitary.mul_star_self_of_mem hu
  rw [Matrix.conjTranspose_mul, onSite_conjTranspose, onSite_conjTranspose,
    mul_assoc (onSite (0 : Fin 2) u),
    onSite_mul_onSite_of_ne (by decide : (1 : Fin 2) ≠ 0) u A,
    ← mul_assoc (onSite (0 : Fin 2) u) (onSite (0 : Fin 2) A),
    mul_assoc (onSite (0 : Fin 2) u * onSite (0 : Fin 2) A) (onSite (1 : Fin 2) u),
    ← mul_assoc (onSite (1 : Fin 2) u), onSite_mul_onSite_same (1 : Fin 2), huu, onSite_one,
    one_mul, onSite_mul_onSite_same, onSite_mul_onSite_same]

end LatticeSystem.Quantum
