import LatticeSystem.Quantum.SU2Integral
import LatticeSystem.Quantum.TotalSpin.Rotation
import LatticeSystem.Quantum.SpinHalfRotation.Conjugation

/-!
# Tasaki Problem 2.2.c: the rotated `|↑⟩₁|↓⟩₂` is determined by `n` alone (pp. 23-24)

Tasaki *Physics and Mathematics of Quantum Many-Body Systems* (1st ed., Springer, 2020), §2.2,
Problem 2.2.c, pp. 23-24 (footnote 16, p. 23; footnote 17, p. 24; solution p. 496, eq. (S.16)).

Fix a unit vector `n ∈ ℝ³` and let `Û` be *any* uniform rotation of the two-spin system in the
class of footnote 16 — an arbitrary finite product of the global rotations
`Û_θ^{(α)} = exp(−iθ Ŝ_tot^{(α)})` (eq. (2.2.11), p. 22) over axes `α = 1, 2, 3` and angles `θ` —
such that `Û Ŝ_x^{(3)} Û† = Ŝ_x · n` at both sites `x = 1, 2`. Problem 2.2.c asks to show that
`Û |↑⟩₁|↓⟩₂` is determined solely by `n`, i.e. does not depend on the particular choice of `Û`
within that class. This module states that conclusion pairwise: any two admissible rotations `U`,
`V` with the same `n` send `|↑⟩₁|↓⟩₂` to the same vector. The statement carries no hypothesis
`‖n‖ = 1`: the proof does not use the printed unit norm.
-/

namespace LatticeSystem.Quantum

/-- Every element of the footnote-16 class of Tasaki's Problem 2.2.c (pp. 23-24; footnote 16,
p. 23), the submonoid generated by the global rotations `exp(−iθ Ŝ_tot^{(α)})` of eq. (2.2.11),
p. 22, on two sites, is a uniform product `u ⊗ u = onSite 0 u * onSite 1 u` with `u ∈ SU(2)`:
each generator factors site by site into the single-spin rotation, and site-`0` and site-`1`
factors commute, so products of such operators stay of this form. -/
private theorem mem_uniformRotClosure_exists_su2 {U : ManyBodyOp (Fin 2)}
    (hU : U ∈ Submonoid.closure (Set.range fun p : Fin 3 × ℝ =>
      NormedSpace.exp ((-(Complex.I * (p.2 : ℂ))) •
        ![totalSpinHalfOp1 (Fin 2), totalSpinHalfOp2 (Fin 2), totalSpinHalfOp3 (Fin 2)] p.1))) :
    ∃ u ∈ SU2, U = onSite (0 : Fin 2) u * onSite (1 : Fin 2) u := by
  induction hU using Submonoid.closure_induction with
  | mem x hx =>
    obtain ⟨⟨α, θ⟩, rfl⟩ := hx
    fin_cases α
    · change ∃ u ∈ SU2, NormedSpace.exp ((-(Complex.I * (θ : ℂ))) • totalSpinHalfOp1 (Fin 2)) =
        onSite (0 : Fin 2) u * onSite (1 : Fin 2) u
      rw [← totalSpinHalfRot1_eq_exp, totalSpinHalfRot1_two_site]
      exact ⟨_, spinHalfRot1_mem_SU2 θ, rfl⟩
    · change ∃ u ∈ SU2, NormedSpace.exp ((-(Complex.I * (θ : ℂ))) • totalSpinHalfOp2 (Fin 2)) =
        onSite (0 : Fin 2) u * onSite (1 : Fin 2) u
      rw [← totalSpinHalfRot2_eq_exp, totalSpinHalfRot2_two_site]
      exact ⟨_, spinHalfRot2_mem_SU2 θ, rfl⟩
    · change ∃ u ∈ SU2, NormedSpace.exp ((-(Complex.I * (θ : ℂ))) • totalSpinHalfOp3 (Fin 2)) =
        onSite (0 : Fin 2) u * onSite (1 : Fin 2) u
      rw [← totalSpinHalfRot3_eq_exp, totalSpinHalfRot3_two_site]
      exact ⟨_, spinHalfRot3_mem_SU2 θ, rfl⟩
  | one => exact ⟨1, one_mem _, by rw [onSite_one, onSite_one, one_mul]⟩
  | mul a b _ _ ha hb =>
    obtain ⟨u, hu, rfl⟩ := ha
    obtain ⟨v, hv, rfl⟩ := hb
    refine ⟨u * v, mul_mem hu hv, ?_⟩
    rw [mul_assoc (onSite (0 : Fin 2) u), ← mul_assoc (onSite (1 : Fin 2) u),
      onSite_mul_onSite_of_ne (by decide : (1 : Fin 2) ≠ 0) u v,
      mul_assoc (onSite (0 : Fin 2) v), ← mul_assoc (onSite (0 : Fin 2) u),
      onSite_mul_onSite_same, onSite_mul_onSite_same]

/-- Conjugating a site-`0` operator `A₁` by a uniform two-site operator `u ⊗ u` with `u` unitary
gives the site-`0` copy of `u A u†`: the site-`1` factors cancel. This is how the hypothesis
`Û Ŝ_1^{(3)} Û† = Ŝ_1 · n` of Tasaki's Problem 2.2.c (pp. 23-24) reduces to a single-spin
equation. -/
private theorem onSite_zero_conj_twoSite {u : Matrix (Fin 2) (Fin 2) ℂ}
    (hu : u ∈ unitary (Matrix (Fin 2) (Fin 2) ℂ)) (A : Matrix (Fin 2) (Fin 2) ℂ) :
    onSite (0 : Fin 2) u * onSite (1 : Fin 2) u * onSite (0 : Fin 2) A *
        Matrix.conjTranspose (onSite (0 : Fin 2) u * onSite (1 : Fin 2) u) =
      onSite (0 : Fin 2) (u * A * Matrix.conjTranspose u) := by
  have huu : u * Matrix.conjTranspose u = 1 := by
    rw [← Matrix.star_eq_conjTranspose]
    exact Unitary.mul_star_self_of_mem hu
  rw [Matrix.conjTranspose_mul, onSite_conjTranspose, onSite_conjTranspose,
    mul_assoc (onSite (0 : Fin 2) u),
    onSite_mul_onSite_of_ne (by decide : (1 : Fin 2) ≠ 0) u A,
    ← mul_assoc (onSite (0 : Fin 2) u) (onSite (0 : Fin 2) A),
    mul_assoc (onSite (0 : Fin 2) u * onSite (0 : Fin 2) A) (onSite (1 : Fin 2) u),
    ← mul_assoc (onSite (1 : Fin 2) u), onSite_mul_onSite_same (1 : Fin 2), huu, onSite_one,
    one_mul, onSite_mul_onSite_same, onSite_mul_onSite_same]

/-- A `2 × 2` matrix `w` commuting with `Ŝ^{(3)}` and of determinant `1` is diagonal with
`w₀₀ w₁₁ = 1`. In Tasaki's Problem 2.2.c (pp. 23-24) `w` relates two admissible rotations with
the same `n`, and its commuting with `Ŝ^{(3)}` is the `U(1)` invariance about the `3`-axis in the
sense of eqs. (2.2.12)-(2.2.13), pp. 22-23. -/
private theorem spinHalfOp3_commute_entries {w : Matrix (Fin 2) (Fin 2) ℂ}
    (hw : w * spinHalfOp3 = spinHalfOp3 * w) (hdet : w.det = 1) :
    w 0 1 = 0 ∧ w 1 0 = 0 ∧ w 0 0 * w 1 1 = 1 := by
  have e01 := congrFun (congrFun hw 0) 1
  have e10 := congrFun (congrFun hw 1) 0
  simp only [spinHalfOp3, one_div, pauliZ, Matrix.smul_of, Matrix.smul_cons, smul_eq_mul, mul_one,
    mul_zero, Matrix.smul_empty, mul_neg, Fin.isValue, Matrix.mul_apply, Matrix.of_apply,
    Matrix.cons_val', Matrix.cons_val_one, Matrix.cons_val_fin_one, Fin.sum_univ_two,
    Matrix.cons_val_zero, zero_add, zero_mul, add_zero, neg_mul] at e01 e10
  rw [Matrix.det_fin_two] at hdet
  have h01 : w 0 1 = 0 := by linear_combination -e01
  have h10 : w 1 0 = 0 := by linear_combination e10
  exact ⟨h01, h10, by linear_combination hdet + w 1 0 * h01⟩

/-- If `u = v w` with `w` diagonal and `w₀₀ w₁₁ = 1`, then `u ⊗ u` and `v ⊗ v` send
`|↑⟩₁|↓⟩₂` to the same vector: the phases `w₀₀` on the up spin and `w₁₁` on the down spin
cancel. This is the absence, for `|↑⟩₁|↓⟩₂`, of the phase of Problem 2.1.e (p. 18) that Tasaki's
Problem 2.2.c (pp. 23-24) refers to. -/
private theorem twoSite_mulVec_upDown_of_eq_mul {u v w : Matrix (Fin 2) (Fin 2) ℂ}
    (huvw : u = v * w) (h01 : w 0 1 = 0) (h10 : w 1 0 = 0) (hdet : w 0 0 * w 1 1 = 1) :
    (onSite (0 : Fin 2) u * onSite (1 : Fin 2) u).mulVec (basisVec upDown) =
      (onSite (0 : Fin 2) v * onSite (1 : Fin 2) v).mulVec (basisVec upDown) := by
  subst huvw
  funext τ
  rw [onSite_zero_mul_one_mulVec_basisVec, onSite_zero_mul_one_mulVec_basisVec, upDown_zero,
    upDown_one]
  simp only [Matrix.mul_apply, Fin.sum_univ_two, h01, h10, mul_zero, add_zero, zero_add]
  linear_combination (v (τ 0) 0 * v (τ 1) 1) * hdet

/-- The `SU(2)` core of Tasaki's Problem 2.2.c (pp. 23-24): if `u, v ∈ SU(2)` and the uniform
operators `u ⊗ u`, `v ⊗ v` both conjugate `Ŝ_1^{(3)}` to `Ŝ_1 · n` (the site-`1` copy of the
`Ŝ · v` of eq. (2.1.19), p. 17), then they send `|↑⟩₁|↓⟩₂` to the same vector. The two
conjugation equations give `u Ŝ^{(3)} u† = v Ŝ^{(3)} v†`, so `w = v† u` commutes with `Ŝ^{(3)}`
and has determinant `1`, and `u = v w`. -/
private theorem su2_twoSite_mulVec_upDown_eq (n : Fin 3 → ℝ) {u v : Matrix (Fin 2) (Fin 2) ℂ}
    (hu : u ∈ SU2) (hv : v ∈ SU2)
    (hun : onSite (0 : Fin 2) u * onSite (1 : Fin 2) u * onSite (0 : Fin 2) spinHalfOp3 *
        Matrix.conjTranspose (onSite (0 : Fin 2) u * onSite (1 : Fin 2) u) =
      onSite (0 : Fin 2) (spinHalfDotVec fun α => (n α : ℂ)))
    (hvn : onSite (0 : Fin 2) v * onSite (1 : Fin 2) v * onSite (0 : Fin 2) spinHalfOp3 *
        Matrix.conjTranspose (onSite (0 : Fin 2) v * onSite (1 : Fin 2) v) =
      onSite (0 : Fin 2) (spinHalfDotVec fun α => (n α : ℂ))) :
    (onSite (0 : Fin 2) u * onSite (1 : Fin 2) u).mulVec (basisVec upDown) =
      (onSite (0 : Fin 2) v * onSite (1 : Fin 2) v).mulVec (basisVec upDown) := by
  rw [onSite_zero_conj_twoSite hu.1] at hun
  rw [onSite_zero_conj_twoSite hv.1] at hvn
  have h := hun.trans hvn.symm
  have hconj : u * spinHalfOp3 * Matrix.conjTranspose u =
      v * spinHalfOp3 * Matrix.conjTranspose v := by
    ext a b
    have hab := congrFun (congrFun h ![a, 0]) ![b, 0]
    simpa [onSite_apply, Fin.forall_fin_two] using hab
  have huu : Matrix.conjTranspose u * u = 1 := by
    rw [← Matrix.star_eq_conjTranspose]
    exact Unitary.star_mul_self_of_mem hu.1
  have hvv : Matrix.conjTranspose v * v = 1 := by
    rw [← Matrix.star_eq_conjTranspose]
    exact Unitary.star_mul_self_of_mem hv.1
  have hvv' : v * Matrix.conjTranspose v = 1 := by
    rw [← Matrix.star_eq_conjTranspose]
    exact Unitary.mul_star_self_of_mem hv.1
  have hcomm : Matrix.conjTranspose v * u * spinHalfOp3 =
      spinHalfOp3 * (Matrix.conjTranspose v * u) :=
    calc Matrix.conjTranspose v * u * spinHalfOp3
        = Matrix.conjTranspose v * (u * spinHalfOp3 * Matrix.conjTranspose u) * u := by
          simp only [mul_assoc, huu, mul_one]
      _ = Matrix.conjTranspose v * (v * spinHalfOp3 * Matrix.conjTranspose v) * u := by
          rw [hconj]
      _ = spinHalfOp3 * (Matrix.conjTranspose v * u) := by
          simp only [← mul_assoc, hvv, one_mul]
  have hdet : (Matrix.conjTranspose v * u).det = 1 := by
    rw [Matrix.det_mul, Matrix.det_conjTranspose, hv.2, hu.2, star_one, one_mul]
  have hvw : u = v * (Matrix.conjTranspose v * u) := by
    rw [← mul_assoc, hvv', one_mul]
  obtain ⟨h01, h10, hd⟩ := spinHalfOp3_commute_entries hcomm hdet
  exact twoSite_mulVec_upDown_of_eq_mul hvw h01 h10 hd

/-- **Tasaki Problem 2.2.c** (*Physics and Mathematics of Quantum Many-Body Systems*, §2.2,
pp. 23-24; footnote 16, p. 23). Let `U` and `V` be uniform rotations of two spins in the class
of footnote 16, i.e. finite products of the global rotations `Û_θ^{(α)} = exp(−iθ Ŝ_tot^{(α)})`
of eq. (2.2.11), p. 22, over axes `α` and angles `θ` (the submonoid they generate). If both
satisfy `Û Ŝ_x^{(3)} Û† = Ŝ_x · n` at both sites `x`, with `Ŝ_x · n` the site-`x` copy of the
`Ŝ · v` of eq. (2.1.19), p. 17, then `U |↑⟩₁|↓⟩₂ = V |↑⟩₁|↓⟩₂`: the rotated state depends only
on `n`, not on the choice of the rotation. The printed unit norm `‖n‖ = 1` is not used by the
proof. -/
theorem tasaki_problem_2_2_c_rotated_upDown_eq (n : Fin 3 → ℝ) {U V : ManyBodyOp (Fin 2)}
    (hU : U ∈ Submonoid.closure (Set.range fun p : Fin 3 × ℝ =>
      NormedSpace.exp ((-(Complex.I * (p.2 : ℂ))) •
        ![totalSpinHalfOp1 (Fin 2), totalSpinHalfOp2 (Fin 2), totalSpinHalfOp3 (Fin 2)] p.1)))
    (hV : V ∈ Submonoid.closure (Set.range fun p : Fin 3 × ℝ =>
      NormedSpace.exp ((-(Complex.I * (p.2 : ℂ))) •
        ![totalSpinHalfOp1 (Fin 2), totalSpinHalfOp2 (Fin 2), totalSpinHalfOp3 (Fin 2)] p.1)))
    (hUn : ∀ x : Fin 2, U * onSite x spinHalfOp3 * Matrix.conjTranspose U =
      onSite x (spinHalfDotVec fun α => (n α : ℂ)))
    (hVn : ∀ x : Fin 2, V * onSite x spinHalfOp3 * Matrix.conjTranspose V =
      onSite x (spinHalfDotVec fun α => (n α : ℂ))) :
    U.mulVec (basisVec upDown) = V.mulVec (basisVec upDown) := by
  obtain ⟨u, hu, rfl⟩ := mem_uniformRotClosure_exists_su2 hU
  obtain ⟨v, hv, rfl⟩ := mem_uniformRotClosure_exists_su2 hV
  exact su2_twoSite_mulVec_upDown_eq n hu hv (hUn 0) (hVn 0)

end LatticeSystem.Quantum
