import LatticeSystem.Quantum.SpinS.SpinThreeHalfBondProjection.Internal.Projector

/-!
# The local spin-three-half VBS kernel certificate

This internal module proves the sparse VBS-vector identities, rank, nullity,
and kernel formula used by the public local bond-projection API.
-/

namespace LatticeSystem.Quantum.SpinThreeHalfBondProjection.Internal

open scoped ComplexOrder

/-- The local spin-3/2 VBS vector with two unpaired virtual spin-halves at
each endpoint, indexed by their down-spin counts `a` and `b`.

The first basis term comes from `|up,down>` on the selected virtual singlet
and the second from `-|down,up>`.  The binomial square roots are the
normalized symmetric-spin coefficients at the two endpoints. -/
noncomputable def rawVBSBondVec
    (a b : Fin 3) : (Fin 2 → Fin 4) → ℂ :=
  fun σ =>
    let singletOuterWeight : ℂ :=
      (Real.sqrt 2 : ℂ)⁻¹ *
        (Real.sqrt (Nat.choose 2 a.val) : ℂ) *
        (Real.sqrt (Nat.choose 2 b.val) : ℂ)
    let upDownSiteWeight : ℂ :=
      ((Real.sqrt (Nat.choose 3 a.val) : ℂ) *
        (Real.sqrt (Nat.choose 3 (b.val + 1)) : ℂ))⁻¹
    let downUpSiteWeight : ℂ :=
      ((Real.sqrt (Nat.choose 3 (a.val + 1)) : ℂ) *
        (Real.sqrt (Nat.choose 3 b.val) : ℂ))⁻¹
    singletOuterWeight *
      (upDownSiteWeight *
          (if σ = ![Fin.castSucc a, Fin.succ b] then 1 else 0) -
        downUpSiteWeight *
          (if σ = ![Fin.succ a, Fin.castSucc b] then 1 else 0))

/-- The nine-dimensional candidate kernel generated by one virtual singlet
and two unpaired virtual spin-halves at each endpoint. -/
noncomputable def rawVBSBondSubspace :
    Submodule ℂ ((Fin 2 → Fin 4) → ℂ) :=
  Submodule.span ℂ
    (Set.range fun p : Fin 3 × Fin 3 =>
      rawVBSBondVec p.1 p.2)

/-- Matrix multiplication on a vector supported at two coordinates is the
corresponding linear combination of the two matrix columns. -/
private theorem spinThreeHalf_mulVec_two_coordinate
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (A : Matrix ι ι ℂ) (τ₁ τ₂ : ι) (c₁ c₂ : ℂ) :
    A.mulVec
        (c₁ • (Pi.single τ₁ (1 : ℂ) : ι → ℂ) -
          c₂ • (Pi.single τ₂ (1 : ℂ) : ι → ℂ)) =
      c₁ • A.col τ₁ - c₂ • A.col τ₂ := by
  rw [Matrix.mulVec_sub, Matrix.mulVec_smul, Matrix.mulVec_smul,
    Matrix.mulVec_single_one, Matrix.mulVec_single_one]

/-- Every local VBS generator is the difference of its two supported basis
coordinates. -/
private theorem rawVBSBondVec_eq_two_coordinate
    (a b : Fin 3) :
    let τUD : Fin 2 → Fin 4 :=
      ![Fin.castSucc a, Fin.succ b]
    let τDU : Fin 2 → Fin 4 :=
      ![Fin.succ a, Fin.castSucc b]
    let outer : ℂ :=
      (Real.sqrt 2 : ℂ)⁻¹ *
        (Real.sqrt (Nat.choose 2 a.val) : ℂ) *
        (Real.sqrt (Nat.choose 2 b.val) : ℂ)
    let uWeight : ℂ :=
      ((Real.sqrt (Nat.choose 3 a.val) : ℂ) *
        (Real.sqrt (Nat.choose 3 (b.val + 1)) : ℂ))⁻¹
    let dWeight : ℂ :=
      ((Real.sqrt (Nat.choose 3 (a.val + 1)) : ℂ) *
        (Real.sqrt (Nat.choose 3 b.val) : ℂ))⁻¹
    let cUD : ℂ := outer * uWeight
    let cDU : ℂ := outer * dWeight
    rawVBSBondVec a b =
      cUD • (Pi.single τUD (1 : ℂ) : (Fin 2 → Fin 4) → ℂ) -
        cDU • (Pi.single τDU (1 : ℂ) : (Fin 2 → Fin 4) → ℂ) := by
  let τUD : Fin 2 → Fin 4 :=
    ![Fin.castSucc a, Fin.succ b]
  let τDU : Fin 2 → Fin 4 :=
    ![Fin.succ a, Fin.castSucc b]
  let outer : ℂ :=
    (Real.sqrt 2 : ℂ)⁻¹ *
      (Real.sqrt (Nat.choose 2 a.val) : ℂ) *
      (Real.sqrt (Nat.choose 2 b.val) : ℂ)
  let uWeight : ℂ :=
    ((Real.sqrt (Nat.choose 3 a.val) : ℂ) *
      (Real.sqrt (Nat.choose 3 (b.val + 1)) : ℂ))⁻¹
  let dWeight : ℂ :=
    ((Real.sqrt (Nat.choose 3 (a.val + 1)) : ℂ) *
      (Real.sqrt (Nat.choose 3 b.val) : ℂ))⁻¹
  let cUD : ℂ := outer * uWeight
  let cDU : ℂ := outer * dWeight
  change rawVBSBondVec a b =
    cUD • (Pi.single τUD (1 : ℂ) : (Fin 2 → Fin 4) → ℂ) -
      cDU • (Pi.single τDU (1 : ℂ) : (Fin 2 → Fin 4) → ℂ)
  have hτne : τUD ≠ τDU := by
    intro h
    have h0 := congrFun h 0
    have hv := congrArg Fin.val h0
    simp only [τUD, τDU, Matrix.cons_val_zero, Fin.val_castSucc,
      Fin.val_succ] at hv
    omega
  funext σ
  by_cases hUD : σ = τUD
  · subst σ
    simp [rawVBSBondVec, τUD, τDU, outer, uWeight,
      dWeight, cUD, cDU, hτne]
  · by_cases hDU : σ = τDU
    · subst σ
      simp [rawVBSBondVec, τUD, τDU, outer, uWeight,
        dWeight, cUD, cDU, hτne.symm]
    · simp [rawVBSBondVec, τUD, τDU, outer, uWeight,
        dWeight, cUD, cDU, hUD, hDU]

/-- The two supported coordinates of a local VBS generator have equal
maximal-spin weight after multiplication by their site-normalization
coefficients. -/
private theorem rawVBSBondVec_weight_balance
    (a b : Fin 3) :
    let τUD : Fin 2 → Fin 4 :=
      ![Fin.castSucc a, Fin.succ b]
    let τDU : Fin 2 → Fin 4 :=
      ![Fin.succ a, Fin.castSucc b]
    let uWeight : ℂ :=
      ((Real.sqrt (Nat.choose 3 a.val) : ℂ) *
        (Real.sqrt (Nat.choose 3 (b.val + 1)) : ℂ))⁻¹
    let dWeight : ℂ :=
      ((Real.sqrt (Nat.choose 3 (a.val + 1)) : ℂ) *
        (Real.sqrt (Nat.choose 3 b.val) : ℂ))⁻¹
    uWeight * spinThreeHalfMaxSpinWeight τUD =
      dWeight * spinThreeHalfMaxSpinWeight τDU := by
  let s : ℂ := Real.sqrt 3
  have hs : s * s = 3 := by
    simpa only [s] using spinThreeHalf_sqrt_three_mul_self
  have hsne : s ≠ 0 := by
    intro h
    rw [h, zero_mul] at hs
    norm_num at hs
  fin_cases a <;> fin_cases b <;>
    norm_num [spinThreeHalfMaxSpinWeight, Matrix.cons_val_zero,
      Matrix.cons_val_one, Matrix.cons_val_two, Matrix.cons_val_three,
      Nat.choose, s] <;>
    field_simp [hsne] <;>
    ring_nf at hs ⊢ <;>
    rw [hs]

/-- The two maximal-spin-table columns supporting a local VBS generator
agree after multiplication by their full generator coefficients. -/
private theorem rawVBSBondVec_scaled_columns
    (a b : Fin 3) :
    let τUD : Fin 2 → Fin 4 :=
      ![Fin.castSucc a, Fin.succ b]
    let τDU : Fin 2 → Fin 4 :=
      ![Fin.succ a, Fin.castSucc b]
    let outer : ℂ :=
      (Real.sqrt 2 : ℂ)⁻¹ *
        (Real.sqrt (Nat.choose 2 a.val) : ℂ) *
        (Real.sqrt (Nat.choose 2 b.val) : ℂ)
    let uWeight : ℂ :=
      ((Real.sqrt (Nat.choose 3 a.val) : ℂ) *
        (Real.sqrt (Nat.choose 3 (b.val + 1)) : ℂ))⁻¹
    let dWeight : ℂ :=
      ((Real.sqrt (Nat.choose 3 (a.val + 1)) : ℂ) *
        (Real.sqrt (Nat.choose 3 b.val) : ℂ))⁻¹
    let cUD : ℂ := outer * uWeight
    let cDU : ℂ := outer * dWeight
    cUD • spinThreeHalfMaxSpinTable.col τUD =
      cDU • spinThreeHalfMaxSpinTable.col τDU := by
  let τUD : Fin 2 → Fin 4 :=
    ![Fin.castSucc a, Fin.succ b]
  let τDU : Fin 2 → Fin 4 :=
    ![Fin.succ a, Fin.castSucc b]
  let outer : ℂ :=
    (Real.sqrt 2 : ℂ)⁻¹ *
      (Real.sqrt (Nat.choose 2 a.val) : ℂ) *
      (Real.sqrt (Nat.choose 2 b.val) : ℂ)
  let uWeight : ℂ :=
    ((Real.sqrt (Nat.choose 3 a.val) : ℂ) *
      (Real.sqrt (Nat.choose 3 (b.val + 1)) : ℂ))⁻¹
  let dWeight : ℂ :=
    ((Real.sqrt (Nat.choose 3 (a.val + 1)) : ℂ) *
      (Real.sqrt (Nat.choose 3 b.val) : ℂ))⁻¹
  let cUD : ℂ := outer * uWeight
  let cDU : ℂ := outer * dWeight
  change cUD • spinThreeHalfMaxSpinTable.col τUD =
    cDU • spinThreeHalfMaxSpinTable.col τDU
  have hdown :
      spinThreeHalfDown τUD = spinThreeHalfDown τDU := by
    simp only [spinThreeHalfDown, τUD, τDU, Matrix.cons_val_zero,
      Matrix.cons_val_one, Fin.val_castSucc, Fin.val_succ]
    omega
  have hweight := rawVBSBondVec_weight_balance a b
  change uWeight * spinThreeHalfMaxSpinWeight τUD =
    dWeight * spinThreeHalfMaxSpinWeight τDU at hweight
  funext ρ
  simp only [Pi.smul_apply, Matrix.col_apply, smul_eq_mul]
  by_cases hρ : spinThreeHalfDown ρ = spinThreeHalfDown τUD
  · have hρDU :
        spinThreeHalfDown ρ = spinThreeHalfDown τDU :=
      hρ.trans hdown
    rw [spinThreeHalfMaxSpinTable_apply_weight, if_pos hρ,
      spinThreeHalfMaxSpinTable_apply_weight, if_pos hρDU, hdown]
    simp only [cUD, cDU]
    calc
      _ = outer *
          ((Nat.choose 6 (spinThreeHalfDown τDU) : ℂ)⁻¹ *
            spinThreeHalfMaxSpinWeight ρ) *
          (uWeight * spinThreeHalfMaxSpinWeight τUD) := by ring
      _ = outer *
          ((Nat.choose 6 (spinThreeHalfDown τDU) : ℂ)⁻¹ *
            spinThreeHalfMaxSpinWeight ρ) *
          (dWeight * spinThreeHalfMaxSpinWeight τDU) := by rw [hweight]
      _ = _ := by ring
  · have hρDU :
        spinThreeHalfDown ρ ≠ spinThreeHalfDown τDU := by
      intro h
      exact hρ (h.trans hdown.symm)
    rw [spinThreeHalfMaxSpinTable_apply_weight, if_neg hρ,
      spinThreeHalfMaxSpinTable_apply_weight, if_neg hρDU]
    simp only [mul_zero]

/-- The frozen maximal-spin table annihilates every local VBS
generator. -/
theorem maxSpinTable_mulVec_rawVBSBondVec
    (a b : Fin 3) :
    spinThreeHalfMaxSpinTable.mulVec (rawVBSBondVec a b) = 0 := by
  rw [rawVBSBondVec_eq_two_coordinate,
    spinThreeHalf_mulVec_two_coordinate,
    rawVBSBondVec_scaled_columns, sub_self]

/-- The nine explicit local VBS bond generators are linearly independent. -/
theorem rawVBSBondVec_linearIndependent :
    LinearIndependent ℂ
      (fun p : Fin 3 × Fin 3 =>
        rawVBSBondVec p.1 p.2) := by
  rw [Fintype.linearIndependent_iff]
  intro c hc p
  have h00 := congrFun hc ![0, 1]
  have h01 := congrFun hc ![0, 2]
  have h02 := congrFun hc ![0, 3]
  have h10 := congrFun hc ![1, 1]
  have h11 := congrFun hc ![1, 2]
  have h12 := congrFun hc ![1, 3]
  have h20 := congrFun hc ![2, 1]
  have h21 := congrFun hc ![2, 2]
  have h22 := congrFun hc ![2, 3]
  simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul,
    rawVBSBondVec, Pi.zero_apply] at h00 h01 h02 h10 h11 h12 h20 h21 h22
  rw [Fintype.sum_prod_type] at h00 h01 h02 h10 h11 h12 h20 h21 h22
  simp only [Fin.sum_univ_three] at h00 h01 h02 h10 h11 h12 h20 h21 h22
  norm_num [Matrix.cons_val_zero, Matrix.cons_val_one, Fin.ext_iff,
    Real.sqrt_eq_zero'] at h00
  norm_num [Matrix.cons_val_zero, Matrix.cons_val_one, Fin.ext_iff,
    Real.sqrt_eq_zero'] at h01
  norm_num [Matrix.cons_val_zero, Matrix.cons_val_one, Fin.ext_iff,
    Real.sqrt_eq_zero'] at h02
  norm_num [Matrix.cons_val_zero, Matrix.cons_val_one, Fin.ext_iff,
    Real.sqrt_eq_zero'] at h10
  norm_num [Matrix.cons_val_zero, Matrix.cons_val_one, Fin.ext_iff,
    Real.sqrt_eq_zero'] at h11
  norm_num [Matrix.cons_val_zero, Matrix.cons_val_one, Fin.ext_iff,
    Real.sqrt_eq_zero'] at h12
  norm_num [Matrix.cons_val_zero, Matrix.cons_val_one, Fin.ext_iff,
    Real.sqrt_eq_zero'] at h20
  norm_num [Matrix.cons_val_zero, Matrix.cons_val_one, Fin.ext_iff,
    Real.sqrt_eq_zero'] at h21
  norm_num [Matrix.cons_val_zero, Matrix.cons_val_one, Fin.ext_iff,
    Real.sqrt_eq_zero'] at h22
  have hsqrt2 : (↑(Real.sqrt 2) : ℂ) ≠ 0 := by
    norm_num [Real.sqrt_eq_zero']
  have hsqrt3 : (↑(Real.sqrt 3) : ℂ) ≠ 0 := by
    norm_num [Real.sqrt_eq_zero']
  have hc10 : c (1, 0) = 0 := by
    simp only [h01, zero_mul, neg_zero, zero_add] at h10
    exact (mul_eq_zero.mp h10).resolve_right
      (mul_ne_zero (inv_ne_zero hsqrt3) (inv_ne_zero hsqrt3))
  have hc11 : c (1, 1) = 0 := by
    simp only [h02, zero_mul, neg_zero, zero_add] at h11
    exact (mul_eq_zero.mp h11).resolve_right
      (mul_ne_zero hsqrt2 (mul_ne_zero (inv_ne_zero hsqrt3) (inv_ne_zero hsqrt3)))
  have hc20 : c (2, 0) = 0 := by
    simp only [hc11, zero_mul, neg_zero, zero_add] at h20
    exact (mul_eq_zero.mp h20).resolve_right
      (mul_ne_zero (inv_ne_zero hsqrt2)
        (mul_ne_zero (inv_ne_zero hsqrt3) (inv_ne_zero hsqrt3)))
  have hc21 : c (2, 1) = 0 := by
    simp only [h12, zero_mul, neg_zero, zero_add] at h21
    exact (mul_eq_zero.mp h21).resolve_right
      (mul_ne_zero (inv_ne_zero hsqrt3) (inv_ne_zero hsqrt3))
  rcases p with ⟨p₀, p₁⟩
  fin_cases p₀ <;> fin_cases p₁ <;> simp_all

/-- The local VBS bond subspace is contained in the kernel of the
frozen maximal-spin table. -/
private theorem rawVBSBondSubspace_le_table_ker :
    rawVBSBondSubspace ≤
      LinearMap.ker (Matrix.mulVecLin spinThreeHalfMaxSpinTable) := by
  rw [rawVBSBondSubspace, Submodule.span_le]
  rintro _ ⟨p, rfl⟩
  simp only [SetLike.mem_coe, LinearMap.mem_ker, Matrix.mulVecLin_apply]
  exact maxSpinTable_mulVec_rawVBSBondVec p.1 p.2

/-- The span of the nine independent local VBS bond generators has
complex dimension nine. -/
private theorem finrank_rawVBSBondSubspace :
    Module.finrank ℂ rawVBSBondSubspace = 9 := by
  rw [rawVBSBondSubspace,
    finrank_span_eq_card rawVBSBondVec_linearIndependent]
  norm_num

/-- One configuration in each total-down-spin sector, used to select
seven independent columns of the frozen maximal-spin table. -/
private def spinThreeHalfMaxSpinTableAnchor :
    Fin 7 → Fin 2 → Fin 4 :=
  ![![0, 0], ![0, 1], ![0, 2], ![0, 3],
    ![1, 3], ![2, 3], ![3, 3]]

/-- The selected anchor indexed by `k` lies in total-down-spin sector
`k`. -/
private theorem spinThreeHalfDown_anchor (k : Fin 7) :
    spinThreeHalfDown (spinThreeHalfMaxSpinTableAnchor k) = k.val := by
  fin_cases k <;>
    norm_num [spinThreeHalfDown, spinThreeHalfMaxSpinTableAnchor,
      Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.cons_val_two, Matrix.cons_val_three]

/-- Every selected anchor has a nonzero diagonal entry in the frozen
maximal-spin table. -/
private theorem spinThreeHalfMaxSpinTable_anchor_diagonal_ne_zero (k : Fin 7) :
    spinThreeHalfMaxSpinTable (spinThreeHalfMaxSpinTableAnchor k)
        (spinThreeHalfMaxSpinTableAnchor k) ≠ 0 := by
  fin_cases k <;>
    norm_num [spinThreeHalfMaxSpinTable, spinThreeHalfDown, spinThreeHalfMaxSpinTableAnchor,
      Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.cons_val_two, Matrix.cons_val_three, Nat.choose,
      Real.sqrt_eq_zero']

/-- Frozen-table entries between distinct selected anchor sectors
vanish. -/
private theorem spinThreeHalfMaxSpinTable_anchor_cross_sector
    (k l : Fin 7) (hkl : k ≠ l) :
    spinThreeHalfMaxSpinTable (spinThreeHalfMaxSpinTableAnchor k)
        (spinThreeHalfMaxSpinTableAnchor l) = 0 := by
  rw [spinThreeHalfMaxSpinTable_apply_weight, if_neg]
  intro hdown
  rw [spinThreeHalfDown_anchor, spinThreeHalfDown_anchor] at hdown
  exact hkl (Fin.ext hdown)

/-- The seven frozen-table columns selected by the anchor
configurations are linearly independent. -/
private theorem spinThreeHalfMaxSpinTable_anchor_columns_linearIndependent :
    LinearIndependent ℂ
      (fun k : Fin 7 => spinThreeHalfMaxSpinTable.col (spinThreeHalfMaxSpinTableAnchor k)) := by
  rw [Fintype.linearIndependent_iff]
  intro c hc k
  have hk := congrFun hc (spinThreeHalfMaxSpinTableAnchor k)
  simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul,
    Matrix.col_apply, Pi.zero_apply] at hk
  rw [Finset.sum_eq_single k] at hk
  · exact (mul_eq_zero.mp hk).resolve_right
      (spinThreeHalfMaxSpinTable_anchor_diagonal_ne_zero k)
  · intro l _ hlk
    rw [spinThreeHalfMaxSpinTable_anchor_cross_sector k l (Ne.symm hlk),
      mul_zero]
  · simp

/-- Multiplying a matrix by a column of a second matrix extracts the
corresponding column of their product. -/
private theorem spinThreeHalf_mulVec_col
    {ι : Type*} [Fintype ι]
    (M N : Matrix ι ι ℂ) (j : ι) :
    M.mulVec (N.col j) = (M * N).col j := by
  rfl

/-- The frozen maximal-spin table has rank at least seven. -/
private theorem spinThreeHalfMaxSpinTable_rank_ge_seven :
    7 ≤ Matrix.rank spinThreeHalfMaxSpinTable := by
  have hfixed (k : Fin 7) :
      spinThreeHalfMaxSpinTable.mulVec
          (spinThreeHalfMaxSpinTable.col (spinThreeHalfMaxSpinTableAnchor k)) =
        spinThreeHalfMaxSpinTable.col (spinThreeHalfMaxSpinTableAnchor k) := by
    rw [spinThreeHalf_mulVec_col, spinThreeHalfMaxSpinTable_idempotent]
  have hspan_le :
      Submodule.span ℂ
          (Set.range fun k : Fin 7 =>
            spinThreeHalfMaxSpinTable.col (spinThreeHalfMaxSpinTableAnchor k)) ≤
        LinearMap.range spinThreeHalfMaxSpinTable.mulVecLin := by
    rw [Submodule.span_le]
    rintro _ ⟨k, rfl⟩
    refine ⟨spinThreeHalfMaxSpinTable.col (spinThreeHalfMaxSpinTableAnchor k), ?_⟩
    rw [Matrix.mulVecLin_apply, hfixed]
  rw [Matrix.rank]
  calc
    7 = Module.finrank ℂ
        (Submodule.span ℂ
          (Set.range fun k : Fin 7 =>
            spinThreeHalfMaxSpinTable.col (spinThreeHalfMaxSpinTableAnchor k))) := by
      rw [finrank_span_eq_card
        spinThreeHalfMaxSpinTable_anchor_columns_linearIndependent]
      norm_num
    _ ≤ Module.finrank ℂ
        (LinearMap.range spinThreeHalfMaxSpinTable.mulVecLin) :=
      Submodule.finrank_mono hspan_le

/-- The nine-dimensional VBS kernel forces the frozen maximal-spin
table to have rank at most seven. -/
private theorem spinThreeHalfMaxSpinTable_rank_le_seven :
    Matrix.rank spinThreeHalfMaxSpinTable ≤ 7 := by
  have hker :
      9 ≤ Module.finrank ℂ
        (LinearMap.ker (Matrix.mulVecLin spinThreeHalfMaxSpinTable)) := by
    rw [← finrank_rawVBSBondSubspace]
    exact Submodule.finrank_mono
      rawVBSBondSubspace_le_table_ker
  have hnullity :=
    (Matrix.mulVecLin spinThreeHalfMaxSpinTable).finrank_range_add_finrank_ker
  have hdim :
      Module.finrank ℂ ((Fin 2 → Fin 4) → ℂ) = 16 := by
    rw [Module.finrank_pi ℂ]
    norm_num
  rw [hdim] at hnullity
  rw [Matrix.rank]
  omega

/-- The frozen maximal-spin table has rank exactly seven. -/
theorem spinThreeHalfMaxSpinTable_rank :
    Matrix.rank spinThreeHalfMaxSpinTable = 7 :=
  le_antisymm spinThreeHalfMaxSpinTable_rank_le_seven
    spinThreeHalfMaxSpinTable_rank_ge_seven

/-- The kernel of the frozen maximal-spin table has complex dimension
nine. -/
theorem finrank_spinThreeHalfMaxSpinTable_ker :
    Module.finrank ℂ
      (LinearMap.ker (Matrix.mulVecLin spinThreeHalfMaxSpinTable)) = 9 := by
  have hnullity :=
    (Matrix.mulVecLin spinThreeHalfMaxSpinTable).finrank_range_add_finrank_ker
  change Matrix.rank spinThreeHalfMaxSpinTable +
      Module.finrank ℂ
        (LinearMap.ker (Matrix.mulVecLin spinThreeHalfMaxSpinTable)) =
      Module.finrank ℂ ((Fin 2 → Fin 4) → ℂ) at hnullity
  rw [spinThreeHalfMaxSpinTable_rank, Module.finrank_pi ℂ] at hnullity
  norm_num at hnullity
  omega

/-- The kernel of the frozen maximal-spin table is exactly the local
VBS bond subspace. -/
theorem maxSpinTable_ker_eq_rawVBSBondSubspace :
    LinearMap.ker (Matrix.mulVecLin spinThreeHalfMaxSpinTable) =
      rawVBSBondSubspace := by
  symm
  apply Submodule.eq_of_le_of_finrank_le
    rawVBSBondSubspace_le_table_ker
  rw [finrank_spinThreeHalfMaxSpinTable_ker,
    finrank_rawVBSBondSubspace]

end LatticeSystem.Quantum.SpinThreeHalfBondProjection.Internal
