/-
The Weyl (Schwinger-boson) linear map for a chain of spin-`S` sites, `N = 2S`.

This file constructs the injective linear map that sends a many-body spin-`S` state
`Φ : (Fin L → Fin (N + 1)) → ℂ` to a homogeneous polynomial of total degree `N·L` in the `2L` Weyl
variables `Fin L × Fin 2` (site `x` carrying `u_x = (x,0)` and `v_x = (x,1)`).  Each site basis
state `k ∈ {0, …, N}` (physically `S^z = S − k`) maps to the degree-`N` monomial
`u_x^{N−k} v_x^k` of that site's two variables, weighted by the Clebsch–Gordan constant
`c(k) = √(binom(N,k))` of the isomorphism `Symᴺ(ℂ²) ≅ (spin S)`.  Two Weyl variables per site
suffice for every `S`: `N` controls the degree carried by a site and the site-state index type
`Fin (N + 1)`, not the polynomial ring.

The weights `c(k)` are **essential**, not cosmetic scalars.  At `N = 2` they are `1, √2, 1`, and the
middle `√2` (the genuine `m = 0` Clebsch–Gordan coefficient) is fixed by the requirement
`2·c(0)·c(2) = c(1)²`, which is exactly what makes a bond singlet land in the ideal generated by the
bond factor `f_x = u_x v_{x+1} − v_x u_{x+1}`.  Concretely, the production VBS bond singlet
`Ψ_{↑↓} = 2|+,−⟩ − |0,0⟩` (`Quantum.vbsBondVec 0 1`) maps to
`2·c(0)c(2)·u_x² v_{x+1}² − c(1)²·u_x v_x u_{x+1} v_{x+1}
  = u_x v_{x+1}·(2·u_x v_{x+1} − 2·v_x u_{x+1}) = 2·u_x v_{x+1}·f_x`,
which is divisible by `f_x`; with the naive unit weights `c ≡ 1` (`2 ≠ 1`) it is **not** divisible,
so the map would not be an algebra-compatible Weyl isomorphism and the bond-kernel ⇔ divisibility
bridge would fail.

This is the "Stage C" Weyl representation used in the uniqueness proof of the AKLT ground state
(Tasaki §7.1.3, eqs. (7.1.22)–(7.1.23)), which is the case `N = 2`; the bond-divisibility / UFD
argument that consumes this map lives in `LatticeSystem.Math.MvPolynomial.BilinearFactorCoprime`.
The map is `ℂ`-linear, injective (each `c(k) ≠ 0`), and image-homogeneous of total degree `N·L`.

The single-monomial image `weylMono σ` (rather than the product form `∏ X`) is used deliberately;
the bridge to the product form `∏_x (u_x v_{x+1} - v_x u_{x+1})` belongs to a later stage.

Reference: Hal Tasaki, *Physics and Mathematics of Quantum Many-Body Systems* (Springer, 2020),
§7.1.3 "The Uniqueness of the Ground State", pp. 186–188, eqs. (7.1.22)–(7.1.25); polynomial
representation due to Arovas–Auerbach–Haldane [10]; proof due to Kennedy–Lieb–Tasaki [41].
-/
import Mathlib.Data.Complex.Basic
import Mathlib.Analysis.SpecialFunctions.Sqrt
import Mathlib.Data.Nat.Choose.Basic
import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import Mathlib.Algebra.BigOperators.Finsupp.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Piecewise
import Mathlib.Algebra.BigOperators.GroupWithZero.Finset

open MvPolynomial

namespace LatticeSystem.Math

variable {L N : ℕ}

/-- The degree-`N` multidegree contributed by a single spin-`S` site `x` in state `k : Fin (N+1)`,
as an exponent `Finsupp` on the Weyl variables `Fin L × Fin 2` (`(x,0) = u_x`, `(x,1) = v_x`):
`k ↦ u_x^{N−k} v_x^k`.  The truncated subtraction `N − k` is harmless because `k : Fin (N+1)`
already guarantees `k ≤ N`. -/
noncomputable def mdSite (x : Fin L) (k : Fin (N + 1)) : (Fin L × Fin 2) →₀ ℕ :=
  Finsupp.single (x, 0) (N - (k : ℕ)) + Finsupp.single (x, 1) (k : ℕ)

/-- Each single-site multidegree has total degree `N` (each site contributes a degree-`N` binary
form), so a chain of `L` sites yields total degree `N·L`. -/
theorem mdSite_degree (x : Fin L) (k : Fin (N + 1)) : (mdSite x k).degree = N := by
  rw [mdSite, map_add, Finsupp.degree_single, Finsupp.degree_single,
    Nat.sub_add_cancel (Nat.lt_succ_iff.mp k.isLt)]

/-- Value of a single-site multidegree at the first (`u`) variable of its own site: reading this
coordinate recovers `k` via `k ↦ N - k`, which underlies injectivity of `md`. -/
theorem mdSite_apply_self (x : Fin L) (k : Fin (N + 1)) : (mdSite x k) (x, 0) = N - (k : ℕ) := by
  simp [mdSite, Finsupp.add_apply, Prod.ext_iff]

/-- Value of a single-site multidegree at the second (`v`) variable of its own site: this
coordinate is the site state `k` itself, the exponent of `v_x` in `u_x^{N−k} v_x^k`. -/
theorem mdSite_apply_snd (x : Fin L) (k : Fin (N + 1)) : (mdSite x k) (x, 1) = (k : ℕ) := by
  simp [mdSite, Finsupp.add_apply, Prod.ext_iff]

/-- A single-site multidegree vanishes at *either* variable of a different site `y ≠ x`. -/
theorem mdSite_apply_ne {x y : Fin L} (h : y ≠ x) (k : Fin (N + 1)) (i : Fin 2) :
    (mdSite y k) (x, i) = 0 := by
  simp [mdSite, Finsupp.add_apply, Prod.ext_iff, h]

/-- The total multidegree of a chain state `σ`, i.e. the sum of the per-site degree-`N`
multidegrees; its coefficient `1` monomial is the Weyl image `weylMono σ`. -/
noncomputable def md (σ : Fin L → Fin (N + 1)) : (Fin L × Fin 2) →₀ ℕ :=
  ∑ x, mdSite x (σ x)

/-- Reading the first (`u`) variable of site `i` recovers the site state via `σ i ↦ N - σ i`;
this is the key computation for injectivity of `md`. -/
theorem md_apply_fst (σ : Fin L → Fin (N + 1)) (i : Fin L) : (md σ) (i, 0) = N - (σ i : ℕ) := by
  rw [md, Finsupp.finset_sum_apply,
    Finset.sum_eq_single i (fun y _ hy => mdSite_apply_ne hy (σ y) 0)
      (fun h => absurd (Finset.mem_univ i) h)]
  exact mdSite_apply_self i (σ i)

/-- Reading the second (`v`) variable of site `i` returns the site state `σ i` itself.  Together
with `md_apply_fst` this recovers a configuration from its multidegree coordinate by coordinate,
which is what identifies the image of `md` (`exists_md_eq`). -/
theorem md_apply_snd (σ : Fin L → Fin (N + 1)) (i : Fin L) : (md σ) (i, 1) = (σ i : ℕ) := by
  rw [md, Finsupp.finset_sum_apply,
    Finset.sum_eq_single i (fun y _ hy => mdSite_apply_ne hy (σ y) 1)
      (fun h => absurd (Finset.mem_univ i) h)]
  exact mdSite_apply_snd i (σ i)

/-- The total multidegree of every chain state is `N·L` (each of the `L` sites contributes `N`);
hence every Weyl monomial is homogeneous of total degree `N·L` (Tasaki eq. (7.1.25)). -/
theorem md_degree (σ : Fin L → Fin (N + 1)) : (md σ).degree = N * L := by
  rw [md, map_sum]
  simp only [mdSite_degree]
  rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, smul_eq_mul, Nat.mul_comm]

/-- Distinct chain states have distinct multidegrees: reading each site's first variable via
`md_apply_fst` recovers `σ i` from `md σ`, so `md` is injective (the Weyl representation is
faithful on the standard basis). -/
theorem md_injective : Function.Injective (md : (Fin L → Fin (N + 1)) → _) := by
  intro σ τ h
  funext i
  have hi : (md σ) (i, 0) = (md τ) (i, 0) := by rw [h]
  rw [md_apply_fst, md_apply_fst] at hi
  have hσ : (σ i : ℕ) ≤ N := Nat.lt_succ_iff.mp (σ i).isLt
  have hτ : (τ i : ℕ) ≤ N := Nat.lt_succ_iff.mp (τ i).isLt
  exact Fin.ext (by omega)

/-- **The multidegrees of chain states are exactly the per-site degree-`N` multidegrees.**  A
multidegree `d` on the Weyl variables whose two exponents at each site sum to `N` is the multidegree
of the configuration `τ y = d (y, 1)`, i.e. `d` really is the exponent of a Weyl monomial.  With
`md_injective` this pins the image of `md`, which is what makes the Weyl map surjective onto its
per-site graded piece (`weylMap_weylPreimage`). -/
theorem exists_md_eq {d : (Fin L × Fin 2) →₀ ℕ} (hd : ∀ y : Fin L, d (y, 0) + d (y, 1) = N) :
    ∃ τ : Fin L → Fin (N + 1), md τ = d := by
  refine ⟨fun y => ⟨d (y, 1), by have := hd y; omega⟩, ?_⟩
  ext v
  obtain ⟨y, i⟩ := v
  fin_cases i
  · change (md _) (y, 0) = d (y, 0)
    rw [md_apply_fst]
    have := hd y
    change N - d (y, 1) = d (y, 0)
    omega
  · change (md _) (y, 1) = d (y, 1)
    rw [md_apply_snd]

/-- The single-site Clebsch–Gordan normalization constant `c(k) = √(binom(N,k))` from the
isomorphism `Symᴺ(ℂ²) ≅ (spin S)`, `N = 2S`.  At `N = 2` it is `c(0) = 1` (`m = +1`, `u_x²`),
`c(1) = √2` (`m = 0`, `u_x v_x`), `c(2) = 1` (`m = −1`, `v_x²`); the middle `√2` is the genuine
`m = 0` weight, and the identity `2·c(0)·c(2) = c(1)² = 2` is what makes a bond singlet divisible
by the bond factor `u_x v_{x+1} − v_x u_{x+1}`. -/
noncomputable def cgSite (k : Fin (N + 1)) : ℂ :=
  (Real.sqrt (N.choose (k : ℕ)) : ℂ)

/-- Each single-site Clebsch–Gordan constant is nonzero (`binom(N,k) > 0` for `k ≤ N`), so the
Weyl map stays injective after normalization. -/
theorem cgSite_ne_zero (k : Fin (N + 1)) : cgSite k ≠ 0 := by
  have hpos : (0 : ℝ) < (N.choose (k : ℕ) : ℝ) :=
    Nat.cast_pos.mpr (Nat.choose_pos (Nat.lt_succ_iff.mp k.isLt))
  rw [cgSite, ne_eq, Complex.ofReal_eq_zero]
  exact ne_of_gt (Real.sqrt_pos.mpr hpos)

/-- The total Clebsch–Gordan normalization of a chain state `σ`, the product `∏_x c(σ x)` of the
per-site constants `cgSite`; it multiplies the Weyl monomial of `σ`. -/
noncomputable def cgNorm (σ : Fin L → Fin (N + 1)) : ℂ :=
  ∏ x, cgSite (σ x)

/-- The total Clebsch–Gordan normalization is nonzero (a product of nonzero per-site constants),
which keeps the Weyl map injective. -/
theorem cgNorm_ne_zero (σ : Fin L → Fin (N + 1)) : cgNorm σ ≠ 0 :=
  Finset.prod_ne_zero_iff.mpr fun x _ => cgSite_ne_zero (σ x)

/-- The Weyl image of the standard basis vector `σ`: the single degree-`N·L` monomial
`c(σ) · X^{md σ}` carrying the Clebsch–Gordan normalization `cgNorm σ` (Tasaki eqs.
(7.1.22)–(7.1.23)).  A single monomial is used (not the product form `∏ X`). -/
noncomputable def weylMono (σ : Fin L → Fin (N + 1)) : MvPolynomial (Fin L × Fin 2) ℂ :=
  MvPolynomial.monomial (md σ) (cgNorm σ)

/-- The single-site Weyl monomial `w_x k = c(k) · u_x^{N−k} v_x^k` (site `x`, site-state `k`):
the image, under the per-site transport layer, of the standard basis vector `k` at site
`x` alone, isolated from the other `L − 1` sites.  This is the fixture the per-site ladder
transport lemmas are stated against; it is the site-`x` factor of `weylMono σ` at `k = σ x`
(`exists_weylMono_site_factor` below). -/
noncomputable def weylSiteMono (x : Fin L) (k : Fin (N + 1)) : MvPolynomial (Fin L × Fin 2) ℂ :=
  MvPolynomial.monomial (mdSite x k) (cgSite k)

/-- **One-site factorization of the Weyl monomials.**  At a fixed site `x` the whole
`Function.update`-family `k ↦ weylMono (Function.update σ x k)` factors as one `k`-independent
polynomial `M` — the monomial of the other `L − 1` sites — times the single-site monomial
`weylSiteMono x k`, and `M` involves no variable of site `x` (recorded as
`∂_{u_x} M = ∂_{v_x} M = 0`).  Taking `k = σ x` and `Function.update_eq_self` gives the plain
factorization `weylMono σ = M * weylSiteMono x (σ x)`.

The off-site factor is packaged existentially on purpose: the two-site analogue `restMono`
(`Quantum.SpinS.AKLTUniqueness.BondDivisibilityBridge`) already names the off-*bond* monomial, and
a second named "off-monomial" definition would be a near-duplicate of it. -/
theorem exists_weylMono_site_factor (x : Fin L) (σ : Fin L → Fin (N + 1)) :
    ∃ M : MvPolynomial (Fin L × Fin 2) ℂ,
      (∀ i : Fin 2, MvPolynomial.pderiv (x, i) M = 0) ∧
        ∀ k, weylMono (Function.update σ x k) = M * weylSiteMono x k := by
  classical
  refine ⟨MvPolynomial.monomial (∑ y ∈ Finset.univ.erase x, mdSite y (σ y))
      (∏ y ∈ Finset.univ.erase x, cgSite (σ y)), fun i => ?_, fun k => ?_⟩
  · have hzero : (∑ y ∈ Finset.univ.erase x, mdSite y (σ y)) (x, i) = 0 := by
      rw [Finsupp.finset_sum_apply]
      exact Finset.sum_eq_zero fun y hy => mdSite_apply_ne (Finset.ne_of_mem_erase hy) (σ y) i
    rw [MvPolynomial.pderiv_monomial, hzero]
    simp
  · have hmd : md (Function.update σ x k)
        = (∑ y ∈ Finset.univ.erase x, mdSite y (σ y)) + mdSite x k := by
      rw [md, ← Finset.sum_erase_add _ _ (Finset.mem_univ x), Function.update_self]
      congr 1
      exact Finset.sum_congr rfl fun y hy => by
        rw [Function.update_of_ne (Finset.ne_of_mem_erase hy)]
    have hcg : cgNorm (Function.update σ x k)
        = (∏ y ∈ Finset.univ.erase x, cgSite (σ y)) * cgSite k := by
      rw [cgNorm, ← Finset.prod_erase_mul _ _ (Finset.mem_univ x), Function.update_self]
      congr 1
      exact Finset.prod_congr rfl fun y hy => by
        rw [Function.update_of_ne (Finset.ne_of_mem_erase hy)]
    rw [weylMono, weylSiteMono, MvPolynomial.monomial_mul, hmd, hcg]

/-- The Weyl (Schwinger-boson) linear map `Φ ↦ ∑_σ Φ σ • X^{md σ}` from many-body spin-`S` states
to polynomials in the `2L` Weyl variables (Tasaki §7.1.3, eq. (7.1.22)).  It is injective with
image homogeneous of total degree `N·L`. -/
noncomputable def weylMap : ((Fin L → Fin (N + 1)) → ℂ) →ₗ[ℂ] MvPolynomial (Fin L × Fin 2) ℂ :=
  Fintype.linearCombination ℂ weylMono

/-- The coefficient of the monomial `X^{md τ}` in `weylMap Φ` is `Φ τ · cgNorm τ`, the state
amplitude times the Clebsch–Gordan normalization of `τ` (the Weyl monomials are a linearly
independent family indexed by the standard basis).  Publicly exposed: consumed by the
bond-divisibility / dimension-count stages. -/
theorem weylMap_coeff (Φ : (Fin L → Fin (N + 1)) → ℂ) (τ : Fin L → Fin (N + 1)) :
    (weylMap Φ).coeff (md τ) = Φ τ * cgNorm τ := by
  classical
  simp only [weylMap, Fintype.linearCombination_apply, weylMono, coeff_sum, smul_monomial,
    smul_eq_mul, coeff_monomial, md_injective.eq_iff]
  exact Fintype.sum_ite_eq' τ (fun σ => Φ σ * cgNorm σ)

/-- The Weyl map is injective: distinct states have distinct images, since the coefficient at
`X^{md σ}` reads off `Φ σ · cgNorm σ` with `cgNorm σ ≠ 0` (`weylMap_coeff`, `cgNorm_ne_zero`). -/
theorem weylMap_injective : Function.Injective (weylMap : ((Fin L → Fin (N + 1)) → ℂ) →ₗ[ℂ] _) := by
  intro Φ Ψ h
  funext σ
  have hc := congrArg (fun p => MvPolynomial.coeff (md σ) p) h
  simp only [weylMap_coeff] at hc
  exact mul_right_cancel₀ (cgNorm_ne_zero σ) hc

/-- The image `weylMap Φ` is homogeneous of total degree `N·L` (each Weyl monomial `X^{md σ}` has
degree `md σ`.degree `= N·L`; Tasaki eq. (7.1.25)). -/
theorem weylMap_isHomogeneous (Φ : (Fin L → Fin (N + 1)) → ℂ) :
    (weylMap Φ).IsHomogeneous (N * L) := by
  simp only [weylMap, Fintype.linearCombination_apply]
  refine IsHomogeneous.sum _ _ _ (fun σ _ => ?_)
  rw [weylMono, smul_monomial]
  exact isHomogeneous_monomial _ (md_degree σ)

/-- The **Weyl preimage** of a polynomial: the chain state reading off, at each configuration `τ`,
the coefficient of the Weyl monomial `X^{md τ}` normalized by the Clebsch–Gordan weight `cgNorm τ`
(the inverse of `weylMap_coeff`).  It inverts `weylMap` on the polynomials with the per-site degrees
of a Weyl image (`weylMap_weylPreimage`, one layer up where the per-site grading lives), and is what
turns an explicitly written polynomial — a boundary monomial times a product of bond factors — into
a state of the chain.  The site index `N` is not determined by `p` and must be supplied. -/
noncomputable def weylPreimage (p : MvPolynomial (Fin L × Fin 2) ℂ) :
    (Fin L → Fin (N + 1)) → ℂ :=
  fun τ => p.coeff (md τ) / cgNorm τ

end LatticeSystem.Math
