import LatticeSystem.Quantum.SpinS.AnisotropicHeisenbergSpinSCaseIIRawSupport
import LatticeSystem.Quantum.SpinS.ParityReachableNoParityBond
import LatticeSystem.Quantum.SpinS.ParityReachableNoSingleIon

/-!
# Case (ii): boundary move sets for the parity-gauged block matrix

Issue #412 (Tasaki §2.5 Theorem 2.4, Mattis--Nishimori).

This file records the case-(ii) boundary move-set variants of the shifted
parity-gauged block bridge.  At `lambda = 1`, the parity-bond branch is
excluded and the move set is generated by transverse and single-ion moves.  At
`D = 0`, the single-ion branch is excluded and the move set is generated by
transverse and parity-bond moves.

Reference: H. Tasaki, *Physics and Mathematics of Quantum Many-Body Systems*,
Springer 2020, §2.5 Theorem 2.4, pp. 43--44.
-/

namespace LatticeSystem.Quantum

open Matrix

variable {Λ : Type*} [Fintype Λ] [DecidableEq Λ] {N : ℕ}

/-! ## Boundary reachability on parity blocks -/

/-- Ion-only parity steps restricted to a fixed parity block. -/
def ionParityStepSOnBlock (G : SimpleGraph Λ) {p : ℕ}
    (σ τ : parityConfigS Λ N p) : Prop :=
  IonParityStepS G σ.1 τ.1

/-- Reflexive-transitive closure of ion-only parity steps in a fixed block. -/
def ionParityReachableSOnBlock (G : SimpleGraph Λ) {p : ℕ} :
    parityConfigS Λ N p → parityConfigS Λ N p → Prop :=
  Relation.ReflTransGen (ionParityStepSOnBlock (N := N) G)

/-- Bond-only parity steps restricted to a fixed parity block. -/
def bondParityStepSOnBlock (G : SimpleGraph Λ) {p : ℕ}
    (σ τ : parityConfigS Λ N p) : Prop :=
  BondParityStepS G σ.1 τ.1

/-- Reflexive-transitive closure of bond-only parity steps in a fixed block. -/
def bondParityReachableSOnBlock (G : SimpleGraph Λ) {p : ℕ} :
    parityConfigS Λ N p → parityConfigS Λ N p → Prop :=
  Relation.ReflTransGen (bondParityStepSOnBlock (N := N) G)

/-! ## Boundary step positivity -/

/-- At `lambda = 1`, every ion-only case-(ii) boundary step gives a strictly
positive shifted parity-gauged block entry. -/
theorem shiftedCaseIIBlock_pos_of_ion_step_lambda_one
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {D : ℂ} (hDim : D.im = 0) (hDneg : D.re < 0)
    (c : ℝ) {p : ℕ} {σ τ : parityConfigS Λ N p}
    (hstep : IonParityStepS (bipartiteCompleteGraphOf A) σ.1 τ.1) :
    0 < shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J 1 D N c p τ σ := by
  rcases hstep with hrl | hion
  · exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_pos_of_raiseLowerStepS
      A hJim hJnn hJpos hJself (by norm_num) (by norm_num) c hrl
  · exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_pos_of_singleIonStepS
      A hJself hDim hDneg c hion

/-- At `D = 0`, every bond-only case-(ii) boundary step gives a strictly
positive shifted parity-gauged block entry. -/
theorem shiftedCaseIIBlock_pos_of_bond_step_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {lam : ℂ} (hlam : lam.im = 0) (hlb : -1 < lam.re) (hlam_gt : 1 < lam.re)
    (c : ℝ) {p : ℕ} {σ τ : parityConfigS Λ N p}
    (hstep : BondParityStepS (bipartiteCompleteGraphOf A) σ.1 τ.1) :
    0 < shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p τ σ := by
  rcases hstep with hrl | hbond
  · exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_pos_of_raiseLowerStepS
      A hJim hJnn hJpos hJself hlam hlb c hrl
  · exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_pos_of_parityBondStepS
      A hJim hJnn hJpos hJself hlam hlam_gt c hbond

/-! ## Boundary path positivity -/

/-- Matrix-power positivity from ion-only block reachability at `lambda = 1`. -/
theorem shiftedCaseIIBlock_pow_pos_of_ion_reachable_lambda_one
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {D : ℂ} (hDim : D.im = 0) (hDneg : D.re < 0)
    {c : ℝ} {p : ℕ}
    (hB_nn : ∀ σ τ : parityConfigS Λ N p,
      0 ≤ shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J 1 D N c p σ τ)
    {σ σ' : parityConfigS Λ N p}
    (hreach : ionParityReachableSOnBlock (bipartiteCompleteGraphOf A) σ σ') :
    ∃ k : ℕ,
      0 < (shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J 1 D N c p ^ k)
        σ' σ := by
  induction hreach with
  | refl =>
      exact ⟨0, by simp [Matrix.one_apply_eq]⟩
  | tail _h₁ h₂ ih =>
      obtain ⟨k, hpos⟩ := ih
      refine ⟨k + 1, ?_⟩
      rw [pow_succ', Matrix.mul_apply]
      apply Finset.sum_pos'
      · intro l _
        exact mul_nonneg (hB_nn _ _) (Matrix.pow_apply_nonneg hB_nn _ _ _)
      · exact ⟨_, Finset.mem_univ _,
          mul_pos
            (shiftedCaseIIBlock_pos_of_ion_step_lambda_one
              A hJim hJnn hJpos hJself hDim hDneg c h₂)
            hpos⟩

/-- Matrix-power positivity from bond-only block reachability at `D = 0`. -/
theorem shiftedCaseIIBlock_pow_pos_of_bond_reachable_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {lam : ℂ} (hlam : lam.im = 0) (hlb : -1 < lam.re) (hlam_gt : 1 < lam.re)
    {c : ℝ} {p : ℕ}
    (hB_nn : ∀ σ τ : parityConfigS Λ N p,
      0 ≤ shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p σ τ)
    {σ σ' : parityConfigS Λ N p}
    (hreach : bondParityReachableSOnBlock (bipartiteCompleteGraphOf A) σ σ') :
    ∃ k : ℕ,
      0 < (shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p ^ k)
        σ' σ := by
  induction hreach with
  | refl =>
      exact ⟨0, by simp [Matrix.one_apply_eq]⟩
  | tail _h₁ h₂ ih =>
      obtain ⟨k, hpos⟩ := ih
      refine ⟨k + 1, ?_⟩
      rw [pow_succ', Matrix.mul_apply]
      apply Finset.sum_pos'
      · intro l _
        exact mul_nonneg (hB_nn _ _) (Matrix.pow_apply_nonneg hB_nn _ _ _)
      · exact ⟨_, Finset.mem_univ _,
          mul_pos
            (shiftedCaseIIBlock_pos_of_bond_step_D_zero
              A hJim hJnn hJpos hJself hlam hlb hlam_gt c h₂)
            hpos⟩

/-! ## Boundary step-support non-negativity -/

/-! ## Raw support at the `lambda = 1` boundary -/

/-- At `lambda = 1`, a local parity-bond witness has zero axis-swapped bond
entry because the `(1 - lambda) / 4` parity-ladder coefficient vanishes, while
the transverse ladder terms mismatch the same-direction move. -/
theorem spinSDotXXZSwap_apply_eq_zero_of_parityBondStepS_witness_lambda_one
    {x y : Λ} (hxy : x ≠ y)
    {σ' σ : Λ → Fin (N + 1)}
    (hsh : ((σ x).val + 1 = (σ' x).val ∧ (σ y).val + 1 = (σ' y).val) ∨
      ((σ' x).val + 1 = (σ x).val ∧ (σ' y).val + 1 = (σ y).val))
    (hagree : ∀ k, k ≠ x → k ≠ y → σ' k = σ k) :
    spinSDotXXZSwap x y (1 : ℂ) N σ' σ = 0 := by
  have hne : σ' ≠ σ := by
    intro he
    rcases hsh with ⟨hsx, _⟩ | ⟨hsx, _⟩ <;> · rw [he] at hsx; omega
  have hladder :=
    congrFun (congrFun (spinSDotXXZSwap_ladder_form (Λ := Λ) (N := N) x y (1 : ℂ)) σ') σ
  rw [hladder, Matrix.add_apply, Matrix.add_apply, Matrix.smul_apply, Matrix.smul_apply,
    smul_eq_mul, smul_eq_mul,
    onSiteS_spinSOp3_mul_onSiteS_spinSOp3_apply_eq_zero_of_ne hxy hne, add_zero]
  rcases hsh with ⟨hsx, hsy⟩ | ⟨hsx, hsy⟩
  · have h1 :
        ((onSiteS x (spinSOpPlus N) * onSiteS y (spinSOpMinus N) :
          ManyBodyOpS Λ N) σ' σ) = 0 := by
      rw [onSiteS_spinSOpPlus_mul_onSiteS_spinSOpMinus_apply_of_off_two_site_agree
        hxy hagree, spinSOpPlus_apply_other N
        (by omega : (σ' x).val + 1 ≠ (σ x).val), zero_mul]
    have h2 :
        ((onSiteS x (spinSOpMinus N) * onSiteS y (spinSOpPlus N) :
          ManyBodyOpS Λ N) σ' σ) = 0 := by
      rw [onSiteS_spinSOpMinus_mul_onSiteS_spinSOpPlus_apply_of_off_two_site_agree
        hxy hagree, spinSOpPlus_apply_other N
        (by omega : (σ' y).val + 1 ≠ (σ y).val), mul_zero]
    rw [Matrix.add_apply, Matrix.add_apply, h1, h2]
    norm_num
  · have h1 :
        ((onSiteS x (spinSOpPlus N) * onSiteS y (spinSOpMinus N) :
          ManyBodyOpS Λ N) σ' σ) = 0 := by
      rw [onSiteS_spinSOpPlus_mul_onSiteS_spinSOpMinus_apply_of_off_two_site_agree
        hxy hagree, spinSOpMinus_apply_other N
        (by omega : (σ y).val + 1 ≠ (σ' y).val), mul_zero]
    have h2 :
        ((onSiteS x (spinSOpMinus N) * onSiteS y (spinSOpPlus N) :
          ManyBodyOpS Λ N) σ' σ) = 0 := by
      rw [onSiteS_spinSOpMinus_mul_onSiteS_spinSOpPlus_apply_of_off_two_site_agree
        hxy hagree, spinSOpMinus_apply_other N
        (by omega : (σ x).val + 1 ≠ (σ' x).val), zero_mul]
    rw [Matrix.add_apply, Matrix.add_apply, h1, h2]
    norm_num

/-- At `lambda = 1`, a raw parity-bond step has zero dressed real entry: the
only possible ordered bond contributions are the two witness orientations, and
both vanish by the zero parity-ladder coefficient. -/
theorem dressedAxisSwappedReMatrix_zero_of_parityBondStep_lambda_one
    (A : Λ → Bool) {J : Λ → Λ → ℂ} (hJself : ∀ x, J x x = 0)
    {D : ℂ}
    {σ' σ : Λ → Fin (N + 1)}
    (hstep : ParityBondStepS (bipartiteCompleteGraphOf A) σ σ') :
    dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N σ' σ = 0 := by
  obtain ⟨x, y, hadj, hsh, hagree⟩ := hstep
  have hxy : x ≠ y := hadj.ne
  have hx_ne : σ' x ≠ σ x := by
    intro h
    rcases hsh with ⟨hsx, _⟩ | ⟨hsx, _⟩ <;> · rw [h] at hsx; omega
  have hy_ne : σ' y ≠ σ y := by
    intro h
    rcases hsh with ⟨_, hsy⟩ | ⟨_, hsy⟩ <;> · rw [h] at hsy; omega
  have hsh_yx :
      ((σ y).val + 1 = (σ' y).val ∧ (σ x).val + 1 = (σ' x).val) ∨
        ((σ' y).val + 1 = (σ y).val ∧ (σ' x).val + 1 = (σ x).val) := by
    rcases hsh with ⟨hsx, hsy⟩ | ⟨hsx, hsy⟩
    · exact Or.inl ⟨hsy, hsx⟩
    · exact Or.inr ⟨hsy, hsx⟩
  have hagree_yx : ∀ k, k ≠ y → k ≠ x → σ' k = σ k := fun k hky hkx => hagree k hkx hky
  have hbonds_zero :
      ((∑ a : Λ, ∑ b : Λ, J a b • spinSDotXXZSwap a b (1 : ℂ) N : ManyBodyOpS Λ N)
        σ' σ) = 0 := by
    rw [Matrix.sum_apply]
    refine Finset.sum_eq_zero (fun a _ => ?_)
    rw [Matrix.sum_apply]
    refine Finset.sum_eq_zero (fun b _ => ?_)
    rw [Matrix.smul_apply, smul_eq_mul]
    by_cases hab : a = b
    · subst a
      rw [hJself b, zero_mul]
    · by_cases hagree_ab : ∀ k, k ≠ a → k ≠ b → σ' k = σ k
      · have hpair := pair_or_swap_of_agree_off_two_site_two_diff hxy hx_ne hy_ne hagree_ab
        rcases hpair with ⟨ha, hb⟩ | ⟨ha, hb⟩
        · subst a
          subst b
          rw [spinSDotXXZSwap_apply_eq_zero_of_parityBondStepS_witness_lambda_one
            hxy hsh hagree, mul_zero]
        · subst a
          subst b
          rw [spinSDotXXZSwap_apply_eq_zero_of_parityBondStepS_witness_lambda_one
            hxy.symm hsh_yx hagree_yx, mul_zero]
      · rw [spinSDotXXZSwap_apply_eq_zero_of_not_agree hab (1 : ℂ) hagree_ab, mul_zero]
  have hsingle_zero : singleIonAnisotropyS2 D N σ' σ = 0 :=
    singleIonAnisotropyS2_apply_eq_zero_of_two_site_diff hxy hx_ne hy_ne
  rw [dressedAxisSwappedAnisotropicHeisenbergSReMatrix_apply,
    dressedAxisSwappedAnisotropicHeisenbergS_apply,
    axisSwappedAnisotropicHeisenbergS_def, Matrix.add_apply, hbonds_zero,
    hsingle_zero, zero_add, mul_zero, Complex.zero_re]

/-- At `lambda = 1`, target-raised raw support reduces to a single-ion step
or zero. -/
theorem dressedAxisSwappedReMatrix_single_or_zero_of_magSum_add_two_lambda_one
    (A : Λ → Bool) {J : Λ → Λ → ℂ} (hJself : ∀ x, J x x = 0)
    (hJsupp : ∀ x y, ¬ (bipartiteCompleteGraphOf A).Adj x y → J x y = 0)
    {D : ℂ}
    {σ' σ : Λ → Fin (N + 1)} (hne : σ' ≠ σ)
    (hmag : magSumS σ' = magSumS σ + 2) :
    SingleIonStepS σ σ' ∨
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N σ' σ = 0 := by
  rcases dressedAxisSwappedReMatrix_parity_or_single_or_zero_of_magSum_add_two
      A hJsupp hne hmag with hbond | hsingle | hzero
  · exact Or.inr (dressedAxisSwappedReMatrix_zero_of_parityBondStep_lambda_one A hJself hbond)
  · exact Or.inl hsingle
  · exact Or.inr hzero

/-- At `lambda = 1`, source-raised raw support reduces to a single-ion step
or zero. -/
theorem dressedAxisSwappedReMatrix_single_or_zero_of_add_two_magSum_lambda_one
    (A : Λ → Bool) {J : Λ → Λ → ℂ} (hJself : ∀ x, J x x = 0)
    (hJsupp : ∀ x y, ¬ (bipartiteCompleteGraphOf A).Adj x y → J x y = 0)
    {D : ℂ}
    {σ' σ : Λ → Fin (N + 1)} (hne : σ' ≠ σ)
    (hmag : magSumS σ' + 2 = magSumS σ) :
    SingleIonStepS σ σ' ∨
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N σ' σ = 0 := by
  rcases dressedAxisSwappedReMatrix_parity_or_single_or_zero_of_add_two_magSum
      A hJsupp hne hmag with hbond | hsingle | hzero
  · exact Or.inr (dressedAxisSwappedReMatrix_zero_of_parityBondStep_lambda_one A hJself hbond)
  · exact Or.inl hsingle
  · exact Or.inr hzero


end LatticeSystem.Quantum
