import LatticeSystem.Quantum.SpinS.AnisotropicHeisenbergSpinSCaseIIRawSupport
import LatticeSystem.Quantum.SpinS.ParityReachableNoParityBond
import LatticeSystem.Quantum.SpinS.ParityReachableNoSingleIon

/-!
# Case (ii): boundary move sets for the parity-gauged block matrix

Issue #412 (Tasaki §2.5 Theorem 2.4, Mattis--Nishimori).

This file records the case-(ii) boundary move-set variants of the shifted
parity-gauged block bridge.  At `lambda = 1`, the parity-bond branch is
excluded and the move set is generated by transverse and single-ion moves.  At
`D = 0`, the single-ion branch is excluded and the move set is generated by
transverse and parity-bond moves.

Reference: H. Tasaki, *Physics and Mathematics of Quantum Many-Body Systems*,
Springer 2020, §2.5 Theorem 2.4, pp. 43--44.
-/

namespace LatticeSystem.Quantum

open Matrix

variable {Λ : Type*} [Fintype Λ] [DecidableEq Λ] {N : ℕ}

/-! ## Boundary reachability on parity blocks -/

/-- Ion-only parity steps restricted to a fixed parity block. -/
def ionParityStepSOnBlock (G : SimpleGraph Λ) {p : ℕ}
    (σ τ : parityConfigS Λ N p) : Prop :=
  IonParityStepS G σ.1 τ.1

/-- Reflexive-transitive closure of ion-only parity steps in a fixed block. -/
def ionParityReachableSOnBlock (G : SimpleGraph Λ) {p : ℕ} :
    parityConfigS Λ N p → parityConfigS Λ N p → Prop :=
  Relation.ReflTransGen (ionParityStepSOnBlock (N := N) G)

/-- Bond-only parity steps restricted to a fixed parity block. -/
def bondParityStepSOnBlock (G : SimpleGraph Λ) {p : ℕ}
    (σ τ : parityConfigS Λ N p) : Prop :=
  BondParityStepS G σ.1 τ.1

/-- Reflexive-transitive closure of bond-only parity steps in a fixed block. -/
def bondParityReachableSOnBlock (G : SimpleGraph Λ) {p : ℕ} :
    parityConfigS Λ N p → parityConfigS Λ N p → Prop :=
  Relation.ReflTransGen (bondParityStepSOnBlock (N := N) G)

/-! ## Boundary step positivity -/

/-- At `lambda = 1`, every ion-only case-(ii) boundary step gives a strictly
positive shifted parity-gauged block entry. -/
theorem shiftedCaseIIBlock_pos_of_ion_step_lambda_one
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {D : ℂ} (hDim : D.im = 0) (hDneg : D.re < 0)
    (c : ℝ) {p : ℕ} {σ τ : parityConfigS Λ N p}
    (hstep : IonParityStepS (bipartiteCompleteGraphOf A) σ.1 τ.1) :
    0 < shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J 1 D N c p τ σ := by
  rcases hstep with hrl | hion
  · exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_pos_of_raiseLowerStepS
      A hJim hJnn hJpos hJself (by norm_num) (by norm_num) c hrl
  · exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_pos_of_singleIonStepS
      A hJself hDim hDneg c hion

/-- At `D = 0`, every bond-only case-(ii) boundary step gives a strictly
positive shifted parity-gauged block entry. -/
theorem shiftedCaseIIBlock_pos_of_bond_step_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {lam : ℂ} (hlam : lam.im = 0) (hlb : -1 < lam.re) (hlam_gt : 1 < lam.re)
    (c : ℝ) {p : ℕ} {σ τ : parityConfigS Λ N p}
    (hstep : BondParityStepS (bipartiteCompleteGraphOf A) σ.1 τ.1) :
    0 < shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p τ σ := by
  rcases hstep with hrl | hbond
  · exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_pos_of_raiseLowerStepS
      A hJim hJnn hJpos hJself hlam hlb c hrl
  · exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_pos_of_parityBondStepS
      A hJim hJnn hJpos hJself hlam hlam_gt c hbond

/-! ## Boundary path positivity -/

/-- Matrix-power positivity from ion-only block reachability at `lambda = 1`. -/
theorem shiftedCaseIIBlock_pow_pos_of_ion_reachable_lambda_one
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {D : ℂ} (hDim : D.im = 0) (hDneg : D.re < 0)
    {c : ℝ} {p : ℕ}
    (hB_nn : ∀ σ τ : parityConfigS Λ N p,
      0 ≤ shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J 1 D N c p σ τ)
    {σ σ' : parityConfigS Λ N p}
    (hreach : ionParityReachableSOnBlock (bipartiteCompleteGraphOf A) σ σ') :
    ∃ k : ℕ,
      0 < (shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J 1 D N c p ^ k)
        σ' σ := by
  induction hreach with
  | refl =>
      exact ⟨0, by simp [Matrix.one_apply_eq]⟩
  | tail _h₁ h₂ ih =>
      obtain ⟨k, hpos⟩ := ih
      refine ⟨k + 1, ?_⟩
      rw [pow_succ', Matrix.mul_apply]
      apply Finset.sum_pos'
      · intro l _
        exact mul_nonneg (hB_nn _ _) (Matrix.pow_apply_nonneg hB_nn _ _ _)
      · exact ⟨_, Finset.mem_univ _,
          mul_pos
            (shiftedCaseIIBlock_pos_of_ion_step_lambda_one
              A hJim hJnn hJpos hJself hDim hDneg c h₂)
            hpos⟩

/-- Matrix-power positivity from bond-only block reachability at `D = 0`. -/
theorem shiftedCaseIIBlock_pow_pos_of_bond_reachable_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {lam : ℂ} (hlam : lam.im = 0) (hlb : -1 < lam.re) (hlam_gt : 1 < lam.re)
    {c : ℝ} {p : ℕ}
    (hB_nn : ∀ σ τ : parityConfigS Λ N p,
      0 ≤ shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p σ τ)
    {σ σ' : parityConfigS Λ N p}
    (hreach : bondParityReachableSOnBlock (bipartiteCompleteGraphOf A) σ σ') :
    ∃ k : ℕ,
      0 < (shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p ^ k)
        σ' σ := by
  induction hreach with
  | refl =>
      exact ⟨0, by simp [Matrix.one_apply_eq]⟩
  | tail _h₁ h₂ ih =>
      obtain ⟨k, hpos⟩ := ih
      refine ⟨k + 1, ?_⟩
      rw [pow_succ', Matrix.mul_apply]
      apply Finset.sum_pos'
      · intro l _
        exact mul_nonneg (hB_nn _ _) (Matrix.pow_apply_nonneg hB_nn _ _ _)
      · exact ⟨_, Finset.mem_univ _,
          mul_pos
            (shiftedCaseIIBlock_pos_of_bond_step_D_zero
              A hJim hJnn hJpos hJself hlam hlb hlam_gt c h₂)
            hpos⟩

/-! ## Boundary step-support non-negativity -/

/-! ## Raw support at the `D = 0` boundary -/

/-- At `D = 0`, a raw single-ion step has zero dressed real entry: bond terms
vanish by the same-site `±2` pattern, and the single-ion coefficient is zero. -/
theorem dressedAxisSwappedReMatrix_zero_of_singleIonStep_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ} (hJself : ∀ x, J x x = 0)
    {lam : ℂ}
    {σ' σ : Λ → Fin (N + 1)} (hstep : SingleIonStepS σ σ') :
    dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N σ' σ = 0 := by
  obtain ⟨x, hsx, hagree⟩ := hstep
  have hbonds_zero :
      ((∑ a : Λ, ∑ b : Λ, J a b • spinSDotXXZSwap a b lam N : ManyBodyOpS Λ N)
        σ' σ) = 0 := by
    rw [Matrix.sum_apply]
    refine Finset.sum_eq_zero (fun a _ => ?_)
    rw [Matrix.sum_apply]
    refine Finset.sum_eq_zero (fun b _ => ?_)
    rw [Matrix.smul_apply, smul_eq_mul]
    by_cases hab : a = b
    · subst a
      rw [hJself b, zero_mul]
    · rw [spinSDotXXZSwap_apply_eq_zero_of_singleIonStep hab lam hsx hagree, mul_zero]
  have hsingle_zero : singleIonAnisotropyS2 (Λ := Λ) (0 : ℂ) N σ' σ = 0 := by
    rw [singleIonAnisotropyS2, zero_smul]
    rfl
  rw [dressedAxisSwappedAnisotropicHeisenbergSReMatrix_apply,
    dressedAxisSwappedAnisotropicHeisenbergS_apply,
    axisSwappedAnisotropicHeisenbergS_def, Matrix.add_apply, hbonds_zero,
    hsingle_zero, zero_add, mul_zero, Complex.zero_re]

/-- At `D = 0`, target-raised raw support reduces to a bond step or zero. -/
theorem dressedAxisSwappedReMatrix_bond_or_zero_of_magSum_add_two_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ} (hJself : ∀ x, J x x = 0)
    (hJsupp : ∀ x y, ¬ (bipartiteCompleteGraphOf A).Adj x y → J x y = 0)
    {lam : ℂ}
    {σ' σ : Λ → Fin (N + 1)} (hne : σ' ≠ σ)
    (hmag : magSumS σ' = magSumS σ + 2) :
    ParityBondStepS (bipartiteCompleteGraphOf A) σ σ' ∨
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N σ' σ = 0 := by
  rcases dressedAxisSwappedReMatrix_parity_or_single_or_zero_of_magSum_add_two
      A hJsupp hne hmag with hbond | hsingle | hzero
  · exact Or.inl hbond
  · exact Or.inr (dressedAxisSwappedReMatrix_zero_of_singleIonStep_D_zero A hJself hsingle)
  · exact Or.inr hzero

/-- At `D = 0`, source-raised raw support reduces to a bond step or zero. -/
theorem dressedAxisSwappedReMatrix_bond_or_zero_of_add_two_magSum_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ} (hJself : ∀ x, J x x = 0)
    (hJsupp : ∀ x y, ¬ (bipartiteCompleteGraphOf A).Adj x y → J x y = 0)
    {lam : ℂ}
    {σ' σ : Λ → Fin (N + 1)} (hne : σ' ≠ σ)
    (hmag : magSumS σ' + 2 = magSumS σ) :
    ParityBondStepS (bipartiteCompleteGraphOf A) σ σ' ∨
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N σ' σ = 0 := by
  rcases dressedAxisSwappedReMatrix_parity_or_single_or_zero_of_add_two_magSum
      A hJsupp hne hmag with hbond | hsingle | hzero
  · exact Or.inl hbond
  · exact Or.inr (dressedAxisSwappedReMatrix_zero_of_singleIonStep_D_zero A hJself hsingle)
  · exact Or.inr hzero

/-- Entrywise non-negativity at `lambda = 1` from an ion-only step-or-zero
support split. -/
theorem shiftedCaseIIBlock_nonneg_of_ion_step_support_lambda_one
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {D : ℂ} (hDim : D.im = 0) (hDneg : D.re < 0)
    {c : ℝ} (p : ℕ)
    (hc : ∀ σ : parityConfigS Λ N p,
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N σ.1 σ.1 ≤ c)
    (heq_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 = magSumS σ.1 →
      RaiseLowerStepS (bipartiteCompleteGraphOf A) σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N τ.1 σ.1 = 0)
    (hup_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 = magSumS σ.1 + 2 →
      SingleIonStepS σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N τ.1 σ.1 = 0)
    (hdown_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 + 2 = magSumS σ.1 →
      SingleIonStepS σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N τ.1 σ.1 = 0)
    (hzero : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 ≠ magSumS σ.1 →
      magSumS τ.1 ≠ magSumS σ.1 + 2 →
      magSumS τ.1 + 2 ≠ magSumS σ.1 →
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N τ.1 σ.1 = 0)
    (σ τ : parityConfigS Λ N p) :
    0 ≤ shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J 1 D N c p σ τ := by
  refine shiftedCaseIIParityGaugedBlock_nonneg_of_magSum_support
    A J 1 D N p hc ?_ ?_ ?_ ?_ σ τ
  · intro σ τ hne hmag
    rcases heq_step hne hmag with hstep | hzero_entry
    · exact dressedAxisSwappedAnisotropicHeisenbergSReMatrix_apply_nonpos_of_raiseLowerStepS_caseII
        A hJim hJnn hJpos hJself (by norm_num) (by norm_num) hstep
    · rw [hzero_entry]
  · intro σ τ hne hmag
    rcases hup_step hne hmag with hstep | hzero_entry
    · exact dressedAxisSwappedAnisotropicHeisenbergSReMatrix_apply_nonneg_of_singleIonStepS_caseII
        A hJself hDim hDneg hstep
    · rw [hzero_entry]
  · intro σ τ hne hmag
    rcases hdown_step hne hmag with hstep | hzero_entry
    · exact dressedAxisSwappedAnisotropicHeisenbergSReMatrix_apply_nonneg_of_singleIonStepS_caseII
        A hJself hDim hDneg hstep
    · rw [hzero_entry]
  · intro σ τ hne hmag_eq hmag_up hmag_down
    exact caseIIParityGaugedAxisSwappedReMatrixOnParityBlock_eq_zero_of_dressed_zero
      A J 1 D N p (hzero hne hmag_eq hmag_up hmag_down)

/-- Entrywise non-negativity at `D = 0` from a bond-only step-or-zero support
split. -/
theorem shiftedCaseIIBlock_nonneg_of_bond_step_support_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {lam : ℂ} (hlam : lam.im = 0) (hlb : -1 < lam.re) (hlam_gt : 1 < lam.re)
    {c : ℝ} (p : ℕ)
    (hc : ∀ σ : parityConfigS Λ N p,
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N σ.1 σ.1 ≤ c)
    (heq_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 = magSumS σ.1 →
      RaiseLowerStepS (bipartiteCompleteGraphOf A) σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N τ.1 σ.1 = 0)
    (hup_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 = magSumS σ.1 + 2 →
      ParityBondStepS (bipartiteCompleteGraphOf A) σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N τ.1 σ.1 = 0)
    (hdown_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 + 2 = magSumS σ.1 →
      ParityBondStepS (bipartiteCompleteGraphOf A) σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N τ.1 σ.1 = 0)
    (hzero : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 ≠ magSumS σ.1 →
      magSumS τ.1 ≠ magSumS σ.1 + 2 →
      magSumS τ.1 + 2 ≠ magSumS σ.1 →
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N τ.1 σ.1 = 0)
    (σ τ : parityConfigS Λ N p) :
    0 ≤ shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p σ τ := by
  refine shiftedCaseIIParityGaugedBlock_nonneg_of_magSum_support
    A J lam 0 N p hc ?_ ?_ ?_ ?_ σ τ
  · intro σ τ hne hmag
    rcases heq_step hne hmag with hstep | hzero_entry
    · exact dressedAxisSwappedAnisotropicHeisenbergSReMatrix_apply_nonpos_of_raiseLowerStepS_caseII
        A hJim hJnn hJpos hJself hlam hlb hstep
    · rw [hzero_entry]
  · intro σ τ hne hmag
    rcases hup_step hne hmag with hstep | hzero_entry
    · exact dressedAxisSwappedAnisotropicHeisenbergSReMatrix_apply_nonneg_of_parityBondStepS_caseII
        A hJim hJnn hJpos hJself hlam hlam_gt hstep
    · rw [hzero_entry]
  · intro σ τ hne hmag
    rcases hdown_step hne hmag with hstep | hzero_entry
    · exact dressedAxisSwappedAnisotropicHeisenbergSReMatrix_apply_nonneg_of_parityBondStepS_caseII
        A hJim hJnn hJpos hJself hlam hlam_gt hstep
    · rw [hzero_entry]
  · intro σ τ hne hmag_eq hmag_up hmag_down
    exact caseIIParityGaugedAxisSwappedReMatrixOnParityBlock_eq_zero_of_dressed_zero
      A J lam 0 N p (hzero hne hmag_eq hmag_up hmag_down)

/-- Entrywise non-negativity at `D = 0` from raw total-Hamiltonian support. -/
theorem shiftedCaseIIBlock_nonneg_of_raw_support_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    (hJsupp : ∀ x y, ¬ (bipartiteCompleteGraphOf A).Adj x y → J x y = 0)
    {lam : ℂ} (hlam : lam.im = 0) (hlb : -1 < lam.re) (hlam_gt : 1 < lam.re)
    {c : ℝ} (p : ℕ)
    (hc : ∀ σ : parityConfigS Λ N p,
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N σ.1 σ.1 ≤ c)
    (σ τ : parityConfigS Λ N p) :
    0 ≤ shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p σ τ := by
  refine shiftedCaseIIBlock_nonneg_of_bond_step_support_D_zero
    A hJim hJnn hJpos hJself hlam hlb hlam_gt p hc ?_ ?_ ?_ ?_ σ τ
  · intro σ τ hne hmag
    have hne_val : τ.1 ≠ σ.1 := fun h => hne (Subtype.ext h)
    exact dressedAxisSwappedReMatrix_raiseLower_or_zero_of_magSum_eq
      A hJsupp hne_val hmag
  · intro σ τ hne hmag
    have hne_val : τ.1 ≠ σ.1 := fun h => hne (Subtype.ext h)
    exact dressedAxisSwappedReMatrix_bond_or_zero_of_magSum_add_two_D_zero
      A hJself hJsupp hne_val hmag
  · intro σ τ hne hmag
    have hne_val : τ.1 ≠ σ.1 := fun h => hne (Subtype.ext h)
    exact dressedAxisSwappedReMatrix_bond_or_zero_of_add_two_magSum_D_zero
      A hJself hJsupp hne_val hmag
  · intro σ τ hne hmag_eq hmag_up hmag_down
    have hne_val : τ.1 ≠ σ.1 := fun h => hne (Subtype.ext h)
    exact dressedAxisSwappedAnisotropicHeisenbergSReMatrix_apply_eq_zero_of_not_magSum_step
      A hJsupp hne_val hmag_eq hmag_up hmag_down

/-! ## Boundary conditional irreducibility -/

/-- Conditional irreducibility at `lambda = 1` from ion-only support and
ion-only block reachability. -/
theorem shiftedCaseIIBlock_irreducible_of_ion_step_support_lambda_one
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {D : ℂ} (hDim : D.im = 0) (hDneg : D.re < 0)
    {c : ℝ} (p : ℕ)
    (hc_strict : ∀ σ : parityConfigS Λ N p,
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N σ.1 σ.1 < c)
    (heq_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 = magSumS σ.1 →
      RaiseLowerStepS (bipartiteCompleteGraphOf A) σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N τ.1 σ.1 = 0)
    (hup_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 = magSumS σ.1 + 2 →
      SingleIonStepS σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N τ.1 σ.1 = 0)
    (hdown_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 + 2 = magSumS σ.1 →
      SingleIonStepS σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N τ.1 σ.1 = 0)
    (hzero : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 ≠ magSumS σ.1 →
      magSumS τ.1 ≠ magSumS σ.1 + 2 →
      magSumS τ.1 + 2 ≠ magSumS σ.1 →
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N τ.1 σ.1 = 0)
    [Nonempty (parityConfigS Λ N p)]
    (hreach_total : ∀ σ' σ : parityConfigS Λ N p, σ' ≠ σ →
      ionParityReachableSOnBlock (bipartiteCompleteGraphOf A) σ σ') :
    (shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J 1 D N c p).IsIrreducible := by
  have hc_le : ∀ σ : parityConfigS Λ N p,
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J 1 D N σ.1 σ.1 ≤ c :=
    fun σ => le_of_lt (hc_strict σ)
  have hB_nn : ∀ σ τ : parityConfigS Λ N p,
      0 ≤ shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J 1 D N c p σ τ :=
    shiftedCaseIIBlock_nonneg_of_ion_step_support_lambda_one
      A hJim hJnn hJpos hJself hDim hDneg p hc_le heq_step hup_step hdown_step hzero
  rw [Matrix.isIrreducible_iff_exists_pow_pos hB_nn]
  intro σ' σ
  by_cases hsig : σ' = σ
  · subst hsig
    refine ⟨1, one_pos, ?_⟩
    rw [pow_one]
    exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_diag_pos
      A J 1 D N p (hc_strict σ')
  · obtain ⟨k, hk⟩ :=
      shiftedCaseIIBlock_pow_pos_of_ion_reachable_lambda_one
        A hJim hJnn hJpos hJself hDim hDneg hB_nn (hreach_total σ' σ hsig)
    have hk_pos : 0 < k := by
      rcases Nat.eq_zero_or_pos k with hk0 | hkp
      · subst hk0
        rw [pow_zero, Matrix.one_apply_ne hsig] at hk
        exact absurd hk (lt_irrefl 0)
      · exact hkp
    exact ⟨k, hk_pos, hk⟩

/-- Conditional irreducibility at `D = 0` from bond-only support and bond-only
block reachability. -/
theorem shiftedCaseIIBlock_irreducible_of_bond_step_support_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    {lam : ℂ} (hlam : lam.im = 0) (hlb : -1 < lam.re) (hlam_gt : 1 < lam.re)
    {c : ℝ} (p : ℕ)
    (hc_strict : ∀ σ : parityConfigS Λ N p,
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N σ.1 σ.1 < c)
    (heq_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 = magSumS σ.1 →
      RaiseLowerStepS (bipartiteCompleteGraphOf A) σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N τ.1 σ.1 = 0)
    (hup_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 = magSumS σ.1 + 2 →
      ParityBondStepS (bipartiteCompleteGraphOf A) σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N τ.1 σ.1 = 0)
    (hdown_step : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 + 2 = magSumS σ.1 →
      ParityBondStepS (bipartiteCompleteGraphOf A) σ.1 τ.1 ∨
        dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N τ.1 σ.1 = 0)
    (hzero : ∀ {σ τ : parityConfigS Λ N p}, τ ≠ σ →
      magSumS τ.1 ≠ magSumS σ.1 →
      magSumS τ.1 ≠ magSumS σ.1 + 2 →
      magSumS τ.1 + 2 ≠ magSumS σ.1 →
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N τ.1 σ.1 = 0)
    [Nonempty (parityConfigS Λ N p)]
    (hreach_total : ∀ σ' σ : parityConfigS Λ N p, σ' ≠ σ →
      bondParityReachableSOnBlock (bipartiteCompleteGraphOf A) σ σ') :
    (shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p).IsIrreducible := by
  have hc_le : ∀ σ : parityConfigS Λ N p,
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N σ.1 σ.1 ≤ c :=
    fun σ => le_of_lt (hc_strict σ)
  have hB_nn : ∀ σ τ : parityConfigS Λ N p,
      0 ≤ shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p σ τ :=
    shiftedCaseIIBlock_nonneg_of_bond_step_support_D_zero
      A hJim hJnn hJpos hJself hlam hlb hlam_gt p hc_le heq_step hup_step hdown_step hzero
  rw [Matrix.isIrreducible_iff_exists_pow_pos hB_nn]
  intro σ' σ
  by_cases hsig : σ' = σ
  · subst hsig
    refine ⟨1, one_pos, ?_⟩
    rw [pow_one]
    exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_diag_pos
      A J lam 0 N p (hc_strict σ')
  · obtain ⟨k, hk⟩ :=
      shiftedCaseIIBlock_pow_pos_of_bond_reachable_D_zero
        A hJim hJnn hJpos hJself hlam hlb hlam_gt hB_nn (hreach_total σ' σ hsig)
    have hk_pos : 0 < k := by
      rcases Nat.eq_zero_or_pos k with hk0 | hkp
      · subst hk0
        rw [pow_zero, Matrix.one_apply_ne hsig] at hk
        exact absurd hk (lt_irrefl 0)
      · exact hkp
    exact ⟨k, hk_pos, hk⟩

/-- Conditional irreducibility at `D = 0` from raw support and bond-only block
reachability. -/
theorem shiftedCaseIIBlock_irreducible_of_raw_support_D_zero
    (A : Λ → Bool) {J : Λ → Λ → ℂ}
    (hJim : ∀ x y, (J x y).im = 0) (hJnn : ∀ x y, 0 ≤ (J x y).re)
    (hJpos : ∀ x y, (bipartiteCompleteGraphOf A).Adj x y → 0 < (J x y).re)
    (hJself : ∀ x, J x x = 0)
    (hJsupp : ∀ x y, ¬ (bipartiteCompleteGraphOf A).Adj x y → J x y = 0)
    {lam : ℂ} (hlam : lam.im = 0) (hlb : -1 < lam.re) (hlam_gt : 1 < lam.re)
    {c : ℝ} (p : ℕ)
    (hc_strict : ∀ σ : parityConfigS Λ N p,
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N σ.1 σ.1 < c)
    [Nonempty (parityConfigS Λ N p)]
    (hreach_total : ∀ σ' σ : parityConfigS Λ N p, σ' ≠ σ →
      bondParityReachableSOnBlock (bipartiteCompleteGraphOf A) σ σ') :
    (shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p).IsIrreducible := by
  have hc_le : ∀ σ : parityConfigS Λ N p,
      dressedAxisSwappedAnisotropicHeisenbergSReMatrix A J lam 0 N σ.1 σ.1 ≤ c :=
    fun σ => le_of_lt (hc_strict σ)
  have hB_nn : ∀ σ τ : parityConfigS Λ N p,
      0 ≤ shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock A J lam 0 N c p σ τ :=
    shiftedCaseIIBlock_nonneg_of_raw_support_D_zero
      A hJim hJnn hJpos hJself hJsupp hlam hlb hlam_gt p hc_le
  rw [Matrix.isIrreducible_iff_exists_pow_pos hB_nn]
  intro σ' σ
  by_cases hsig : σ' = σ
  · subst hsig
    refine ⟨1, one_pos, ?_⟩
    rw [pow_one]
    exact shiftedCaseIIParityGaugedAxisSwappedReMatrixOnParityBlock_diag_pos
      A J lam 0 N p (hc_strict σ')
  · obtain ⟨k, hk⟩ :=
      shiftedCaseIIBlock_pow_pos_of_bond_reachable_D_zero
        A hJim hJnn hJpos hJself hlam hlb hlam_gt hB_nn (hreach_total σ' σ hsig)
    have hk_pos : 0 < k := by
      rcases Nat.eq_zero_or_pos k with hk0 | hkp
      · subst hk0
        rw [pow_zero, Matrix.one_apply_ne hsig] at hk
        exact absurd hk (lt_irrefl 0)
      · exact hkp
    exact ⟨k, hk_pos, hk⟩

end LatticeSystem.Quantum
