import LatticeSystem.Lattice.HypercubicLattice
import LatticeSystem.Math.CStarAlgebra.State
import Mathlib.Algebra.Star.StarAlgHom
import Mathlib.Data.Fintype.Pi
import Mathlib.Data.Int.Interval
import Mathlib.Topology.Algebra.InfiniteSum.Basic

/-!
# Tasaki §4.3.1: ground states of the infinite-volume antiferromagnetic Heisenberg model

On the infinite hypercubic lattice `ℤᵈ` the antiferromagnetic Heisenberg model is treated through
its
algebra of local observables and its states (linear functionals giving expectation values), rather
than vectors in a Hilbert space.  Following Tasaki §4.3.1, we bundle the abstract data — the
`C*`-algebra of observables, the per-site spin operators `Ŝ_x^{(α)}`, and the translation
automorphisms `τ_x` — into `InfiniteSpinSystem`, and reuse the existing `C*`-algebra state machinery
(`IsState`, `WeakDual`).

**Definition 4.17**: a *translation-invariant* state `ω` is a **ground state** of the
antiferromagnetic Heisenberg model iff `ω(Ŝ_x · Ŝ_y) = ε_GS` for every nearest-neighbor bond
`{x, y} ∈ B∞` (eq. (4.3.1)), where `ε_GS` is the ground-state energy density (per bond).  This is
the
infinite-volume version of the finite-volume variational characterization, restricted to
translation-invariant states (cf. Definition A.25 / Theorem A.26).

This file sets up the infinite-volume spin system and records Definition 4.17.

Reference: Hal Tasaki, *Physics and Mathematics of Quantum Many-Body Systems* (1st ed., Springer,
2020), §4.3.1, Definition 4.17, eqs. (4.3.1)–(4.3.4), pp. 112–113.
-/

namespace LatticeSystem.Quantum

open scoped ComplexOrder

/-- The **infinite-volume spin system** on `ℤᵈ`: the abstract `C*`-algebra `A` of observables (the
quasi-local algebra), the per-site spin operators `spin x α = Ŝ_x^{(α)}` (`x ∈ ℤᵈ`, `α = 1, 2, 3`),
and the translation automorphisms `transl x = τ_x` (eq. (4.3.3), bundled as star-algebra
isomorphisms). -/
structure InfiniteSpinSystem (d : ℕ) (A : Type*) [CStarAlgebra A] [NormedSpace ℂ A]
    [StarModule ℂ A] where
  /-- The per-site spin operators `Ŝ_x^{(α)}`. -/
  spin : (Fin d → ℤ) → Fin 3 → A
  /-- The translation automorphisms `τ_x` (eq. (4.3.3)). -/
  transl : (Fin d → ℤ) → (A ≃⋆ₐ[ℂ] A)
  /-- `τ_0` is the identity (the translations form an action of `ℤᵈ`). -/
  transl_zero : ∀ a : A, transl 0 a = a
  /-- The translations compose additively: `τ_x ∘ τ_y = τ_{x+y}` (action law). -/
  transl_add : ∀ (x y : Fin d → ℤ) (a : A), transl x (transl y a) = transl (x + y) a
  /-- **Spin covariance** (eq. (4.3.3)): the translation `τ_x` moves the site-`y` spin operator to
  site `y + x`, `τ_x(Ŝ_y^{(α)}) = Ŝ_{y+x}^{(α)}`. -/
  transl_spin : ∀ (x y : Fin d → ℤ) (α : Fin 3), transl x (spin y α) = spin (y + x) α
  /-- The **algebra of local observables** `A_loc`, the `*`-subalgebra generated by the spin
  operators (each acting nontrivially on only finitely many sites). -/
  localAlg : StarSubalgebra ℂ A
  /-- The spin operators are local observables. -/
  spin_mem : ∀ (x : Fin d → ℤ) (α : Fin 3), spin x α ∈ localAlg

namespace InfiniteSpinSystem

variable {d : ℕ} {A : Type*} [CStarAlgebra A] [NormedSpace ℂ A] [StarModule ℂ A]

/-- A site `x ∈ ℤᵈ` is **even** when its coordinate sum is even (`ℤᵈ_even`, eq. (4.3.2)); this is
the
infinite-volume `A`-sublattice. -/
def evenSite (x : Fin d → ℤ) : Prop := (∑ i, x i) % 2 = 0

/-- `{x, y}` is a **nearest-neighbor bond** (`B∞`, eq. (4.3.1)) when `x` and `y` differ in exactly
one
coordinate by `±1`.  This is the adjacency of the graph-centric infinite hypercubic lattice
`LatticeSystem.Lattice.hypercubicLatticeGraph d`; the local wrapper is kept for the faithful §4.3
naming (cf. `bond_iff_adj`). -/
def bond (x y : Fin d → ℤ) : Prop :=
  (LatticeSystem.Lattice.hypercubicLatticeGraph d).Adj x y

/-- The nearest-neighbor `bond` predicate is exactly the adjacency of the infinite hypercubic
lattice graph, unfolded to its differ-in-one-coordinate-by-`±1` form. -/
theorem bond_iff_adj {x y : Fin d → ℤ} :
    bond x y ↔ ∃ i : Fin d, |x i - y i| = 1 ∧ ∀ j, j ≠ i → x j = y j :=
  LatticeSystem.Lattice.hypercubicLatticeGraph_adj

/-- The **bond spin–spin operator** `Ŝ_x · Ŝ_y = Σ_α Ŝ_x^{(α)} Ŝ_y^{(α)}`. -/
noncomputable def spinDot (S : InfiniteSpinSystem d A) (x y : Fin d → ℤ) : A :=
  ∑ α : Fin 3, S.spin x α * S.spin y α

/-- A state `ρ` is **translation invariant** when `ρ(τ_x a) = ρ(a)` for every observable `a` and
every **even** translation `x ∈ ℤᵈ_even`.  This is exactly Tasaki's convention for §4.3: he
restricts
the translations to the even sublattice `ℤᵈ_even`, "anticipating antiferromagnetic order" (the Néel
state is invariant under even translations but *not* under odd ones), and footnote 35 explicitly
notes this is a deliberate restriction of the general (all-`x`) notion to even translations.  So the
`evenSite` quantifier is faithful to Definition 4.17, not a weakening. -/
def TranslationInvariant (S : InfiniteSpinSystem d A) (ρ : WeakDual ℂ A) : Prop :=
  ∀ a : A, ∀ x : Fin d → ℤ, evenSite x → ρ (S.transl x a) = ρ a

/-- **Tasaki Definition 4.17 (ground state of the infinite-volume antiferromagnetic Heisenberg
model).**  Given the ground-state energy density `εGS` (per bond, eq. (4.3.4)), a state `ρ` is a
*ground state* iff it is a state, translation invariant, and assigns every nearest-neighbor bond the
energy density: `ρ(Ŝ_x · Ŝ_y) = εGS` for all `{x, y} ∈ B∞`. -/
def IsInfiniteVolumeGroundState (S : InfiniteSpinSystem d A) (εGS : ℝ) (ρ : WeakDual ℂ A) : Prop :=
  LatticeSystem.Math.IsState ρ ∧ TranslationInvariant S ρ ∧
    ∀ x y : Fin d → ℤ, bond x y → ρ (spinDot S x y) = (εGS : ℂ)

instance : DecidablePred (evenSite (d := d)) := fun x => Int.decEq ((∑ i, x i) % 2) 0

/-- The finite hypercubic box `Λ_n = {x ∈ ℤᵈ : −n < xᵢ ≤ n}` (even side length `2n`, volume `(2n)ᵈ`,
centered at the origin, cf. eq. (3.1.2)), as a `Finset`. -/
noncomputable def latticeBox (d n : ℕ) : Finset (Fin d → ℤ) :=
  LatticeSystem.Lattice.hypercubicBox d n

/-- The finite box `latticeBox d n` is the graph-centric `hypercubicBox d n`. -/
theorem latticeBox_eq_hypercubicBox (d n : ℕ) :
    latticeBox d n = LatticeSystem.Lattice.hypercubicBox d n := rfl

/-- The **bulk operator** `Â_n = Σ_{x ∈ Λ_n ∩ ℤᵈ_even} τ_x(Â)` (eq. (4.3.5)): the sum of the
translated observables over the even sites of the centered box `Λ_n` (side `2n`). -/
noncomputable def bulkOp (S : InfiniteSpinSystem d A) (Â : A) (n : ℕ) : A :=
  ∑ x ∈ (latticeBox d n).filter evenSite, S.transl x Â

/-- **Tasaki Definition 4.18 (ergodic state).**  A translation-invariant state `ρ` is *ergodic* iff,
for every self-adjoint **local** observable `Â ∈ A_loc`, the fluctuation of the bulk density
`Â_L / Lᵈ` (with side length `L = 2n`, volume `Lᵈ = (2n)ᵈ`) vanishes in the infinite-volume limit
(eq. (4.3.6)):
`lim_{n↑∞} [ ρ(Â_n²) / ((2n)ᵈ)² − (ρ(Â_n) / (2n)ᵈ)² ] = 0`.
The vanishing of the fluctuation is the law of large numbers for densities — the mark of a
macroscopically "healthy" state.  (`Â` self-adjoint makes `ρ(Â_n)` and `ρ(Â_n²)` real, so the real
parts carry the content; the index is shifted by one to avoid the empty `n = 0` box.) -/
def IsErgodic (S : InfiniteSpinSystem d A) (ρ : WeakDual ℂ A) : Prop :=
  LatticeSystem.Math.IsState ρ ∧ TranslationInvariant S ρ ∧
    ∀ Â : A, Â ∈ S.localAlg → IsSelfAdjoint Â →
      Filter.Tendsto
        (fun n : ℕ =>
          (ρ ((bulkOp S Â (n + 1)) ^ 2)).re / ((2 * ((n : ℝ) + 1)) ^ d) ^ 2
            - ((ρ (bulkOp S Â (n + 1))).re / (2 * ((n : ℝ) + 1)) ^ d) ^ 2)
        Filter.atTop (nhds 0)

/-- **Tasaki Definition 4.19 (physical ground state).**  A translation-invariant ground state `ω` of
the antiferromagnetic Heisenberg model is a *physical ground state* when it is ergodic. -/
def IsPhysicalGroundState (S : InfiniteSpinSystem d A) (εGS : ℝ) (ω : WeakDual ℂ A) : Prop :=
  IsInfiniteVolumeGroundState S εGS ω ∧ IsErgodic S ω

/-- The **staggered sign** `ε_x = (−1)^{Σ_i x_i}` (`+1` on even sites, `−1` on odd), as a real
number; the Néel magnetization alternates with this sign. -/
def staggeredSign (x : Fin d → ℤ) : ℝ := if Even (∑ i, x i) then 1 else -1

/-- A vector `n : Fin 3 → ℝ` is a **unit vector** when `Σ_α (n α)² = 1`. -/
def IsUnitVector (n : Fin 3 → ℝ) : Prop := (∑ α, (n α) ^ 2) = 1

/-! ### Parity bridge to the graph-centric sublattices

The §4.3 quantum-side parity helpers `evenSite` / `staggeredSign` agree with the
graph-centric even/odd sublattices `Lattice.hypercubicEvenSublattice` /
`hypercubicOddSublattice` of the bipartite hypercubic lattice (Issue #4557). -/

/-- A site is **even** (`evenSite`) iff it lies in the graph-centric even
sublattice `ℤᵈ_even` (the A-sublattice of the bipartite hypercubic lattice). -/
theorem evenSite_iff_mem_hypercubicEvenSublattice (x : Fin d → ℤ) :
    evenSite x ↔ x ∈ LatticeSystem.Lattice.hypercubicEvenSublattice d := by
  simp only [evenSite, LatticeSystem.Lattice.hypercubicEvenSublattice, Set.mem_setOf_eq,
    Int.even_iff]

/-- A site lies in the graph-centric odd sublattice `ℤᵈ_odd` (the B-sublattice)
iff it is **not** an even site. -/
theorem mem_hypercubicOddSublattice_iff_not_evenSite (x : Fin d → ℤ) :
    x ∈ LatticeSystem.Lattice.hypercubicOddSublattice d ↔ ¬ evenSite x := by
  simp only [LatticeSystem.Lattice.hypercubicOddSublattice, Set.mem_setOf_eq, evenSite,
    Int.even_iff]

/-- The staggered sign is `+1` exactly on the even sublattice. -/
theorem staggeredSign_eq_one_iff_mem_hypercubicEvenSublattice (x : Fin d → ℤ) :
    staggeredSign x = 1 ↔ x ∈ LatticeSystem.Lattice.hypercubicEvenSublattice d := by
  rw [show (x ∈ LatticeSystem.Lattice.hypercubicEvenSublattice d) ↔ Even (∑ i, x i) from Iff.rfl]
  unfold staggeredSign
  by_cases h : Even (∑ i, x i) <;> norm_num [h]

/-- The staggered sign is `−1` exactly on the odd sublattice. -/
theorem staggeredSign_eq_neg_one_iff_mem_hypercubicOddSublattice (x : Fin d → ℤ) :
    staggeredSign x = -1 ↔ x ∈ LatticeSystem.Lattice.hypercubicOddSublattice d := by
  rw [show (x ∈ LatticeSystem.Lattice.hypercubicOddSublattice d) ↔ ¬ Even (∑ i, x i) from Iff.rfl]
  unfold staggeredSign
  by_cases h : Even (∑ i, x i) <;> norm_num [h]

/-- **`εGS` is the ground-state energy density of `S`** (an uninterpreted documented predicate): the
per-bond ground-state energy density `ε_GS = lim_L E_GS,L / |B_L|` (eq. (4.3.4)) of the
antiferromagnetic Heisenberg model `S`.  Kept uninterpreted so Theorem 4.20 asserts the existence of
ground states only for the genuine `(S, ε_GS)` data (and cannot be instantiated with an arbitrary
`εGS` unrelated to `S`, which would be inconsistent for degenerate systems). -/
axiom IsGroundStateEnergyDensity {d : ℕ} {A : Type*} [CStarAlgebra A] [NormedSpace ℂ A]
    [StarModule ℂ A] : InfiniteSpinSystem d A → ℝ → Prop

/-- **The model exhibits staggered long-range order with order parameter `m∗`** (an uninterpreted
documented predicate, the infinite-volume LRO assumption).  Tasaki's construction of the
symmetry-breaking ground states `ω_n` (Theorem 4.20) presumes the model has Néel long-range order
(`m∗ > 0`); in one dimension there is no such order (cf. Corollary 4.3), so this hypothesis is not
available there.  Kept uninterpreted so the existence of `ω_n` is genuinely conditional on
long-range
order, not trivially dischargeable. -/
axiom HasStaggeredLRO {d : ℕ} {A : Type*} [CStarAlgebra A] [NormedSpace ℂ A] [StarModule ℂ A] :
    InfiniteSpinSystem d A → ℝ → Prop

/-- **Tasaki Theorem 4.20 for `ω_0` (the symmetric infinite-volume ground state), AXIOM.**  The
infinite-volume state `ω_0` built as the `L↑∞` limit of the unique finite-volume ground-state
expectation `⟨Φ_GS|·|Φ_GS⟩` (eq. (4.3.7)) is a translation-invariant ground state with vanishing
single-site magnetization `ω_0(Ŝ_x^{(α)}) = 0` (eq. (4.3.9)): it exhibits long-range order but
**no**
spontaneous symmetry breaking.  The `L↑∞` limit's existence is assumed (Banach–Alaoglu, Theorem
A.24); recorded as a documented axiom asserting the limit state exists with the stated properties.
Conditional on `εGS` being the genuine ground-state energy density of `S` (`hε`), so it cannot be
applied with an arbitrary `εGS`. -/
axiom theorem_4_20_omega0 (S : InfiniteSpinSystem d A) (εGS : ℝ)
    (hε : IsGroundStateEnergyDensity S εGS) :
    ∃ ω0 : WeakDual ℂ A, IsInfiniteVolumeGroundState S εGS ω0 ∧
      ∀ (x : Fin d → ℤ) (α : Fin 3), ω0 (S.spin x α) = 0

/-- **Tasaki Theorem 4.20 for `ω_n` (the symmetry-breaking infinite-volume ground states), AXIOM.**
Assuming the model has staggered long-range order with order parameter `m∗ > 0` (`HasStaggeredLRO`),
for every unit direction `n ∈ ℝ³` the infinite-volume state `ω_n` built as the `L↑∞` limit of the
symmetry-breaking low-lying state expectation `⟨Ξ_n|·|Ξ_n⟩` (eq. (4.3.8)) is a translation-invariant
ground state with Néel magnetization `ω_n(Ŝ_x^{(α)}) = (−1)^x m∗ n_α` (eq. (4.3.10)): it exhibits
long-range order **and** full spontaneous symmetry breaking in the direction `n`.  Recorded as a
documented axiom; the `m∗` is tied to long-range order (not arbitrary), so `ω_n` exists only in the
ordered regime (vacuous in one dimension). -/
axiom theorem_4_20_omegaN (S : InfiniteSpinSystem d A) (εGS : ℝ)
    (hε : IsGroundStateEnergyDensity S εGS) (mStar : ℝ) (hm : 0 < mStar)
    (hLRO : HasStaggeredLRO S mStar) (n : Fin 3 → ℝ) (hn : IsUnitVector n) :
    ∃ ωn : WeakDual ℂ A, IsInfiniteVolumeGroundState S εGS ωn ∧
      ∀ (x : Fin d → ℤ) (α : Fin 3),
        ωn (S.spin x α) = ((staggeredSign x : ℝ) : ℂ) * (mStar : ℂ) * (n α : ℂ)

/-- **Tasaki Conjecture 4.21 (the symmetry-breaking ground states are physical), as a `Prop`
STATEMENT ONLY** (eq. after (4.3.10)).  This registers the *unproven* conjecture as a numbered,
searchable item; it is a `def … : Prop` and is **never asserted true** (no `axiom`/`theorem` derives
it — that would be unsound, the conjecture being open).

The statement: every symmetry-breaking infinite-volume ground state `ω` — a translation-invariant
ground state with the Néel magnetization `ω(Ŝ_x^{(α)}) = (−1)^x m∗ n_α` for some `m∗ > 0` and unit
direction `n` (the `ω_n` of Theorem 4.20) — is **ergodic**, hence a *physical* ground state
(Definition 4.19).  This conjecture motivates identifying the low-lying states `|Ξ_n⟩` as physical
"ground states".  Tasaki believes it likely valid but it is open; we record it without asserting
it. -/
def conjecture_4_21 (S : InfiniteSpinSystem d A) (εGS : ℝ) : Prop :=
  ∀ (mStar : ℝ), 0 < mStar → ∀ (n : Fin 3 → ℝ), IsUnitVector n →
    ∀ (ω : WeakDual ℂ A), IsInfiniteVolumeGroundState S εGS ω →
      (∀ (x : Fin d → ℤ) (α : Fin 3),
        ω (S.spin x α) = ((staggeredSign x : ℝ) : ℂ) * (mStar : ℂ) * (n α : ℂ)) →
      IsErgodic S ω

end InfiniteSpinSystem

end LatticeSystem.Quantum
