import LatticeSystem.Quantum.SpinS.AnisotropicEdgeStringOrder

/-!
# Tasaki §8.2.2: the Kennedy–Tasaki transformation

The picture of **hidden Z₂ × Z₂ symmetry breaking** in the Haldane phase is made precise by the
**Kennedy–Tasaki transformation**, the non-local unitary (eq. (8.2.5))

  `Û_KT = ∏_{u < v} exp(iπ Ŝ_u^{(3)} Ŝ_v^{(1)})`,

written in this concise form by Oshikawa.  This module builds `Û_KT` concretely and proves that it
is a self-adjoint involution.

No bridge to `NormedSpace.exp` is used or needed.  The two factors of
`exp(iπ Ŝ_u^{(3)} Ŝ_v^{(1)})` sit on *different* sites, so `A³ = A` holds for
`A = Ŝ_u^{(3)} Ŝ_v^{(1)}` and
the `S = 1` closed form of a `π` rotation gives `exp(iπ A) = 1 - 2 A²`, which is the definition of
`ktPairFactorS` below.  Substituting `(Ŝ^{(α)})² = (1 - u_α)/2` turns each factor into the
**half-turn control polynomial** `(1 + u_3^{(u)} + u_1^{(v)} - u_3^{(u)} u_1^{(v)}) / 2`, so the
whole construction lives inside the commuting algebra generated by the single-site half turns.  All
the properties Tasaki states on p. 241 — mutual commutativity of the factors, `Û_KT² = 1`, and
`Û_KT = Û_KT†` — follow from that observation.

Grouping the ordered product by its right index `v` is not cosmetic: for `Ŝ_x^{(α)}` the columns
`v < x` act trivially, the column `v = x` contributes exactly the left string `∏_{u < x} u_3^{(u)}`
(the axis-3 instance of the §8.1.2 prefix rotation `edgeStringPrefixRotationS`, reused here rather
than restated), and each column `v > x` contributes exactly one right-string factor `u_1^{(v)}`.
That is the mechanism of the transformation rules (8.2.12)–(8.2.14).

The relevant symmetry is **Z₂ × Z₂**: the three `π` rotations `Û_π^{(α)} = ∏_x exp(iπ Ŝ_x^{(α)})`
about the spin axes (any two generate the group).  A Hamiltonian is Z₂ × Z₂ invariant when
`(Û_π^{(α)})† Ĥ Û_π^{(α)} = Ĥ` for `α = 1, 2, 3`.  Each `Û_π^{(α)}` is the whole-chain instance of
the region half turn, again by the `S = 1` closed form and with no `exp` bridge.

Reference: Hal Tasaki, *Physics and Mathematics of Quantum Many-Body Systems* (1st ed., Springer,
2020), §8.2.2, eqs. (8.2.5)–(8.2.7) and the derivation on p. 244, pp. 241–244; §2.1,
eqs. (2.1.21), (2.1.23) and (2.1.25), pp. 17–18; T. Kennedy, H. Tasaki, Commun. Math. Phys. **147**,
431 (1992); M. Oshikawa, J. Phys.: Condens. Matter **4**, 7469 (1992); F. Pollmann, A. M. Turner,
E. Berg, M. Oshikawa, *Symmetry protection of topological phases in one-dimensional quantum spin
systems*, Phys. Rev. B **85**, 075125 (2012).
-/

namespace LatticeSystem.Quantum

open Matrix

variable {L : ℕ}

/-! ## The half-turn control polynomial -/

/-- The **half-turn control polynomial** `C(G, T) = (1 + G + T - G T) / 2`.

For commuting involutions `G` and `T` this is the "controlled `T`" operator `P₊(G) + P₋(G) T` with
`P_± = (1 ± G) / 2`: it acts as the identity on the `+1` eigenspace of `G` and as `T` on the `-1`
eigenspace.  Every factor of the Kennedy–Tasaki unitary has this shape, with `G` a single-site
axis-3 half turn and `T` a single-site axis-1 half turn. -/
noncomputable def halfTurnCtrlS (G T : ManyBodyOpS (Fin L) 2) : ManyBodyOpS (Fin L) 2 :=
  (2 : ℂ)⁻¹ • (1 + G + T - G * T)

/-- The **factored (controlled-gate) form** `C(G, T) = [(1 + G) + (1 - G) T] / 2`, which is the
shape all the algebra below is done in. -/
theorem halfTurnCtrlS_eq_factored (G T : ManyBodyOpS (Fin L) 2) :
    halfTurnCtrlS G T = (2 : ℂ)⁻¹ • ((1 + G) + (1 - G) * T) := by
  rw [halfTurnCtrlS]
  congr 1
  noncomm_ring

/-- A trivial control gives the identity: `C(1, T) = 1`. -/
theorem halfTurnCtrlS_one_left (T : ManyBodyOpS (Fin L) 2) :
    halfTurnCtrlS (1 : ManyBodyOpS (Fin L) 2) T = 1 := by
  rw [halfTurnCtrlS, one_mul,
    show (1 : ManyBodyOpS (Fin L) 2) + 1 + T - T = (2 : ℂ) • 1 by rw [two_smul]; noncomm_ring,
    smul_smul]
  norm_num

/-- The bare (undivided) composition identity behind `halfTurnCtrlS_mul`. -/
private theorem halfTurnCtrlS_mul_aux (G G' T : ManyBodyOpS (Fin L) 2)
    (hTG' : Commute T G') (hT : T * T = 1) :
    ((1 + G) + (1 - G) * T) * ((1 + G') + (1 - G') * T)
      = ((1 + G * G') + (1 - G * G') * T) + ((1 + G * G') + (1 - G * G') * T) := by
  have h1 : T * (1 + G') = (1 + G') * T := by
    rw [mul_add, add_mul, mul_one, one_mul, hTG'.eq]
  have h2 : T * ((1 - G') * T) = 1 - G' := by
    have hsub : T * (1 - G') = (1 - G') * T := by
      rw [mul_sub, sub_mul, mul_one, one_mul, hTG'.eq]
    rw [← mul_assoc, hsub, mul_assoc, hT, mul_one]
  calc ((1 + G) + (1 - G) * T) * ((1 + G') + (1 - G') * T)
      = (1 + G) * (1 + G') + (1 + G) * ((1 - G') * T)
        + (1 - G) * (T * (1 + G')) + (1 - G) * (T * ((1 - G') * T)) := by noncomm_ring
    _ = (1 + G) * (1 + G') + (1 + G) * ((1 - G') * T)
        + (1 - G) * ((1 + G') * T) + (1 - G) * (1 - G') := by rw [h1, h2]
    _ = ((1 + G * G') + (1 - G * G') * T) + ((1 + G * G') + (1 - G * G') * T) := by noncomm_ring

/-- **Composition law**: `C(G, T) C(G', T) = C(G G', T)` for a common target `T` that is an
involution commuting with `G'`.  Two controlled gates with the same target compose by multiplying
their controls. -/
theorem halfTurnCtrlS_mul {G G' T : ManyBodyOpS (Fin L) 2} (hTG' : Commute T G') (hT : T * T = 1) :
    halfTurnCtrlS G T * halfTurnCtrlS G' T = halfTurnCtrlS (G * G') T := by
  rw [halfTurnCtrlS_eq_factored, halfTurnCtrlS_eq_factored, halfTurnCtrlS_eq_factored,
    Matrix.smul_mul, Matrix.mul_smul, smul_smul, halfTurnCtrlS_mul_aux G G' T hTG' hT,
    ← two_smul ℂ, smul_smul]
  norm_num

/-- **Each control polynomial with an involutive control and target is an involution**:
`C(G, T)² = C(G², T) = C(1, T) = 1`. -/
theorem halfTurnCtrlS_mul_self {G T : ManyBodyOpS (Fin L) 2} (hTG : Commute T G)
    (hG : G * G = 1) (hT : T * T = 1) :
    halfTurnCtrlS G T * halfTurnCtrlS G T = 1 := by
  rw [halfTurnCtrlS_mul hTG hT, hG, halfTurnCtrlS_one_left]

/-- **The control polynomial is Hermitian** when its control and target are Hermitian and
commute. -/
theorem halfTurnCtrlS_isHermitian {G T : ManyBodyOpS (Fin L) 2} (hTG : Commute T G)
    (hG : G.IsHermitian) (hT : T.IsHermitian) : (halfTurnCtrlS G T).IsHermitian := by
  change Matrix.conjTranspose (halfTurnCtrlS G T) = halfTurnCtrlS G T
  rw [halfTurnCtrlS, Matrix.conjTranspose_smul, Matrix.conjTranspose_sub,
    Matrix.conjTranspose_add, Matrix.conjTranspose_add, Matrix.conjTranspose_one,
    Matrix.conjTranspose_mul, hG.eq, hT.eq, hTG.eq]
  simp

/-- **Anything commuting with the control and the target commutes with the control polynomial.** -/
theorem halfTurnCtrlS_commute {G T X : ManyBodyOpS (Fin L) 2} (hGX : Commute G X)
    (hTX : Commute T X) : Commute (halfTurnCtrlS G T) X := by
  have hGT : G * T * X = X * (G * T) := by
    rw [mul_assoc, hTX.eq, ← mul_assoc, hGX.eq, mul_assoc]
  have h : (1 + G + T - G * T) * X = X * (1 + G + T - G * T) := by
    rw [sub_mul, add_mul, add_mul, one_mul, mul_sub, mul_add, mul_add, mul_one, hGX.eq, hTX.eq,
      hGT]
  change halfTurnCtrlS G T * X = X * halfTurnCtrlS G T
  rw [halfTurnCtrlS, Matrix.smul_mul, h, Matrix.mul_smul]

/-- **Conjugation, trivial case**: an operator commuting with both control and target is fixed. -/
theorem halfTurnCtrlS_conj_of_commute {G T X : ManyBodyOpS (Fin L) 2} (hTG : Commute T G)
    (hG : G * G = 1) (hT : T * T = 1) (hGX : Commute G X) (hTX : Commute T X) :
    halfTurnCtrlS G T * X * halfTurnCtrlS G T = X := by
  rw [(halfTurnCtrlS_commute hGX hTX).eq, mul_assoc, halfTurnCtrlS_mul_self hTG hG hT, mul_one]

/-- **Conjugation, target-anticommuting case**: if `X` commutes with the control but is flipped by
the target, conjugation multiplies it by the control.  This is the column `v = x` of the
Kennedy–Tasaki product, which creates the left string of (8.2.13)–(8.2.14). -/
theorem halfTurnCtrlS_conj_of_target_anticomm {G T X : ManyBodyOpS (Fin L) 2} (hTG : Commute T G)
    (hG : G * G = 1) (hT : T * T = 1) (hGX : Commute G X) (hTX : T * X * T = -X) :
    halfTurnCtrlS G T * X * halfTurnCtrlS G T = X * G := by
  have hTX' : T * X = -(X * T) := by
    have h := congrArg (fun M => M * T) hTX
    simp only [neg_mul] at h
    rwa [mul_assoc, hT, mul_one] at h
  have hcomm1 : Commute (1 + G) X := (Commute.one_left X).add_left hGX
  have hcomm2 : Commute (1 - G) X := (Commute.one_left X).sub_left hGX
  have hGexp : G * ((1 + G) + (1 - G) * T) = (1 + G) - (1 - G) * T := by
    rw [show G * ((1 + G) + (1 - G) * T) = G + G * G + (G - G * G) * T by noncomm_ring, hG]
    noncomm_ring
  have hkey : ((1 + G) + (1 - G) * T) * X = X * (G * ((1 + G) + (1 - G) * T)) := by
    rw [hGexp, add_mul, mul_assoc, hTX', hcomm1.eq, mul_neg, ← mul_assoc, hcomm2.eq, mul_assoc]
    noncomm_ring
  have hkey2 : halfTurnCtrlS G T * X = X * (G * halfTurnCtrlS G T) := by
    rw [halfTurnCtrlS_eq_factored, Matrix.smul_mul, Matrix.mul_smul, Matrix.mul_smul, hkey]
  calc halfTurnCtrlS G T * X * halfTurnCtrlS G T
      = X * G * (halfTurnCtrlS G T * halfTurnCtrlS G T) := by rw [hkey2]; noncomm_ring
    _ = X * G := by rw [halfTurnCtrlS_mul_self hTG hG hT, mul_one]

/-- **Conjugation, control-anticommuting case**: if `X` is flipped by the control but commutes with
the target, conjugation multiplies it by the target.  This is a column `v > x` of the
Kennedy–Tasaki product, which contributes one right-string factor of (8.2.12)–(8.2.13). -/
theorem halfTurnCtrlS_conj_of_control_anticomm {G T X : ManyBodyOpS (Fin L) 2} (hTG : Commute T G)
    (hG : G * G = 1) (hT : T * T = 1) (hGX : G * X * G = -X) (hTX : Commute T X) :
    halfTurnCtrlS G T * X * halfTurnCtrlS G T = X * T := by
  have hGX' : G * X = -(X * G) := by
    have h := congrArg (fun M => M * G) hGX
    simp only [neg_mul] at h
    rwa [mul_assoc, hG, mul_one] at h
  have h1 : (1 + G) * X = X * (1 - G) := by
    rw [add_mul, one_mul, hGX', mul_sub, mul_one]
    noncomm_ring
  have h2 : (1 - G) * X = X * (1 + G) := by
    rw [sub_mul, one_mul, hGX', mul_add, mul_one]
    noncomm_ring
  have hTexp : T * ((1 + G) + (1 - G) * T) = (1 - G) + (1 + G) * T := by
    have hsub : T * ((1 - G) * T) = 1 - G := by
      have hc : T * (1 - G) = (1 - G) * T := by
        rw [mul_sub, sub_mul, mul_one, one_mul, hTG.eq]
      rw [← mul_assoc, hc, mul_assoc, hT, mul_one]
    have hadd : T * (1 + G) = (1 + G) * T := by
      rw [mul_add, add_mul, mul_one, one_mul, hTG.eq]
    rw [mul_add, hsub, hadd]
    noncomm_ring
  have hkey : ((1 + G) + (1 - G) * T) * X = X * (T * ((1 + G) + (1 - G) * T)) := by
    rw [hTexp, add_mul, mul_assoc, hTX.eq, ← mul_assoc, h1, h2, mul_assoc]
    noncomm_ring
  have hkey2 : halfTurnCtrlS G T * X = X * (T * halfTurnCtrlS G T) := by
    rw [halfTurnCtrlS_eq_factored, Matrix.smul_mul, Matrix.mul_smul, Matrix.mul_smul, hkey]
  calc halfTurnCtrlS G T * X * halfTurnCtrlS G T
      = X * T * (halfTurnCtrlS G T * halfTurnCtrlS G T) := by rw [hkey2]; noncomm_ring
    _ = X * T := by rw [halfTurnCtrlS_mul_self hTG hG hT, mul_one]

/-- **An ordered product of control polynomials with a common involutive target collapses to a
single one**, whose control is the ordered product of the controls. -/
private theorem halfTurnCtrlS_listProd {T : ManyBodyOpS (Fin L) 2} (hT : T * T = 1) :
    ∀ l : List (ManyBodyOpS (Fin L) 2), (∀ G ∈ l, Commute T G) →
      (l.map fun G => halfTurnCtrlS G T).prod = halfTurnCtrlS l.prod T := by
  intro l
  induction l with
  | nil => intro _; simp [halfTurnCtrlS_one_left]
  | cons a t ih =>
    intro hc
    have hTt : Commute T t.prod :=
      Commute.list_prod_right _ _ fun X hX => hc X (List.mem_cons_of_mem _ hX)
    rw [List.map_cons, List.prod_cons, ih fun X hX => hc X (List.mem_cons_of_mem _ hX),
      halfTurnCtrlS_mul hTt hT, List.prod_cons]

/-! ## The pair factors and the columns -/

/-- The **pair factor** `exp(iπ Ŝ_u^{(3)} Ŝ_v^{(1)}) = 1 - 2 (Ŝ_u^{(3)} Ŝ_v^{(1)})²` of the
Kennedy–Tasaki product (Tasaki (8.2.5), p. 241).  The closed form is valid because `A³ = A` for
`A = Ŝ_u^{(3)} Ŝ_v^{(1)}` at `S = 1` with `u ≠ v`; no `NormedSpace.exp` bridge is used. -/
noncomputable def ktPairFactorS (L : ℕ) (u v : Fin L) : ManyBodyOpS (Fin L) 2 :=
  1 - (2 : ℂ) • (spinSSiteComponentS 2 u * spinSSiteComponentS 0 v) ^ 2

/-- The `S = 1` square of an axis operator in terms of its half turn: `(Ŝ^{(α)})² = (1 - u_α)/2`. -/
private theorem spinOneAxisS_sq_eq (alpha : Fin 3) :
    spinOneAxisS alpha * spinOneAxisS alpha = (2 : ℂ)⁻¹ • (1 - spinOneHalfTurnS alpha) := by
  rw [spinOneHalfTurnS_eq_one_sub_two_smul_sq, pow_two, sub_sub_cancel, smul_smul]
  norm_num

/-- **The pair factor is a half-turn control polynomial**: substituting `(Ŝ^{(α)})² = (1 - u_α)/2`
into `1 - 2 (Ŝ_u^{(3)} Ŝ_v^{(1)})²` gives `(1 + u_3^{(u)} + u_1^{(v)} - u_3^{(u)} u_1^{(v)})/2`.
This is the identity that removes all exponentials from §8.2.2. -/
theorem ktPairFactorS_eq_halfTurnCtrlS (L : ℕ) {u v : Fin L} (huv : u ≠ v) :
    ktPairFactorS L u v
      = halfTurnCtrlS (onSiteS u (spinOneHalfTurnS 2)) (onSiteS v (spinOneHalfTurnS 0)) := by
  have hcomm : Commute (onSiteS v (spinOneAxisS 0) : ManyBodyOpS (Fin L) 2)
      (onSiteS u (spinOneAxisS 2)) := onSiteS_commute_of_ne huv.symm _ _
  have hsq : (spinSSiteComponentS 2 u * spinSSiteComponentS 0 v) ^ 2
      = ((2 : ℂ)⁻¹ • (1 - onSiteS u (spinOneHalfTurnS 2))) *
        ((2 : ℂ)⁻¹ • (1 - onSiteS v (spinOneHalfTurnS 0))) := by
    rw [pow_two, spinSSiteComponentS_eq_onSiteS, spinSSiteComponentS_eq_onSiteS,
      hcomm.mul_mul_mul_comm, onSiteS_mul_onSiteS_same, onSiteS_mul_onSiteS_same,
      spinOneAxisS_sq_eq, spinOneAxisS_sq_eq, onSiteS_smul, onSiteS_smul, onSiteS_sub,
      onSiteS_sub, onSiteS_one, onSiteS_one]
  have hprod : ((2 : ℂ)⁻¹ • (1 - onSiteS u (spinOneHalfTurnS 2))) *
        ((2 : ℂ)⁻¹ • (1 - onSiteS v (spinOneHalfTurnS 0)))
      = (4 : ℂ)⁻¹ • ((1 - onSiteS u (spinOneHalfTurnS 2)) *
          (1 - onSiteS v (spinOneHalfTurnS 0))) := by
    rw [Matrix.smul_mul, Matrix.mul_smul, smul_smul,
      show ((2 : ℂ)⁻¹ * (2 : ℂ)⁻¹) = (4 : ℂ)⁻¹ by norm_num]
  have hexpand : (1 - onSiteS u (spinOneHalfTurnS 2)) * (1 - onSiteS v (spinOneHalfTurnS 0))
      = 1 - onSiteS u (spinOneHalfTurnS 2) - onSiteS v (spinOneHalfTurnS 0)
        + onSiteS u (spinOneHalfTurnS 2) * onSiteS v (spinOneHalfTurnS 0) := by noncomm_ring
  rw [ktPairFactorS, hsq, hprod, hexpand, halfTurnCtrlS]
  module

/-- The **column** `Û_v = ∏_{u < v} exp(iπ Ŝ_u^{(3)} Ŝ_v^{(1)})` of the Kennedy–Tasaki product:
the factors of (8.2.5) grouped by their right index `v`. -/
noncomputable def ktColumnS (L : ℕ) (v : Fin L) : ManyBodyOpS (Fin L) 2 :=
  (List.ofFn fun u : Fin L => if u.val < v.val then ktPairFactorS L u v else 1).prod

/-- The column's target commutes with its control: the prefix rotation `∏_{u < v} u_3^{(u)}` does
not touch the site `v`. -/
theorem ktColumnTarget_commute_control (L : ℕ) (v : Fin L) :
    Commute (onSiteS v (spinOneHalfTurnS 0) : ManyBodyOpS (Fin L) 2)
      (edgeStringPrefixRotationS L 2 v.val) :=
  (edgeStringPrefixRotationS_commute_onSiteS_of_le L 2 v.val (le_refl v.val) _).symm

/-- **The column is a single control polynomial** whose control is the axis-3 prefix rotation
`∏_{u < v} u_3^{(u)}` and whose target is the axis-1 half turn at `v`.  This is where the `u < v`
product of (8.2.5) collapses; the left string of (8.2.13)–(8.2.14) is exactly this control. -/
theorem ktColumnS_eq_halfTurnCtrlS (L : ℕ) (v : Fin L) :
    ktColumnS L v
      = halfTurnCtrlS (edgeStringPrefixRotationS L 2 v.val)
          (onSiteS v (spinOneHalfTurnS 0)) := by
  have hfun : (fun u : Fin L => if u.val < v.val then ktPairFactorS L u v else 1)
      = fun u : Fin L =>
        halfTurnCtrlS (if u.val < v.val then onSiteS u (spinOneHalfTurnS 2) else 1)
          (onSiteS v (spinOneHalfTurnS 0)) := by
    funext u
    by_cases h : u.val < v.val
    · rw [if_pos h, if_pos h,
        ktPairFactorS_eq_halfTurnCtrlS L (fun huv : u = v => absurd (huv ▸ h) (lt_irrefl _))]
    · rw [if_neg h, if_neg h, halfTurnCtrlS_one_left]
  have hmap : (List.ofFn fun u : Fin L =>
        halfTurnCtrlS (if u.val < v.val then onSiteS u (spinOneHalfTurnS 2) else 1)
          (onSiteS v (spinOneHalfTurnS 0)))
      = (List.ofFn fun u : Fin L =>
          if u.val < v.val then onSiteS u (spinOneHalfTurnS 2) else 1).map
        fun G => halfTurnCtrlS G (onSiteS v (spinOneHalfTurnS 0)) := by
    rw [List.map_ofFn]
    rfl
  have hcomm : ∀ G ∈ List.ofFn fun u : Fin L =>
      if u.val < v.val then onSiteS u (spinOneHalfTurnS 2) else (1 : ManyBodyOpS (Fin L) 2),
      Commute (onSiteS v (spinOneHalfTurnS 0)) G := by
    intro G hG
    rw [List.ofFn_eq_map, List.mem_map] at hG
    obtain ⟨u, _, rfl⟩ := hG
    by_cases h : u.val < v.val
    · rw [if_pos h]
      exact onSiteS_commute_of_ne (fun hvu : v = u => absurd (hvu ▸ h) (lt_irrefl _)) _ _
    · rw [if_neg h]
      exact Commute.one_right _
  have hctrl : (List.ofFn fun u : Fin L =>
        if u.val < v.val then onSiteS u (spinOneHalfTurnS 2) else 1).prod
      = edgeStringPrefixRotationS L 2 v.val := by
    have hset : (fun y : Fin L =>
          if y ∈ Finset.univ.filter (fun z : Fin L => z.val < v.val) then
            onSiteS y (spinOneHalfTurnS 2) else 1)
        = fun u : Fin L => if u.val < v.val then onSiteS u (spinOneHalfTurnS 2) else 1 := by
      funext y
      simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    rw [edgeStringPrefixRotationS, halfTurnRegionS, hset]
  rw [ktColumnS, hfun, hmap,
    halfTurnCtrlS_listProd (onSiteS_spinOneHalfTurnS_mul_self L 0 v) _ hcomm, hctrl]

/-- **Each column is an involution** (Tasaki p. 241: every factor of (8.2.5) squares to the
identity). -/
theorem ktColumnS_mul_self (L : ℕ) (v : Fin L) : ktColumnS L v * ktColumnS L v = 1 := by
  rw [ktColumnS_eq_halfTurnCtrlS]
  exact halfTurnCtrlS_mul_self (ktColumnTarget_commute_control L v)
    (edgeStringPrefixRotationS_mul_self L 2 v.val) (onSiteS_spinOneHalfTurnS_mul_self L 0 v)

/-- **Each column is Hermitian.** -/
theorem ktColumnS_isHermitian (L : ℕ) (v : Fin L) : (ktColumnS L v).IsHermitian := by
  rw [ktColumnS_eq_halfTurnCtrlS]
  exact halfTurnCtrlS_isHermitian (ktColumnTarget_commute_control L v)
    (edgeStringPrefixRotationS_isHermitian L 2 v.val)
    (onSiteS_isHermitian v (spinOneHalfTurnS_isHermitian 0))

/-- Anything commuting with a column's control and target commutes with the column. -/
theorem ktColumnS_commute_of (L : ℕ) (v : Fin L) {X : ManyBodyOpS (Fin L) 2}
    (hG : Commute (edgeStringPrefixRotationS L 2 v.val) X)
    (hT : Commute (onSiteS v (spinOneHalfTurnS 0)) X) : Commute (ktColumnS L v) X := by
  rw [ktColumnS_eq_halfTurnCtrlS]
  exact halfTurnCtrlS_commute hG hT

/-- **Every column commutes with every region half turn**, since both are built from the mutually
commuting single-site half turns. -/
theorem ktColumnS_commute_halfTurnRegionS (L : ℕ) (v : Fin L) (alpha : Fin 3)
    (s : Finset (Fin L)) : Commute (ktColumnS L v) (halfTurnRegionS L alpha s) := by
  refine ktColumnS_commute_of L v ?_ ?_
  · rw [edgeStringPrefixRotationS]
    exact halfTurnRegionS_commute L 2 alpha _ s
  · rw [← halfTurnRegionS_singleton L 0 v]
    exact halfTurnRegionS_commute L 0 alpha _ s

/-- **The columns of (8.2.5) mutually commute** (Tasaki p. 241, proved on p. 244): the only
nontrivial case, a shared middle index, reduces to the commutation of two single-site half
turns. -/
theorem ktColumnS_commute (L : ℕ) (v w : Fin L) : Commute (ktColumnS L v) (ktColumnS L w) := by
  refine ktColumnS_commute_of L v ?_ ?_
  · rw [edgeStringPrefixRotationS]
    exact (ktColumnS_commute_halfTurnRegionS L w 2 _).symm
  · rw [← halfTurnRegionS_singleton L 0 v]
    exact (ktColumnS_commute_halfTurnRegionS L w 0 _).symm

/-! ## The Kennedy–Tasaki unitary -/

/-- The **Kennedy–Tasaki unitary** `Û_KT = ∏_{u < v} exp(iπ Ŝ_u^{(3)} Ŝ_v^{(1)})` (eq. (8.2.5),
p. 241), the non-local transformation turning hidden Z₂ × Z₂ symmetry breaking into manifest
symmetry breaking, written as the ordered product of its columns. -/
noncomputable def ktUnitaryS (L : ℕ) : ManyBodyOpS (Fin L) 2 :=
  (List.ofFn (ktColumnS L)).prod

/-- The columns, listed in index order, are pairwise commuting. -/
private theorem ktColumnS_list_pairwise (L : ℕ) :
    (List.ofFn (ktColumnS L)).Pairwise Commute := by
  rw [List.ofFn_eq_map, List.pairwise_map]
  exact (List.nodup_finRange L).imp fun {a b} _ => ktColumnS_commute L a b

/-- **`Û_KT² = 1`** (Tasaki (8.2.5) ff., p. 241): the commuting two-site factors each square to the
identity, so the Kennedy–Tasaki unitary is an involution. -/
theorem ktUnitaryS_sq (L : ℕ) : ktUnitaryS L * ktUnitaryS L = 1 := by
  refine listProd_mul_self_of_pairwise_commute _ (ktColumnS_list_pairwise L) ?_
  intro X hX
  rw [List.ofFn_eq_map, List.mem_map] at hX
  obtain ⟨v, _, rfl⟩ := hX
  exact ktColumnS_mul_self L v

/-- **`Û_KT = Û_KT†`**: the Kennedy–Tasaki unitary is self-adjoint (hence `Û_KT` and `Û_KT†` may be
used interchangeably, as Tasaki does from p. 241 on). -/
theorem ktUnitaryS_selfAdjoint (L : ℕ) :
    (ktUnitaryS L).conjTranspose = ktUnitaryS L := by
  refine Matrix.IsHermitian.eq (listProd_isHermitian_of_pairwise_commute _
    (ktColumnS_list_pairwise L) ?_)
  intro X hX
  rw [List.ofFn_eq_map, List.mem_map] at hX
  obtain ⟨v, _, rfl⟩ := hX
  exact ktColumnS_isHermitian L v

/-- **The Kennedy–Tasaki unitary commutes with every region half turn.**  Applied to the
whole-chain region this is Tasaki's statement (p. 250) that `Û_KT` commutes with each `Û_π^{(α)}`,
and it is also what makes the left and right strings pass through `Û_KT` unchanged. -/
theorem ktUnitaryS_commute_halfTurnRegionS (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L)) :
    Commute (ktUnitaryS L) (halfTurnRegionS L alpha s) := by
  refine Commute.list_prod_left _ _ ?_
  intro X hX
  rw [List.ofFn_eq_map, List.mem_map] at hX
  obtain ⟨v, _, rfl⟩ := hX
  exact ktColumnS_commute_halfTurnRegionS L v alpha s

/-! ## The `Z₂ × Z₂` `π` rotations -/

/-- The **`π` rotation** `Û_π^{(α)} = ∏_x exp(iπ Ŝ_x^{(α)})` about the spin axis `α : Fin 3`: the
whole-chain instance of the region half turn, using the `S = 1` closed form
`exp(iπ Ŝ^{(α)}) = 1 - 2 (Ŝ^{(α)})²` rather than an exponential.  Together the three generate the
Z₂ × Z₂ group. -/
noncomputable def piRotationS (L : ℕ) (alpha : Fin 3) : ManyBodyOpS (Fin L) 2 :=
  halfTurnRegionS L alpha Finset.univ

/-- **Z₂ × Z₂ invariance** of a Hamiltonian `H`: `(Û_π^{(α)})† H Û_π^{(α)} = H` for every spin axis
`α = 1, 2, 3`, i.e. `H` commutes with each of the three `π` rotations.  This is the *concrete*
`S = 1` condition, spelled out through `piRotationS`; the general-`N` opaque marker
`IsZ2Z2SymmetricS` (`LiebSchultzMattisDiscrete.lean`) is a deliberately different object and the
two are not to be merged. -/
def IsZ2Z2Invariant (H : ManyBodyOpS (Fin L) 2) : Prop :=
  ∀ α : Fin 3, (piRotationS L α).conjTranspose * H * piRotationS L α = H

/-- Each `π` rotation is an involution. -/
theorem piRotationS_mul_self (L : ℕ) (alpha : Fin 3) :
    piRotationS L alpha * piRotationS L alpha = 1 :=
  halfTurnRegionS_mul_self L alpha _

/-- Each `π` rotation is self-adjoint. -/
theorem piRotationS_isHermitian (L : ℕ) (alpha : Fin 3) : (piRotationS L alpha).IsHermitian :=
  halfTurnRegionS_isHermitian L alpha _

/-- **Z₂ × Z₂ invariance in conjugation form**: since each `π` rotation is a self-adjoint
involution, invariance says exactly `Û_π^{(α)} H Û_π^{(α)} = H`. -/
theorem isZ2Z2Invariant_iff (H : ManyBodyOpS (Fin L) 2) :
    IsZ2Z2Invariant H ↔ ∀ α : Fin 3, piRotationS L α * H * piRotationS L α = H := by
  have h : ∀ α : Fin 3, (piRotationS L α).conjTranspose = piRotationS L α :=
    fun α => (piRotationS_isHermitian L α).eq
  simp only [IsZ2Z2Invariant, h]

/-- **`Û_KT` commutes with every `π` rotation** (Tasaki p. 250, first paragraph).  This is why
the `Z₂ × Z₂` symmetry of the transformed Hamiltonian is not newly acquired but inherited. -/
theorem ktUnitaryS_commute_piRotationS (L : ℕ) (alpha : Fin 3) :
    Commute (ktUnitaryS L) (piRotationS L alpha) :=
  ktUnitaryS_commute_halfTurnRegionS L alpha _

/-! ## Boundary sanity -/

/-- **Verification viewpoint 2 (boundary sanity, `L = 0, 1`).** The pairwise product defining
`Û_KT` (eq. (8.2.5)) ranges over `u < v` in `Fin L`; with `L = 0` there are no sites at all and
with `L = 1` there is a single site but no pair `u < v`, so in both cases the product is empty and
`Û_KT` reduces to the identity. -/
theorem ktUnitaryS_boundary_sanity : ktUnitaryS 0 = 1 ∧ ktUnitaryS 1 = 1 := by
  refine ⟨by simp [ktUnitaryS], ?_⟩
  have h : ktColumnS 1 0 = 1 := by simp [ktColumnS]
  simp [ktUnitaryS, List.ofFn_succ, h]

end LatticeSystem.Quantum
