import LatticeSystem.Quantum.SpinS.ParityReachableMatrixPow
import LatticeSystem.Quantum.SpinS.ParityReachableSymm

/-!
# Parity-block reachability without parity-bond steps

Issue #412 -- Tasaki Section 2.5 Theorem 2.4.

This file introduces the parity-block reachability relation generated by the
transverse bond moves and single-ion moves, deliberately excluding
`ParityBondStepS`.  It is intended for the general spin-`S` `lambda = 1`
boundary, where the same-direction parity-bond coefficient vanishes but the
single-ion branch is strict when `D.re > 0`.

Reference: H. Tasaki, *Physics and Mathematics of Quantum Many-Body Systems*,
Springer 2020, Section 2.5 Theorem 2.4, pp. 43--44.
-/

namespace LatticeSystem.Quantum

open Matrix

variable {V : Type*} [Fintype V] [DecidableEq V] {N : ℕ}

/-- A parity-block move generated by transverse bonds and single-ion terms:
either a transverse raise/lower move or a single-ion `±2` move.  This excludes
`ParityBondStepS`. -/
def IonParityStepS (G : SimpleGraph V) (σ σ' : V → Fin (N + 1)) : Prop :=
  RaiseLowerStepS G σ σ' ∨ SingleIonStepS σ σ'

/-- Reflexive-transitive closure of `IonParityStepS`. -/
def IonParityReachableS (G : SimpleGraph V) :
    (V → Fin (N + 1)) → (V → Fin (N + 1)) → Prop :=
  Relation.ReflTransGen (IonParityStepS G)

omit [Fintype V] [DecidableEq V] in
/-- Reflexivity of ion-only parity reachability. -/
theorem IonParityReachableS.refl (G : SimpleGraph V) (σ : V → Fin (N + 1)) :
    IonParityReachableS G σ σ := Relation.ReflTransGen.refl

omit [Fintype V] [DecidableEq V] in
/-- A single ion-only parity step is ion-only reachable. -/
theorem IonParityReachableS.single {G : SimpleGraph V} {σ σ' : V → Fin (N + 1)}
    (h : IonParityStepS G σ σ') : IonParityReachableS G σ σ' :=
  Relation.ReflTransGen.single h

omit [Fintype V] [DecidableEq V] in
/-- Transitivity of ion-only parity reachability. -/
theorem IonParityReachableS.trans {G : SimpleGraph V} {σ σ' σ'' : V → Fin (N + 1)}
    (h₁ : IonParityReachableS G σ σ') (h₂ : IonParityReachableS G σ' σ'') :
    IonParityReachableS G σ σ'' := Relation.ReflTransGen.trans h₁ h₂

omit [Fintype V] [DecidableEq V] in
/-- A transverse hop is an ion-only parity-block move. -/
theorem IonParityReachableS.of_raiseLower {G : SimpleGraph V}
    {σ σ' : V → Fin (N + 1)}
    (h : RaiseLowerStepS G σ σ') : IonParityReachableS G σ σ' :=
  Relation.ReflTransGen.single (Or.inl h)

omit [Fintype V] [DecidableEq V] in
/-- A single-ion hop is an ion-only parity-block move. -/
theorem IonParityReachableS.of_singleIon {G : SimpleGraph V}
    {σ σ' : V → Fin (N + 1)}
    (h : SingleIonStepS σ σ') : IonParityReachableS G σ σ' :=
  Relation.ReflTransGen.single (Or.inr h)

omit [Fintype V] [DecidableEq V] in
/-- Lift transverse-only reachability to ion-only parity reachability. -/
theorem IonParityReachableS.of_raiseLowerReachable {G : SimpleGraph V}
    {σ σ' : V → Fin (N + 1)}
    (h : RaiseLowerReachableS G σ σ') : IonParityReachableS G σ σ' := by
  refine Relation.ReflTransGen.mono ?_ h
  intro _ _ hstep
  exact Or.inl hstep

omit [Fintype V] [DecidableEq V] in
/-- Symmetry of an ion-only parity step. -/
theorem ionParityStepS_symm {G : SimpleGraph V} {σ σ' : V → Fin (N + 1)}
    (h : IonParityStepS G σ σ') : IonParityStepS G σ' σ := by
  rcases h with hRL | hSI
  · exact Or.inl (RaiseLowerStepS.symm hRL)
  · exact Or.inr (singleIonStepS_symm hSI)

omit [Fintype V] [DecidableEq V] in
/-- Symmetry of ion-only parity reachability. -/
theorem IonParityReachableS.symm {G : SimpleGraph V} {σ σ' : V → Fin (N + 1)}
    (h : IonParityReachableS G σ σ') : IonParityReachableS G σ' σ :=
  Relation.ReflTransGen.symmetric (fun _ _ => ionParityStepS_symm) h

omit [Fintype V] [DecidableEq V] in
/-- An ion-only parity step is a full parity step. -/
theorem IonParityStepS.to_parityStepS {G : SimpleGraph V} {σ σ' : V → Fin (N + 1)}
    (h : IonParityStepS G σ σ') : ParityStepS G σ σ' := by
  rcases h with hRL | hSI
  · exact Or.inl hRL
  · exact Or.inr (Or.inr hSI)

omit [Fintype V] [DecidableEq V] in
/-- Ion-only parity reachability embeds into the existing full parity
reachability relation. -/
theorem IonParityReachableS.to_parityReachableS {G : SimpleGraph V}
    {σ σ' : V → Fin (N + 1)}
    (h : IonParityReachableS G σ σ') : ParityReachableS G σ σ' := by
  induction h with
  | refl => exact ParityReachableS.refl G σ
  | tail _h₁ h₂ ih =>
      exact ParityReachableS.trans ih (ParityReachableS.single h₂.to_parityStepS)

/-- Matrix-power positivity from ion-only parity reachability.  For a
non-negative matrix `B` strictly positive on every ion-only parity step,
`IonParityReachableS G σ σ'` gives some `k` with `0 < (B^k) σ' σ`. -/
theorem exists_matrixPow_apply_pos_of_ionParityReachableS
    {G : SimpleGraph V}
    {B : Matrix (V → Fin (N + 1)) (V → Fin (N + 1)) ℝ}
    (hB_nn : ∀ σ τ, 0 ≤ B σ τ)
    (hB_step : ∀ {σ τ : V → Fin (N + 1)}, IonParityStepS G σ τ → 0 < B τ σ)
    {σ σ' : V → Fin (N + 1)}
    (hreach : IonParityReachableS G σ σ') :
    ∃ k : ℕ, 0 < (B ^ k) σ' σ := by
  induction hreach with
  | refl => refine ⟨0, ?_⟩; simp [Matrix.one_apply_eq]
  | tail _h₁ h₂ ih =>
      obtain ⟨k, hpos⟩ := ih
      refine ⟨k + 1, ?_⟩
      rw [pow_succ', Matrix.mul_apply]
      apply Finset.sum_pos'
      · intro l _
        exact mul_nonneg (hB_nn _ _) (Matrix.pow_apply_nonneg hB_nn _ _ _)
      · exact ⟨_, Finset.mem_univ _, mul_pos (hB_step h₂) hpos⟩

end LatticeSystem.Quantum
