import LatticeSystem.Quantum.SpinS.ParityReachableMatrixPow
import LatticeSystem.Quantum.SpinS.ParityReachableSymm

/-!
# Parity-block reachability without single-ion steps

Issue #412 -- Tasaki Section 2.5 Theorem 2.4.

This file introduces the parity-block reachability relation generated only by
the bond moves of the axis-swapped Hamiltonian: transverse raise/lower moves
and bond-parity moves.  It deliberately excludes `SingleIonStepS`, so it can be
used at the `D >= 0` boundary where the single-ion strict-positive matrix entry
is unavailable.

Reference: H. Tasaki, *Physics and Mathematics of Quantum Many-Body Systems*,
Springer 2020, Section 2.5 Theorem 2.4, pp. 43--44.
-/

namespace LatticeSystem.Quantum

open Matrix

variable {V : Type*} [Fintype V] [DecidableEq V] {N : ℕ}

/-- A parity-block move generated by the bond terms only: either a transverse
raise/lower move or a bond-parity move.  This excludes `SingleIonStepS`. -/
def BondParityStepS (G : SimpleGraph V) (σ σ' : V → Fin (N + 1)) : Prop :=
  RaiseLowerStepS G σ σ' ∨ ParityBondStepS G σ σ'

/-- Reflexive-transitive closure of `BondParityStepS`. -/
def BondParityReachableS (G : SimpleGraph V) :
    (V → Fin (N + 1)) → (V → Fin (N + 1)) → Prop :=
  Relation.ReflTransGen (BondParityStepS G)

omit [Fintype V] [DecidableEq V] in
/-- Reflexivity of bond-only parity reachability. -/
theorem BondParityReachableS.refl (G : SimpleGraph V) (σ : V → Fin (N + 1)) :
    BondParityReachableS G σ σ := Relation.ReflTransGen.refl

omit [Fintype V] [DecidableEq V] in
/-- A single bond-only parity step is bond-only reachable. -/
theorem BondParityReachableS.single {G : SimpleGraph V} {σ σ' : V → Fin (N + 1)}
    (h : BondParityStepS G σ σ') : BondParityReachableS G σ σ' :=
  Relation.ReflTransGen.single h

omit [Fintype V] [DecidableEq V] in
/-- Transitivity of bond-only parity reachability. -/
theorem BondParityReachableS.trans {G : SimpleGraph V} {σ σ' σ'' : V → Fin (N + 1)}
    (h₁ : BondParityReachableS G σ σ') (h₂ : BondParityReachableS G σ' σ'') :
    BondParityReachableS G σ σ'' := Relation.ReflTransGen.trans h₁ h₂

omit [Fintype V] [DecidableEq V] in
/-- A transverse hop is a bond-only parity-block move. -/
theorem BondParityReachableS.of_raiseLower {G : SimpleGraph V}
    {σ σ' : V → Fin (N + 1)}
    (h : RaiseLowerStepS G σ σ') : BondParityReachableS G σ σ' :=
  Relation.ReflTransGen.single (Or.inl h)

omit [Fintype V] [DecidableEq V] in
/-- A bond-parity hop is a bond-only parity-block move. -/
theorem BondParityReachableS.of_bond {G : SimpleGraph V} {σ σ' : V → Fin (N + 1)}
    (h : ParityBondStepS G σ σ') : BondParityReachableS G σ σ' :=
  Relation.ReflTransGen.single (Or.inr h)

omit [Fintype V] [DecidableEq V] in
/-- Lift transverse-only reachability to bond-only parity reachability. -/
theorem BondParityReachableS.of_raiseLowerReachable {G : SimpleGraph V}
    {σ σ' : V → Fin (N + 1)}
    (h : RaiseLowerReachableS G σ σ') : BondParityReachableS G σ σ' := by
  refine Relation.ReflTransGen.mono ?_ h
  intro _ _ hstep
  exact Or.inl hstep

omit [Fintype V] [DecidableEq V] in
/-- Symmetry of a bond-only parity step. -/
theorem bondParityStepS_symm {G : SimpleGraph V} {σ σ' : V → Fin (N + 1)}
    (h : BondParityStepS G σ σ') : BondParityStepS G σ' σ := by
  rcases h with hRL | hPB
  · exact Or.inl (raiseLowerStepS_symm hRL)
  · exact Or.inr (parityBondStepS_symm hPB)

omit [Fintype V] [DecidableEq V] in
/-- Symmetry of bond-only parity reachability. -/
theorem BondParityReachableS.symm {G : SimpleGraph V} {σ σ' : V → Fin (N + 1)}
    (h : BondParityReachableS G σ σ') : BondParityReachableS G σ' σ :=
  Relation.ReflTransGen.symmetric (fun _ _ => bondParityStepS_symm) h

omit [Fintype V] [DecidableEq V] in
/-- A bond-only parity step is a full parity step. -/
theorem BondParityStepS.to_parityStepS {G : SimpleGraph V} {σ σ' : V → Fin (N + 1)}
    (h : BondParityStepS G σ σ') : ParityStepS G σ σ' := by
  rcases h with hRL | hPB
  · exact Or.inl hRL
  · exact Or.inr (Or.inl hPB)

omit [Fintype V] [DecidableEq V] in
/-- Bond-only parity reachability embeds into the existing full parity
reachability relation. -/
theorem BondParityReachableS.to_parityReachableS {G : SimpleGraph V}
    {σ σ' : V → Fin (N + 1)}
    (h : BondParityReachableS G σ σ') : ParityReachableS G σ σ' := by
  induction h with
  | refl => exact ParityReachableS.refl G σ
  | tail _h₁ h₂ ih =>
      exact ParityReachableS.trans ih (ParityReachableS.single h₂.to_parityStepS)

/-- Matrix-power positivity from bond-only parity reachability.  For a
non-negative matrix `B` strictly positive on every bond-only parity step,
`BondParityReachableS G σ σ'` gives some `k` with `0 < (B^k) σ' σ`. -/
theorem exists_matrixPow_apply_pos_of_bondParityReachableS
    {G : SimpleGraph V}
    {B : Matrix (V → Fin (N + 1)) (V → Fin (N + 1)) ℝ}
    (hB_nn : ∀ σ τ, 0 ≤ B σ τ)
    (hB_step : ∀ {σ τ : V → Fin (N + 1)}, BondParityStepS G σ τ → 0 < B τ σ)
    {σ σ' : V → Fin (N + 1)}
    (hreach : BondParityReachableS G σ σ') :
    ∃ k : ℕ, 0 < (B ^ k) σ' σ := by
  induction hreach with
  | refl => refine ⟨0, ?_⟩; simp [Matrix.one_apply_eq]
  | tail _h₁ h₂ ih =>
      obtain ⟨k, hpos⟩ := ih
      refine ⟨k + 1, ?_⟩
      rw [pow_succ', Matrix.mul_apply]
      apply Finset.sum_pos'
      · intro l _
        exact mul_nonneg (hB_nn _ _) (Matrix.pow_apply_nonneg hB_nn _ _ _)
      · exact ⟨_, Finset.mem_univ _, mul_pos (hB_step h₂) hpos⟩

end LatticeSystem.Quantum
