/-
Copyright (c) 2026 lattice-system contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import LatticeSystem.Quantum.SpinS.LagrangeFormula
import Mathlib.RingTheory.Adjoin.Basic
import Mathlib.RingTheory.Adjoin.Polynomial.Basic

/-!
# Diagonal projectors live in the algebra generated by `{Ŝ^{(α)}}`
(Tasaki §2.1 P1d''' β-27)

We promote the Lagrange-interpolation formula (β-25) to the
`Algebra.adjoin` level: each diagonal projector
`P_k = |k⟩⟨k|` is a member of the unital `ℂ`-subalgebra of
`Matrix (Fin (N+1)) (Fin (N+1)) ℂ` generated by the **Cartesian
spin operators** `{Ŝ^{(1)}, Ŝ^{(2)}, Ŝ^{(3)}}`:

  `P_k ∈ Algebra.adjoin ℂ {Ŝ^{(1)}, Ŝ^{(2)}, Ŝ^{(3)}}`.

A fortiori, `P_k ∈ Algebra.adjoin ℂ {Ŝ^{(3)}}` already (by β-25
alone), and we record both forms.

Tracked in #458.

Reference: Tasaki, *Physics and Mathematics of Quantum Many-Body
Systems*, §2.1.
-/

namespace LatticeSystem.Quantum

open Matrix Complex Polynomial

variable {N : ℕ}

/-- Each diagonal projector lies in `Algebra.adjoin ℂ {Ŝ^{(3)}}`. -/
theorem spinSDiagProj_mem_adjoin_spinSOp3 (N : ℕ) (k : Fin (N + 1)) :
    spinSDiagProj N k ∈
      Algebra.adjoin ℂ
        ({spinSOp3 N} :
          Set (Matrix (Fin (N + 1)) (Fin (N + 1)) ℂ)) := by
  rw [spinSDiagProj_eq_lagrange_aeval]
  rw [Algebra.adjoin_singleton_eq_range_aeval]
  exact ⟨_, rfl⟩

/-- Each diagonal projector lies in `Algebra.adjoin ℂ {Ŝ^{(1)}, Ŝ^{(2)}, Ŝ^{(3)}}`. -/
theorem spinSDiagProj_mem_adjoin (N : ℕ) (k : Fin (N + 1)) :
    spinSDiagProj N k ∈
      Algebra.adjoin ℂ
        ({spinSOp1 N, spinSOp2 N, spinSOp3 N} :
          Set (Matrix (Fin (N + 1)) (Fin (N + 1)) ℂ)) := by
  apply Algebra.adjoin_mono _ (spinSDiagProj_mem_adjoin_spinSOp3 N k)
  intro x hx
  rcases hx with rfl
  · exact Set.mem_insert_of_mem _ (Set.mem_insert_of_mem _ rfl)

end LatticeSystem.Quantum
