import Mathlib.LinearAlgebra.Eigenspace.Basic
import Mathlib.LinearAlgebra.Matrix.ToLin
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.LinearAlgebra.Dimension.FreeAndStrongRankCondition
import Mathlib.Analysis.Complex.Basic
import Mathlib.Data.Complex.BigOperators

/-!
# Real-to-complex eigenspace `finrank ≤ 1` bridge

Issue #3739 (Tasaki §2.5 Theorem 2.4, Mattis–Nishimori).

(f) bridge step 3: if the **real**-eigenspace of `M : Matrix n n ℝ` at real `ν` has
`finrank ≤ 1`, then the **complex**-eigenspace of the complexified matrix
`M.map ((↑) : ℝ → ℂ)` at `(ν : ℂ)` also has `finrank ≤ 1`.

Strategy: pick a generator `v_0` of the real eigenspace (via `finrank_le_one_iff`).  Cast `v_0`
to a complex eigenvector `v_c`.  For any complex eigenvector `w`, its real and imaginary parts
are real eigenvectors, hence real scalar multiples `α • v_0`, `β • v_0` of `v_0`.  Then
`w = (α + β I) • v_c`, so the complex eigenspace is generated by `v_c`.

Reference: H. Tasaki, *Physics and Mathematics of Quantum Many-Body Systems*, Springer 2020,
§2.5 Theorem 2.4, p. 43–44.
-/

namespace LatticeSystem.Quantum

open Module Matrix Complex

variable {n : Type*} [Fintype n] [DecidableEq n]

omit [DecidableEq n] in
/-- **Real part of a complex eigenvector is a real eigenvector**. -/
theorem matrix_eigenvec_re_of_complex {M : Matrix n n ℝ} {ν : ℝ} {v : n → ℂ}
    (hv : (M.map ((↑) : ℝ → ℂ)) *ᵥ v = (ν : ℂ) • v) :
    M *ᵥ (fun i => (v i).re) = ν • (fun i => (v i).re) := by
  funext i
  have hi := congrFun hv i
  apply_fun Complex.re at hi
  simp only [Matrix.mulVec, dotProduct, Matrix.map_apply, Pi.smul_apply, smul_eq_mul,
    Complex.re_sum, Complex.mul_re, Complex.ofReal_re, Complex.ofReal_im, zero_mul,
    sub_zero] at hi
  simp only [Matrix.mulVec, dotProduct, Pi.smul_apply, smul_eq_mul]
  exact hi

omit [DecidableEq n] in
/-- **Imag part of a complex eigenvector is a real eigenvector**. -/
theorem matrix_eigenvec_im_of_complex {M : Matrix n n ℝ} {ν : ℝ} {v : n → ℂ}
    (hv : (M.map ((↑) : ℝ → ℂ)) *ᵥ v = (ν : ℂ) • v) :
    M *ᵥ (fun i => (v i).im) = ν • (fun i => (v i).im) := by
  funext i
  have hi := congrFun hv i
  apply_fun Complex.im at hi
  simp only [Matrix.mulVec, dotProduct, Matrix.map_apply, Pi.smul_apply, smul_eq_mul,
    Complex.im_sum, Complex.mul_im, Complex.ofReal_re, Complex.ofReal_im, zero_mul,
    add_zero] at hi
  simp only [Matrix.mulVec, dotProduct, Pi.smul_apply, smul_eq_mul]
  exact hi

omit [DecidableEq n] in
/-- **Cast of real eigenvector to complex is a complex eigenvector**. -/
theorem matrix_eigenvec_map_ofReal {M : Matrix n n ℝ} {ν : ℝ} {v : n → ℝ}
    (hv : M *ᵥ v = ν • v) :
    (M.map ((↑) : ℝ → ℂ)) *ᵥ (fun i => ((v i) : ℂ)) =
      (ν : ℂ) • (fun i => ((v i) : ℂ)) := by
  funext i
  have hi := RingHom.map_mulVec (Complex.ofRealHom) M v i
  rw [hv] at hi
  simp only [Pi.smul_apply, smul_eq_mul, Function.comp_def,
    Complex.ofRealHom_eq_coe, Complex.ofReal_mul] at hi
  simp only [Pi.smul_apply, smul_eq_mul]
  exact hi.symm

/-- **Real-to-complex eigenspace `finrank ≤ 1` bridge**. -/
theorem matrix_complex_eigenspace_finrank_le_one_of_real
    (M : Matrix n n ℝ) (ν : ℝ)
    (h_le1 : Module.finrank ℝ (End.eigenspace (Matrix.toLin' M) ν) ≤ 1) :
    Module.finrank ℂ
        (End.eigenspace (Matrix.toLin' (M.map ((↑) : ℝ → ℂ))) (ν : ℂ)) ≤ 1 := by
  rw [finrank_le_one_iff] at h_le1
  obtain ⟨v_0, hv_0_span⟩ := h_le1
  have hv_0_eig : M *ᵥ v_0.1 = ν • v_0.1 := by
    have := End.mem_eigenspace_iff.mp v_0.2
    rw [Matrix.toLin'_apply] at this; exact this
  have hv_c_in : (fun i => ((v_0.1 i) : ℂ)) ∈
      End.eigenspace (Matrix.toLin' (M.map ((↑) : ℝ → ℂ))) (ν : ℂ) := by
    rw [End.mem_eigenspace_iff, Matrix.toLin'_apply]
    exact matrix_eigenvec_map_ofReal hv_0_eig
  rw [finrank_le_one_iff]
  refine ⟨⟨fun i => ((v_0.1 i) : ℂ), hv_c_in⟩, fun w => ?_⟩
  have hw_eig : (M.map ((↑) : ℝ → ℂ)) *ᵥ w.1 = (ν : ℂ) • w.1 := by
    have := End.mem_eigenspace_iff.mp w.2
    rw [Matrix.toLin'_apply] at this; exact this
  have hw_re_eig := matrix_eigenvec_re_of_complex hw_eig
  have hw_im_eig := matrix_eigenvec_im_of_complex hw_eig
  obtain ⟨α, hα⟩ := hv_0_span ⟨fun i => (w.1 i).re, by
    rw [End.mem_eigenspace_iff, Matrix.toLin'_apply]; exact hw_re_eig⟩
  obtain ⟨β, hβ⟩ := hv_0_span ⟨fun i => (w.1 i).im, by
    rw [End.mem_eigenspace_iff, Matrix.toLin'_apply]; exact hw_im_eig⟩
  have hα_fn : (α : ℝ) • v_0.1 = (fun i => (w.1 i).re) := congrArg Subtype.val hα
  have hβ_fn : (β : ℝ) • v_0.1 = (fun i => (w.1 i).im) := congrArg Subtype.val hβ
  refine ⟨(α : ℂ) + (β : ℂ) * Complex.I, ?_⟩
  apply Subtype.ext
  funext i
  change ((α : ℂ) + (β : ℂ) * Complex.I) * ((v_0.1 i) : ℂ) = w.1 i
  have hα_i : α * v_0.1 i = (w.1 i).re := by
    have := congrFun hα_fn i; simpa [Pi.smul_apply, smul_eq_mul] using this
  have hβ_i : β * v_0.1 i = (w.1 i).im := by
    have := congrFun hβ_fn i; simpa [Pi.smul_apply, smul_eq_mul] using this
  rw [show w.1 i = ((w.1 i).re : ℂ) + ((w.1 i).im : ℂ) * Complex.I from
      (Complex.re_add_im (w.1 i)).symm]
  rw [show ((w.1 i).re : ℂ) = ((α * v_0.1 i : ℝ) : ℂ) from by rw [hα_i]]
  rw [show ((w.1 i).im : ℂ) = ((β * v_0.1 i : ℝ) : ℂ) from by rw [hβ_i]]
  push_cast
  ring

end LatticeSystem.Quantum
