import LatticeSystem.Quantum.SpinS.SiteComponent
import LatticeSystem.Quantum.SpinS.SpinOneHalfTurn
import LatticeSystem.Math.MatrixAnalysis.HermitianSum

/-!
# Region half turns `R^{(α)}_s = ∏_{y ∈ s} u_α^{(y)}`

The `π` rotation about the spin axis `α` of an arbitrary set of sites `s ⊆ Λ_L`, written as an
ordered product of the commuting single-site half turns `u_α` of `SpinOneHalfTurn.lean`.

Three regions are used by the spin-one chain arguments and all three are instances of the single
definition below, so the algebraic identities (involutivity, self-adjointness, commutation with
operators outside the region, half-turn conjugation of operators inside it) are proved once:

* the **prefix** `{y | y < m}` — the string factor of Tasaki's (8.1.8) order operator;
* the **suffix** `{v | x < v}` — the right string generated by the Kennedy–Tasaki rules
  (8.2.12)–(8.2.13);
* the **whole chain** — the `π` rotation `Û_π^{(α)}` generating the `Z₂ × Z₂` symmetry.

The module also collects the generic ordered-product facts (conjugation by an involution is
multiplicative and distributes over a product; an ordered product of pairwise commuting involutions
is an involution, of pairwise commuting Hermitians is Hermitian), which are used both here and by
the Kennedy–Tasaki construction.  Ordered products are used throughout because matrices form no
`CommMonoid`, so `Finset.prod` is unavailable.

Reference: Hal Tasaki, *Physics and Mathematics of Quantum Many-Body Systems* (1st ed., Springer,
2020), §2.1, eqs. (2.1.21) and (2.1.23), pp. 17–18; §8.1.2, eq. (8.1.8), p. 236; §8.2.2,
eqs. (8.2.12)–(8.2.14), p. 243.
-/

namespace LatticeSystem.Quantum

open Matrix

variable {L : ℕ}

/-! ## Generic facts about ordered products -/

/-- **Conjugation by an involution is multiplicative**: `U (X Y) U = (U X U)(U Y U)` when
`U² = 1`. -/
theorem conj_mul_of_mul_self {U : ManyBodyOpS (Fin L) 2} (hU : U * U = 1)
    (X Y : ManyBodyOpS (Fin L) 2) :
    U * (X * Y) * U = (U * X * U) * (U * Y * U) := by
  rw [show (U * X * U) * (U * Y * U) = U * X * (U * U) * (Y * U) by noncomm_ring, hU]
  noncomm_ring

/-- **Conjugation by an involution distributes over an ordered product.** -/
theorem conj_listProd {U : ManyBodyOpS (Fin L) 2} (hU : U * U = 1)
    (l : List (ManyBodyOpS (Fin L) 2)) :
    U * l.prod * U = (l.map fun X => U * X * U).prod := by
  induction l with
  | nil => simpa using hU
  | cons a t ih =>
    rw [List.prod_cons, List.map_cons, List.prod_cons, ← ih, ← conj_mul_of_mul_self hU]

/-- **An ordered product of pairwise commuting involutions is an involution.** -/
theorem listProd_mul_self_of_pairwise_commute :
    ∀ l : List (ManyBodyOpS (Fin L) 2), l.Pairwise Commute → (∀ X ∈ l, X * X = 1) →
      l.prod * l.prod = 1 := by
  intro l
  induction l with
  | nil => intro _ _; simp
  | cons a t ih =>
    intro hp hinv
    rw [List.pairwise_cons] at hp
    have hc : Commute a t.prod := Commute.list_prod_right _ _ hp.1
    rw [List.prod_cons, hc.symm.mul_mul_mul_comm, hinv a (List.mem_cons_self ..),
      ih hp.2 fun X hX => hinv X (List.mem_cons_of_mem _ hX), mul_one]

/-- **An ordered product of pairwise commuting Hermitian operators is Hermitian.** -/
theorem listProd_isHermitian_of_pairwise_commute :
    ∀ l : List (ManyBodyOpS (Fin L) 2), l.Pairwise Commute → (∀ X ∈ l, X.IsHermitian) →
      l.prod.IsHermitian := by
  intro l
  induction l with
  | nil => intro _ _; simp
  | cons a t ih =>
    intro hp hH
    rw [List.pairwise_cons] at hp
    have hc : Commute a t.prod := Commute.list_prod_right _ _ hp.1
    rw [List.prod_cons]
    exact Matrix.IsHermitian.mul_of_commute (hH a (List.mem_cons_self ..))
      (ih hp.2 fun X hX => hH X (List.mem_cons_of_mem _ hX)) hc

/-! ## Single-site consequences of the half-turn conjugation law -/

/-- **The single-site half turns commute**: `u_α u_β = u_β u_α` (the integer-spin commutation of
two `π` rotations, Tasaki (2.1.25), p. 18).  Immediate from the conjugation stability
`u_α u_β u_α = u_β` and `u_α² = 1`. -/
theorem spinOneHalfTurnS_commute (alpha beta : Fin 3) :
    Commute (spinOneHalfTurnS alpha) (spinOneHalfTurnS beta) := by
  have h : spinOneHalfTurnS alpha * spinOneHalfTurnS beta * spinOneHalfTurnS alpha
      * spinOneHalfTurnS alpha = spinOneHalfTurnS beta * spinOneHalfTurnS alpha :=
    congrArg (fun M => M * spinOneHalfTurnS alpha)
      (spinOneHalfTurnS_conj_spinOneHalfTurnS alpha beta)
  rw [mul_assoc (spinOneHalfTurnS alpha * spinOneHalfTurnS beta), spinOneHalfTurnS_mul_self,
    mul_one] at h
  exact h

/-- **The half turn flips its own axis operator by a sign**: `Ŝ^{(α)} u_α = -Ŝ^{(α)}`, since
`u_α = 1 - 2 (Ŝ^{(α)})²` and `(Ŝ^{(α)})³ = Ŝ^{(α)}` at `S = 1`.  This is the identity
`exp(iπ Ŝ^{(α)}) Ŝ^{(α)} = -Ŝ^{(α)}` that produces the residual sign of Tasaki (8.2.15),
p. 243. -/
theorem spinOneAxisS_mul_spinOneHalfTurnS (alpha : Fin 3) :
    spinOneAxisS alpha * spinOneHalfTurnS alpha = -spinOneAxisS alpha := by
  fin_cases alpha
  · change spinOneAxisS 0 * spinOnePiRot1 = -spinOneAxisS 0
    have h1 : spinOneAxisS 0 = (1 / 2 : ℂ) • (spinSOpPlus 2 + spinSOpMinus 2) := rfl
    rw [h1]
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Matrix.mul_apply, Fin.sum_univ_three, spinOnePiRot1, spinSOpPlus, spinSOpMinus]
  · change spinOneAxisS 1 * spinOnePiRot2 = -spinOneAxisS 1
    have h2 : spinOneAxisS 1 = (1 / (2 * Complex.I) : ℂ) • (spinSOpPlus 2 - spinSOpMinus 2) := rfl
    rw [h2]
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Matrix.mul_apply, Fin.sum_univ_three, spinOnePiRot2, spinSOpPlus, spinSOpMinus]
  · change spinOneAxisS 2 * spinOnePiRot3 = -spinOneAxisS 2
    have h3 : spinOneAxisS 2 = spinSOp3 2 := rfl
    rw [h3]
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Matrix.mul_apply, Fin.sum_univ_three, spinOnePiRot3, spinSOp3]

/-- The many-body site component is the site embedding of the single-site axis operator. -/
theorem spinSSiteComponentS_eq_onSiteS (alpha : Fin 3) (x : Fin L) :
    spinSSiteComponentS alpha x = onSiteS x (spinOneAxisS alpha) := by
  fin_cases alpha <;> rfl

/-! ## The region half turn -/

/-- The **region half turn** `R^{(α)}_s = ∏_{y ∈ s} u_α^{(y)}`, the `π` rotation about axis `α`
of the sub-chain `s`, written as an ordered product of commuting single-site half turns.  The
product uses `List.ofFn ... |>.prod` because matrices form no `CommMonoid`. -/
noncomputable def halfTurnRegionS (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L)) :
    ManyBodyOpS (Fin L) 2 :=
  (List.ofFn fun y : Fin L => if y ∈ s then onSiteS y (spinOneHalfTurnS alpha) else 1).prod

/-- The site-`y` factor of `R^{(α)}_s`: the half turn `u_α` inside the region, the identity
outside it. -/
private noncomputable def halfTurnRegionFactorS (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L))
    (y : Fin L) : Matrix (Fin 3) (Fin 3) ℂ :=
  if y ∈ s then spinOneHalfTurnS alpha else 1

/-- Each region factor is an involution. -/
private theorem halfTurnRegionFactorS_mul_self (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L))
    (y : Fin L) :
    halfTurnRegionFactorS L alpha s y * halfTurnRegionFactorS L alpha s y = 1 := by
  rw [halfTurnRegionFactorS]
  split
  · exact spinOneHalfTurnS_mul_self alpha
  · exact one_mul 1

/-- Each region factor is Hermitian. -/
private theorem halfTurnRegionFactorS_isHermitian (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L))
    (y : Fin L) : (halfTurnRegionFactorS L alpha s y).IsHermitian := by
  rw [halfTurnRegionFactorS]
  split
  · exact spinOneHalfTurnS_isHermitian alpha
  · exact Matrix.isHermitian_one

/-- The region half turn as a product over `List.finRange`, with the factor selector exposed. -/
private theorem halfTurnRegionS_eq_map (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L)) :
    halfTurnRegionS L alpha s
      = ((List.finRange L).map fun y => onSiteS y (halfTurnRegionFactorS L alpha s y)).prod := by
  have hfun : (fun y : Fin L => if y ∈ s then onSiteS y (spinOneHalfTurnS alpha) else 1)
      = fun y : Fin L => onSiteS y (halfTurnRegionFactorS L alpha s y) := by
    funext y
    rw [halfTurnRegionFactorS]
    split
    · rfl
    · exact (onSiteS_one y).symm
  rw [halfTurnRegionS, hfun, List.ofFn_eq_map]

/-- Site embeddings at distinct sites commute, so a list of them indexed by distinct sites is
pairwise commuting. -/
private theorem onSiteS_map_pairwise (f : Fin L → Matrix (Fin 3) (Fin 3) ℂ)
    {l : List (Fin L)} (hl : l.Nodup) :
    ((l.map fun y => onSiteS y (f y) : List (ManyBodyOpS (Fin L) 2))).Pairwise Commute := by
  rw [List.pairwise_map]
  exact hl.imp fun {a b} hab => onSiteS_commute_of_ne hab _ _

/-- Splitting the region half turn off its site-`w` factor. -/
private theorem halfTurnRegionS_split (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L)) (w : Fin L) :
    halfTurnRegionS L alpha s
      = onSiteS w (halfTurnRegionFactorS L alpha s w) *
        ((((List.finRange L).erase w).map fun y =>
          onSiteS y (halfTurnRegionFactorS L alpha s y)).prod) := by
  rw [halfTurnRegionS_eq_map]
  have hperm := (List.perm_cons_erase (List.mem_finRange w)).map
    (fun y : Fin L => onSiteS y (halfTurnRegionFactorS L alpha s y))
  rw [hperm.prod_eq' (onSiteS_map_pairwise _ (List.nodup_finRange L))]
  simp

/-- The complement of the site-`w` factor commutes with every operator supported at `w`. -/
private theorem halfTurnRegionErased_commute (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L))
    (w : Fin L) (A : Matrix (Fin 3) (Fin 3) ℂ) :
    Commute ((((List.finRange L).erase w).map fun y =>
      onSiteS y (halfTurnRegionFactorS L alpha s y)).prod) (onSiteS w A) := by
  refine Commute.list_prod_left _ _ ?_
  intro z hz
  rw [List.mem_map] at hz
  obtain ⟨y, hy, rfl⟩ := hz
  refine onSiteS_commute_of_ne ?_ _ _
  intro hyw
  subst hyw
  exact (List.nodup_finRange L).not_mem_erase hy

/-! ## Algebraic properties of the region half turn -/

/-- **The region half turn is an involution**: `R² = 1`, since each `u_α` is. -/
theorem halfTurnRegionS_mul_self (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L)) :
    halfTurnRegionS L alpha s * halfTurnRegionS L alpha s = 1 := by
  rw [halfTurnRegionS_eq_map]
  refine listProd_mul_self_of_pairwise_commute _
    (onSiteS_map_pairwise _ (List.nodup_finRange L)) ?_
  intro X hX
  rw [List.mem_map] at hX
  obtain ⟨y, _, rfl⟩ := hX
  rw [onSiteS_mul_onSiteS_same, halfTurnRegionFactorS_mul_self, onSiteS_one]

/-- **The region half turn is self-adjoint**, hence unitary. -/
theorem halfTurnRegionS_isHermitian (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L)) :
    (halfTurnRegionS L alpha s).IsHermitian := by
  rw [halfTurnRegionS_eq_map]
  refine listProd_isHermitian_of_pairwise_commute _
    (onSiteS_map_pairwise _ (List.nodup_finRange L)) ?_
  intro X hX
  rw [List.mem_map] at hX
  obtain ⟨y, _, rfl⟩ := hX
  exact onSiteS_isHermitian y (halfTurnRegionFactorS_isHermitian L alpha s y)

/-- The region half turn is unitary: `RᴴR = 1`. -/
theorem halfTurnRegionS_conjTranspose_mul_self (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L)) :
    Matrix.conjTranspose (halfTurnRegionS L alpha s) * halfTurnRegionS L alpha s = 1 := by
  rw [(halfTurnRegionS_isHermitian L alpha s).eq]
  exact halfTurnRegionS_mul_self L alpha s

/-- **Sites outside the region are untouched**: `R^{(α)}_s` commutes with any operator supported
at a site `w ∉ s`. -/
theorem halfTurnRegionS_commute_onSiteS_of_not_mem (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L))
    {w : Fin L} (h : w ∉ s) (A : Matrix (Fin 3) (Fin 3) ℂ) :
    Commute (halfTurnRegionS L alpha s) (onSiteS w A) := by
  rw [halfTurnRegionS_split L alpha s w]
  have hfac : halfTurnRegionFactorS L alpha s w = 1 := if_neg h
  rw [hfac, onSiteS_one, one_mul]
  exact halfTurnRegionErased_commute L alpha s w A

/-- **Sites inside the region are conjugated by the half turn**: for `w ∈ s`,
`R^{(α)}_s A_w R^{(α)}_s = (u_α A u_α)_w`. -/
theorem halfTurnRegionS_conj_onSiteS_of_mem (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L))
    {w : Fin L} (h : w ∈ s) (A : Matrix (Fin 3) (Fin 3) ℂ) :
    halfTurnRegionS L alpha s * onSiteS w A * halfTurnRegionS L alpha s
      = onSiteS w (spinOneHalfTurnS alpha * A * spinOneHalfTurnS alpha) := by
  set Q := ((((List.finRange L).erase w).map fun y =>
    onSiteS y (halfTurnRegionFactorS L alpha s y)).prod) with hQdef
  have hsplit : halfTurnRegionS L alpha s = onSiteS w (spinOneHalfTurnS alpha) * Q := by
    rw [hQdef, halfTurnRegionS_split L alpha s w, halfTurnRegionFactorS, if_pos h]
  have hpast : halfTurnRegionS L alpha s * onSiteS w A
      = onSiteS w (spinOneHalfTurnS alpha * A * spinOneHalfTurnS alpha) *
        halfTurnRegionS L alpha s := by
    rw [hsplit]
    calc onSiteS w (spinOneHalfTurnS alpha) * Q * onSiteS w A
        = onSiteS w (spinOneHalfTurnS alpha) * (Q * onSiteS w A) := by noncomm_ring
      _ = onSiteS w (spinOneHalfTurnS alpha) * (onSiteS w A * Q) :=
          by rw [(halfTurnRegionErased_commute L alpha s w A).eq]
      _ = onSiteS w (spinOneHalfTurnS alpha * A) * Q := by
          rw [← mul_assoc, onSiteS_mul_onSiteS_same]
      _ = onSiteS w (spinOneHalfTurnS alpha * A * spinOneHalfTurnS alpha) *
            (onSiteS w (spinOneHalfTurnS alpha) * Q) := by
          rw [← mul_assoc, onSiteS_mul_onSiteS_same, mul_assoc, mul_assoc,
            spinOneHalfTurnS_mul_self alpha, mul_one]
  rw [hpast, mul_assoc, halfTurnRegionS_mul_self, mul_one]

/-- **Two region half turns commute**, for arbitrary axes and arbitrary regions: single-site half
turns at the same site commute with each other, and site embeddings at distinct sites always
commute. -/
theorem halfTurnRegionS_commute (L : ℕ) (alpha beta : Fin 3) (s t : Finset (Fin L)) :
    Commute (halfTurnRegionS L alpha s) (halfTurnRegionS L beta t) := by
  rw [halfTurnRegionS_eq_map, halfTurnRegionS_eq_map]
  refine Commute.list_prod_left _ _ ?_
  intro z hz
  rw [List.mem_map] at hz
  obtain ⟨y, _, rfl⟩ := hz
  refine Commute.list_prod_right _ _ ?_
  intro v hv
  rw [List.mem_map] at hv
  obtain ⟨w, _, rfl⟩ := hv
  by_cases hyw : y = w
  · subst hyw
    have hfac : halfTurnRegionFactorS L alpha s y * halfTurnRegionFactorS L beta t y
        = halfTurnRegionFactorS L beta t y * halfTurnRegionFactorS L alpha s y := by
      unfold halfTurnRegionFactorS
      split <;> split <;> simp [(spinOneHalfTurnS_commute alpha beta).eq]
    change onSiteS y (halfTurnRegionFactorS L alpha s y) *
        onSiteS y (halfTurnRegionFactorS L beta t y)
      = onSiteS y (halfTurnRegionFactorS L beta t y) *
        onSiteS y (halfTurnRegionFactorS L alpha s y)
    rw [onSiteS_mul_onSiteS_same, onSiteS_mul_onSiteS_same, hfac]
  · exact onSiteS_commute_of_ne hyw _ _

/-- **The region half turn commutes with its own axis component at every site**: inside the region
because `u_α` commutes with `Ŝ^{(α)}`, outside because the supports are disjoint. -/
theorem halfTurnRegionS_commute_component (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L))
    (x : Fin L) : Commute (halfTurnRegionS L alpha s) (spinSSiteComponentS alpha x) := by
  rw [spinSSiteComponentS_eq_onSiteS]
  by_cases h : x ∈ s
  · have hconj := halfTurnRegionS_conj_onSiteS_of_mem L alpha s h (spinOneAxisS alpha)
    rw [spinOneHalfTurnS_conj_spinOneAxisS, if_pos rfl, one_smul] at hconj
    have hstep := congrArg (fun M => M * halfTurnRegionS L alpha s) hconj
    simp only [mul_assoc, halfTurnRegionS_mul_self, mul_one] at hstep
    exact hstep
  · exact halfTurnRegionS_commute_onSiteS_of_not_mem L alpha s h _

/-- The empty region carries the identity. -/
theorem halfTurnRegionS_empty (L : ℕ) (alpha : Fin 3) :
    halfTurnRegionS L alpha (∅ : Finset (Fin L)) = 1 := by
  rw [halfTurnRegionS]
  simp

/-- **Adjoining a site to the region multiplies in one more half turn**: for `a ∉ s`,
`R^{(α)}_{insert a s} = u_α^{(a)} R^{(α)}_s`.  This is what accumulates the right string of
Tasaki (8.2.12)–(8.2.13) one column at a time. -/
theorem halfTurnRegionS_insert (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L)) {a : Fin L}
    (ha : a ∉ s) :
    halfTurnRegionS L alpha (insert a s)
      = onSiteS a (spinOneHalfTurnS alpha) * halfTurnRegionS L alpha s := by
  have herase : (((List.finRange L).erase a).map fun y =>
        onSiteS y (halfTurnRegionFactorS L alpha (insert a s) y)).prod
      = (((List.finRange L).erase a).map fun y =>
        onSiteS y (halfTurnRegionFactorS L alpha s y)).prod := by
    congr 1
    refine List.map_congr_left ?_
    intro y hy
    have hya : y ≠ a := fun h => (List.nodup_finRange L).not_mem_erase (h ▸ hy)
    have : halfTurnRegionFactorS L alpha (insert a s) y = halfTurnRegionFactorS L alpha s y := by
      unfold halfTurnRegionFactorS
      simp only [Finset.mem_insert, hya, false_or]
    rw [this]
  rw [halfTurnRegionS_split L alpha (insert a s) a, halfTurnRegionS_split L alpha s a, herase,
    halfTurnRegionFactorS, halfTurnRegionFactorS, if_pos (Finset.mem_insert_self a s), if_neg ha,
    onSiteS_one, one_mul]

/-- A single-site half turn is an involution, as the site embedding of an involution. -/
theorem onSiteS_spinOneHalfTurnS_mul_self (L : ℕ) (alpha : Fin 3) (a : Fin L) :
    (onSiteS a (spinOneHalfTurnS alpha) : ManyBodyOpS (Fin L) 2) *
      onSiteS a (spinOneHalfTurnS alpha) = 1 := by
  rw [onSiteS_mul_onSiteS_same, spinOneHalfTurnS_mul_self, onSiteS_one]

/-- A one-site region carries the single-site half turn, so single-site half turns are themselves
region half turns and inherit all the region commutation lemmas. -/
theorem halfTurnRegionS_singleton (L : ℕ) (alpha : Fin 3) (a : Fin L) :
    halfTurnRegionS L alpha ({a} : Finset (Fin L)) = onSiteS a (spinOneHalfTurnS alpha) := by
  rw [show ({a} : Finset (Fin L)) = insert a (∅ : Finset (Fin L)) by simp,
    halfTurnRegionS_insert L alpha ∅ (by simp), halfTurnRegionS_empty, mul_one]

/-- **The region half turn is invariant under any global half turn**: if the involution `U` acts
site-wise by conjugation with a single-site involution `V` that fixes `u_α`, then `U R U = R`.
This is the many-body lift of `spinOneHalfTurnS_conj_spinOneHalfTurnS`. -/
theorem halfTurnRegionS_conj (L : ℕ) (alpha : Fin 3) (s : Finset (Fin L))
    (U : ManyBodyOpS (Fin L) 2) (V : Matrix (Fin 3) (Fin 3) ℂ)
    (hU : U * U = 1) (hV : V * V = 1)
    (hVhalf : V * spinOneHalfTurnS alpha * V = spinOneHalfTurnS alpha)
    (hconj : ∀ (z : Fin L) (A : Matrix (Fin 3) (Fin 3) ℂ),
      U * onSiteS z A * U = onSiteS z (V * A * V)) :
    U * halfTurnRegionS L alpha s * U = halfTurnRegionS L alpha s := by
  rw [halfTurnRegionS_eq_map, conj_listProd hU, List.map_map]
  congr 1
  apply List.map_congr_left
  intro y _
  simp only [Function.comp_apply]
  rw [hconj]
  congr 1
  rw [halfTurnRegionFactorS]
  split
  · exact hVhalf
  · rw [mul_one]; exact hV

end LatticeSystem.Quantum
