import LatticeSystem.Quantum.SpinS.SpinThreeHalfBondProjection.Internal.VBS

/-!
# The local spin-three-half AKLT bond projection

This module exposes the concrete two-site maximal-spin projector for the
spin-three-half AKLT interaction and its explicit nine-dimensional VBS kernel.
-/

namespace LatticeSystem.Quantum

open scoped ComplexOrder

open SpinThreeHalfBondProjection.Internal

/-- The local spin-3/2 VBS vector with two unpaired virtual spin-halves at
each endpoint, indexed by their down-spin counts `a` and `b`.

The first basis term comes from `|up,down>` on the selected virtual singlet
and the second from `-|down,up>`.  The binomial square roots are the
normalized symmetric-spin coefficients at the two endpoints. -/
noncomputable def spinThreeHalfVBSBondVec
    (a b : Fin 3) : (Fin 2 → Fin 4) → ℂ :=
  fun σ =>
    let singletOuterWeight : ℂ :=
      (Real.sqrt 2 : ℂ)⁻¹ *
        (Real.sqrt (Nat.choose 2 a.val) : ℂ) *
        (Real.sqrt (Nat.choose 2 b.val) : ℂ)
    let upDownSiteWeight : ℂ :=
      ((Real.sqrt (Nat.choose 3 a.val) : ℂ) *
        (Real.sqrt (Nat.choose 3 (b.val + 1)) : ℂ))⁻¹
    let downUpSiteWeight : ℂ :=
      ((Real.sqrt (Nat.choose 3 (a.val + 1)) : ℂ) *
        (Real.sqrt (Nat.choose 3 b.val) : ℂ))⁻¹
    singletOuterWeight *
      (upDownSiteWeight *
          (if σ = ![Fin.castSucc a, Fin.succ b] then 1 else 0) -
        downUpSiteWeight *
          (if σ = ![Fin.succ a, Fin.castSucc b] then 1 else 0))

/-- The nine-dimensional candidate kernel generated by one virtual singlet
and two unpaired virtual spin-halves at each endpoint. -/
noncomputable def spinThreeHalfVBSBondSubspace :
    Submodule ℂ ((Fin 2 → Fin 4) → ℂ) :=
  Submodule.span ℂ
    (Set.range fun p : Fin 3 × Fin 3 =>
      spinThreeHalfVBSBondVec p.1 p.2)

/-- The concrete local projector `P₃` onto total bond spin three, obtained
from the existing Lagrange-Casimir maximal-spin projector at `N = 3`. -/
noncomputable def spinThreeHalfBondMaxProjection :
    Matrix (Fin 2 → Fin 4) (Fin 2 → Fin 4) ℂ :=
  bondMaxSpinProjectionS (0 : Fin 2) 1 3

/-- The public bond projector equals the certified frozen maximal-spin table. -/
private theorem spinThreeHalfBondMaxProjection_eq_table :
    spinThreeHalfBondMaxProjection = spinThreeHalfMaxSpinTable := by
  simpa only [spinThreeHalfBondMaxProjection] using
    bondMaxSpinProjection_eq_table

/-- The nine explicit local VBS bond generators are linearly independent. -/
theorem spinThreeHalfVBSBondVec_linearIndependent :
    LinearIndependent ℂ
      (fun p : Fin 3 × Fin 3 =>
        spinThreeHalfVBSBondVec p.1 p.2) := by
  simpa only [spinThreeHalfVBSBondVec, rawVBSBondVec] using
    rawVBSBondVec_linearIndependent

/-- Every explicit local VBS bond generator is annihilated by `P₃`. -/
theorem spinThreeHalfVBSBondVec_annihilated (a b : Fin 3) :
    spinThreeHalfBondMaxProjection.mulVec
      (spinThreeHalfVBSBondVec a b) = 0 := by
  rw [spinThreeHalfBondMaxProjection_eq_table]
  simpa only [spinThreeHalfVBSBondVec, rawVBSBondVec] using
    maxSpinTable_mulVec_rawVBSBondVec a b

/-- The concrete local maximal-spin projector `P₃` has rank seven. -/
theorem bondMaxSpinProjectionS_three_local_rank :
    Matrix.rank spinThreeHalfBondMaxProjection = 7 := by
  rw [spinThreeHalfBondMaxProjection_eq_table]
  exact spinThreeHalfMaxSpinTable_rank

/-- The kernel of the concrete local maximal-spin projector has dimension
nine. -/
theorem finrank_spinThreeHalfBondLocal_ker :
    Module.finrank ℂ
      (LinearMap.ker
        (Matrix.mulVecLin spinThreeHalfBondMaxProjection)) = 9 := by
  rw [spinThreeHalfBondMaxProjection_eq_table]
  exact finrank_spinThreeHalfMaxSpinTable_ker

/-- The kernel of local `P₃` is exactly the span of the nine VBS bond
generators. -/
theorem spinThreeHalfBondLocal_ker_eq_vbsBondSubspace :
    LinearMap.ker
        (Matrix.mulVecLin spinThreeHalfBondMaxProjection) =
      spinThreeHalfVBSBondSubspace := by
  rw [spinThreeHalfBondMaxProjection_eq_table]
  simpa only [spinThreeHalfVBSBondSubspace, rawVBSBondSubspace,
    spinThreeHalfVBSBondVec, rawVBSBondVec] using
    maxSpinTable_ker_eq_rawVBSBondSubspace

/-- The concrete local maximal-spin projector `P₃` is Hermitian. -/
theorem bondMaxSpinProjectionS_three_local_isHermitian :
    spinThreeHalfBondMaxProjection.IsHermitian := by
  rw [spinThreeHalfBondMaxProjection_eq_table]
  exact spinThreeHalfMaxSpinTable_isHermitian

/-- The concrete local maximal-spin projector `P₃` is idempotent. -/
theorem bondMaxSpinProjectionS_three_local_idempotent :
    spinThreeHalfBondMaxProjection * spinThreeHalfBondMaxProjection =
      spinThreeHalfBondMaxProjection := by
  rw [spinThreeHalfBondMaxProjection_eq_table]
  exact spinThreeHalfMaxSpinTable_idempotent

/-- The concrete local maximal-spin projector `P₃` has nonnegative
quadratic form on every two-site spin-3/2 vector. -/
theorem bondMaxSpinProjectionS_three_local_posSemidef :
    spinThreeHalfBondMaxProjection.PosSemidef := by
  have key :
      Matrix.conjTranspose spinThreeHalfBondMaxProjection *
          spinThreeHalfBondMaxProjection =
        spinThreeHalfBondMaxProjection := by
    rw [bondMaxSpinProjectionS_three_local_isHermitian.eq,
      bondMaxSpinProjectionS_three_local_idempotent]
  exact key ▸ Matrix.posSemidef_conjTranspose_mul_self
    spinThreeHalfBondMaxProjection

end LatticeSystem.Quantum
