import LatticeSystem.Fermion.JordanWigner.String
import LatticeSystem.Fermion.JordanWigner.StringBasisVecAction
import LatticeSystem.Fermion.JordanWigner.AnnihilationCreationBasisVec
import LatticeSystem.Fermion.JordanWigner.VacuumCreationBasisVec
import LatticeSystem.Fermion.JordanWigner.HopBasisVec
import LatticeSystem.Fermion.JordanWigner.Operators
import LatticeSystem.Fermion.JordanWigner.CAR
import LatticeSystem.Fermion.JordanWigner.CAR.CrossSiteOfNe
import LatticeSystem.Fermion.JordanWigner.Number
import LatticeSystem.Fermion.JordanWigner.NumberAnticommutators
import LatticeSystem.Fermion.JordanWigner.NumberPow
import LatticeSystem.Fermion.JordanWigner.CDaggerCCommutator
import LatticeSystem.Fermion.JordanWigner.CDaggerCIdentity
import LatticeSystem.Fermion.JordanWigner.CDaggerCProjection
import LatticeSystem.Fermion.JordanWigner.CDaggerCHermitian
import LatticeSystem.Fermion.JordanWigner.ProjectionsOrthogonal
import LatticeSystem.Fermion.JordanWigner.ProjectionsCommute
import LatticeSystem.Fermion.JordanWigner.AnnihilationNumberIdentities
import LatticeSystem.Fermion.JordanWigner.CreationNumberIdentities
import LatticeSystem.Fermion.JordanWigner.PartialIsometry
import LatticeSystem.Fermion.JordanWigner.HoleProjectionsCommute
import LatticeSystem.Fermion.JordanWigner.HoleProjectionCommuteLadder
import LatticeSystem.Fermion.JordanWigner.HoleProjectionCommuteNumber
import LatticeSystem.Fermion.JordanWigner.CDaggerCLadderZero
import LatticeSystem.Fermion.JordanWigner.Hubbard
import LatticeSystem.Fermion.JordanWigner.Hubbard.Charges
import LatticeSystem.Fermion.JordanWigner.Hubbard.Graph
import LatticeSystem.Fermion.JordanWigner.Hubbard.SpinSymmetryAux
import LatticeSystem.Fermion.JordanWigner.Hubbard.SpinSymmetry
import LatticeSystem.Fermion.JordanWigner.Hubbard.AllUpState
import LatticeSystem.Fermion.JordanWigner.Hubbard.AllDownState
import LatticeSystem.Fermion.JordanWigner.Hubbard.AllDownStateTotalNumber
import LatticeSystem.Fermion.JordanWigner.Hubbard.SpinTotHermitian
import LatticeSystem.Fermion.JordanWigner.Hubbard.SaturatedFerromagnetism
import LatticeSystem.Fermion.JordanWigner.Hubbard.HardcoreSubspace
import LatticeSystem.Fermion.JordanWigner.Hubbard.HardcoreProjection
import LatticeSystem.Fermion.JordanWigner.Hubbard.HardcoreBasis
import LatticeSystem.Fermion.JordanWigner.Hubbard.HardcoreSpan
import LatticeSystem.Fermion.JordanWigner.Hubbard.HopConfig
import LatticeSystem.Fermion.JordanWigner.Hubbard.HopAction
import LatticeSystem.Fermion.JordanWigner.Hubbard.HopMatrixElement
import LatticeSystem.Fermion.JordanWigner.Hubbard.EffectiveHamiltonian
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiBasis
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiHopAction
import LatticeSystem.Fermion.JordanWigner.Hubbard.HopSignBetween
import LatticeSystem.Fermion.JordanWigner.Hubbard.EffectiveHamiltonianMatrix
import LatticeSystem.Fermion.JordanWigner.Hubbard.EffectiveHamiltonianSpinSymmetry
import LatticeSystem.Fermion.JordanWigner.Hubbard.WeakNagaoka
import LatticeSystem.Fermion.JordanWigner.Hubbard.WeakNagaokaTheorem
import LatticeSystem.Fermion.JordanWigner.Hubbard.WeakNagaokaGroundState
import LatticeSystem.Fermion.JordanWigner.Hubbard.WeakNagaokaGlobalMin
import LatticeSystem.Fermion.JordanWigner.Hubbard.NagaokaMagnetizationSector
import LatticeSystem.Fermion.JordanWigner.Hubbard.NagaokaPerronFrobenius
import LatticeSystem.Fermion.JordanWigner.Hubbard.NagaokaConnectivity
import LatticeSystem.Fermion.JordanWigner.Hubbard.NagaokaBondGraph
import LatticeSystem.Fermion.JordanWigner.Hubbard.NagaokaConnectivityClassification
import LatticeSystem.Fermion.JordanWigner.Hubbard.NagaokaStateQuiver
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandModel
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandBasis
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandModeCreation
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandModeMonomial
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandBetaGram
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandDualAnnihilation
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandModeReorder
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandOccBasis
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandPeel
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandUniqueness
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandCAR
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandGroundState
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandZeroEnergy
import LatticeSystem.Fermion.JordanWigner.Hubbard.SpinLoweringTowerGeneral
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandHighestWeight
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandNonvanishing
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandMultiplet
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandEnergyTower
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandPosSemidef
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandFrustrationFree
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandNumberConservation
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandSubspaces
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandAlphaFockKernel
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandTheorem11_11
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandClassification
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandWeightStructure
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandWeightSupport
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandSiteAnnihilation
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandSiteModeCAR
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandSitePeel
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandModePeel
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandDoubleOcc
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandSwapCoeff
import LatticeSystem.Fermion.JordanWigner.Hubbard.MielkeHamiltonian
import LatticeSystem.Fermion.JordanWigner.Hubbard.MielkeTheorems
import LatticeSystem.Fermion.JordanWigner.Hubbard.MielkeIncidenceMatrix
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBand
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandOperators
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandGroundAnnihilation
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandModeMonomial
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandOccBasis
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandEigenbasis
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandSpanning
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandFilling
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandMuTransport
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandSpinConfig
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandSpinRep
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandSpinConfigRep
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandSignPropagation
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandSlaterReorder
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandCanonicalCoord
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandTwoHoleCollapse
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandConnectivity
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandMultiplet
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandDisconnected
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandProjectionBridge
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandProjectionBlock
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralFlatBandTheorem1115
import LatticeSystem.Fermion.JordanWigner.Hubbard.GeneralBasisHN
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveReflection
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveCoeffAction
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBlockOrder
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveHopAction
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBlockKinetic
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBlockCoeff
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBlockCoeffDown
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveFockUp
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveFockDown
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBlockKineticMatrix
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveInterleave
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractivePermutation
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveConjHop
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveJwCocycle
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveCocycleOperator
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveKineticConj
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveCoeffBridge
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBrRelation
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveEnergyTrace
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractivePermConj
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveKineticHermitian
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveKineticReal
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveInterleavedEnergy
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveInteractionEnergy
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveCoeffNormSq
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveFullEnergy
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveInteractionTrace
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveHermitianCoeff
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveSRPRearrangement
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveHermitianAbs
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveInteractionIneq
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveEnergyMonotone
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveKineticW
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveInteractionW
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractivePHConjDiag
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveEnergyReconcile
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveGammaCoords
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveGammaReflection
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveKineticIntertwiner
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveInteractionIntertwiner
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveHamiltonianCommute
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveGammaAntilinear
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveHermitianGround
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveNormFoundation
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveHamiltonianHermitian
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractivePosSemidefGround
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveGroundLyapunov
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveSectorSupport
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveKineticHopEntry
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveKineticEntry
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveSectorConnectivity
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveSectorGround
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBalancedSectorGround
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveSectorVariational
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveThetaSector
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBalancedThetaSector
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBalancedPosSemidefGround
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBalancedPosDefCompress
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveOverlapPositive
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveBalancedUniqueness
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveSU2Invariance
import LatticeSystem.Fermion.JordanWigner.Hubbard.FermionTotalSpinCasimirCharges
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveTotalSpinEigenstate
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveSingletGround
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveFullSectorSU2Algebra
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveFullSectorEnergy
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveFullSectorUnique
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractive
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveTheorem102Witness
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveTheorem102
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractivePairTransferMatrix
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractivePairCorrelationTrace
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebAttractiveTheorem103
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebRepulsive
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebRepulsiveShibaTransform
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebRepulsiveShibaUnitary
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebRepulsiveShibaInteraction
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebRepulsiveShibaKinetic
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebRepulsiveShibaConjugation
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebRepulsiveShibaSector
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebRepulsiveBalancedGround
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebRepulsiveShibaSpinOp
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebRepulsiveCorrelation
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebFerrimagnetism
import LatticeSystem.Fermion.JordanWigner.Hubbard.BipartiteSpectrum
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebShenQiu
import LatticeSystem.Fermion.JordanWigner.Hubbard.LiebKuboKishi
import LatticeSystem.Fermion.JordanWigner.Hubbard.SectorMinEnergy
import LatticeSystem.Fermion.JordanWigner.Hubbard.NonsingularHubbardModel
import LatticeSystem.Fermion.JordanWigner.Hubbard.NonsingularLocalStability
import LatticeSystem.Fermion.JordanWigner.Hubbard.WannierExampleModel
import LatticeSystem.Fermion.JordanWigner.Hubbard.TranslationOperator
import LatticeSystem.Fermion.JordanWigner.Hubbard.FermionicTranslation
import LatticeSystem.Fermion.JordanWigner.Hubbard.SpinWaveExcitation
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiNonsingularFerro
import LatticeSystem.Fermion.JordanWigner.Hubbard.NonsingularLocalHamiltonian
import LatticeSystem.Fermion.JordanWigner.Hubbard.NonsingularFrustrationFree
import LatticeSystem.Fermion.JordanWigner.Hubbard.NonsingularFrustrationFreePos
import LatticeSystem.Fermion.JordanWigner.Hubbard.NonsingularFerromagnetism
import LatticeSystem.Fermion.JordanWigner.Hubbard.FermionSiteSpin
import LatticeSystem.Fermion.JordanWigner.Hubbard.GroundSubspaceAtFilling
import LatticeSystem.Fermion.JordanWigner.Hubbard.HubbardFerromagnetismStructure
import LatticeSystem.Fermion.JordanWigner.Hubbard.HubbardImpossibilityLowU
import LatticeSystem.Fermion.JordanWigner.Hubbard.HubbardImpossibilityLowDensity
import LatticeSystem.Fermion.JordanWigner.Hubbard.TasakiFlatBandBasisLemma
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJModel
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSpinSymmetry
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSpinSymmetryRaising
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHermitian
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorReduction
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorBasis
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorSpin
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorNumber
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorHop
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorHopConfig
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorHopAction
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorHopNN
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorHopBackward
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorHopBackwardWrap
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJOccupationCount
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorHopWrap
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJEffMatrix
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorExchange
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJKineticSector
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJKineticMatrixElement
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJExchangeMatrixElement
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJDiagonalMatrixElement
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJOffDiagonal
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJKineticNonneg
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJKineticSummand
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJExchangeNonneg
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJExchangeBondSum
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorMatrix
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJStepRelation
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJStepMatrixEntry
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJAdjacentSwap
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSwapReachableBasics
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSwapReachable
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorShifted
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorIrreducible
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorGroundState
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJExpansion
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJCompleteness
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJNumberCommute
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHardcorePreserve
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJOperatorLift
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJEigenvectorLift
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundEnergy
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundEnergyReverse
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJFillingBasis
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJFillingCompress
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJFillingSpinCompress
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJFillingCompressSpinAlgebra
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJFillingRayleighBridge
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJFillingEigenLift
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJFillingSpinZDiag
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundEnergyGe
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundSpinHalfFinrank
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSectorRaise
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJRaisingTower
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJRaisingTermination
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHighestWeight
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJExpansionSpinEigen
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJTotalRaiseAction
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJRaiseCoeffSum
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJFillingCoeffSum
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJRaisePositivityStep
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJRaiseHardcore
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJRaisePositivity
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJMaximalSpinGroundState
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundDegeneracyLower
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJLadderInjective
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundWeightFinrank
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundWeightFinrankRaise
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundWeightOne
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundWeightDirectSum
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundWeightReindex
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJGroundDegeneracyUpper
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJProposition1124
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingKinetic
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingExchange
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJAllUpSpinDot
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJAllUpGround
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJSingletAnnihilation
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJCrossSiteSpinCommute
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJExchangeBondPSD
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJExchangeBondHalf
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJExchangePSD
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingReduction
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJAllUpProperties
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingGroundEnergy
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingDegeneracyLower
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingBondAction
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingBondGround
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingAmplitude
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingUpCount
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingDegeneracyUpper
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJHalfFillingMaximalSpin
import LatticeSystem.Fermion.JordanWigner.Hubbard.TJMaximalSpinUnified
import LatticeSystem.Fermion.JordanWigner.Hubbard.SpinfulVectorOperator
import LatticeSystem.Fermion.JordanWigner.Hubbard.MetallicFerroModel
import LatticeSystem.Fermion.JordanWigner.Hubbard.TanakaTasakiModel
import LatticeSystem.Fermion.JordanWigner.Hubbard.DoubleOccupancyProjection
import LatticeSystem.Fermion.JordanWigner.Hubbard.DoubleOccupancyCommute
import LatticeSystem.Fermion.JordanWigner.Hubbard.SpinfulNumberHermitian
import LatticeSystem.Fermion.JordanWigner.Hubbard.SitePartitionIdentity
import LatticeSystem.Fermion.JordanWigner.Hubbard.SiteProjectionsIdempotent
import LatticeSystem.Fermion.JordanWigner.Hubbard.SiteProjectionsDoublyEmpty
import LatticeSystem.Fermion.JordanWigner.Hubbard.SiteProjectionsHermitian
import LatticeSystem.Fermion.JordanWigner.Hubbard.SiteProjectionsUpDown
import LatticeSystem.Fermion.JordanWigner.Hubbard.SiteProjectionsEmptySingle
import LatticeSystem.Fermion.JordanWigner.Hubbard.SiteProjectionsSingleDoubly
import LatticeSystem.Fermion.JordanWigner.Hubbard.SiteProjectionsSpinResolved
import LatticeSystem.Fermion.JordanWigner.Hubbard.SiteProjectionsCommute
import LatticeSystem.Fermion.JordanWigner.Hubbard.SiteProjectionsPow
import LatticeSystem.Fermion.JordanWigner.Hubbard.EmptyProjectionCommute
import LatticeSystem.Fermion.JordanWigner.Hubbard.SingleProjectionsCommute
import LatticeSystem.Fermion.JordanWigner.Hubbard.UpDownProjectionCommute
import LatticeSystem.Fermion.JordanWigner.Hubbard.RemainingProjectionCommutes
import LatticeSystem.Fermion.JordanWigner.CPlusCDaggerSq
import LatticeSystem.Fermion.JordanWigner.CMinusCDaggerSq
import LatticeSystem.Fermion.JordanWigner.CPlusMinusCDaggerPauli
import LatticeSystem.Fermion.JordanWigner.OneSubTwoNumberSq
import LatticeSystem.Fermion.JordanWigner.CPlusCDaggerAnticomm
import LatticeSystem.Fermion.JordanWigner.CMinusCDaggerAnticomm
import LatticeSystem.Fermion.JordanWigner.NumberCommutePauliOfNe

set_option linter.unusedSectionVars false
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/-!
# Multi-mode fermion via Jordan–Wigner mapping

**Façade module** re-exporting the full Jordan–Wigner machinery.
Following the refactor plan v4 §3.1 (Phase 2 PR 10–14), this file
is a thin re-import of the sub-files under
`LatticeSystem/Fermion/JordanWigner/` (originally five core files;
further extended with single-mode-mirror and Hubbard algebra lemmas
during the 2026-05-04 autonomous fermion expansion).

The sub-modules group into the following families (see each file's own
doc comment for details, and the consolidated per-file overview table at
`docs/jordan-wigner-overview.md`):

* JW string + multi-mode operators: `String`, `Operators`, `CAR`,
  `Number`, `FockProduct`, and the number / commutator / projection
  lemma files (`NumberAnticommutators` … `CDaggerCLadderZero`).
* Pauli-analog algebra: `CPlusCDaggerSq`, `CMinusCDaggerSq`,
  `CPlusMinusCDaggerPauli`, `OneSubTwoNumberSq`, the anticommutators, and
  `NumberCommutePauliOfNe`.
* Hubbard core (`Hubbard`, `Hubbard/Charges`, `Hubbard/Graph`), spin
  symmetry (`Hubbard/SpinSymmetry*`, `SpinChargeCommutation`), spinful
  site projections (`Hubbard/SiteProjections*`, `DoubleOccupancy*`).
* Nagaoka §11.2 (`Hubbard/Hardcore*`, `EffectiveHamiltonian*`,
  `WeakNagaoka*`, `Nagaoka*`).
* Flat-band §11.3 (`Hubbard/TasakiFlatBand*`, `Mielke*`,
  `GeneralFlatBand*`).
* Non-singular / spin-wave §11.4 (`Hubbard/Nonsingular*`,
  `TasakiNonsingularFerro`, `Wannier*`, `TranslationOperator`,
  `FermionicTranslation`, `SpinWaveExcitation`).
* t-J and decorated Hubbard §11.5 (`Hubbard/TJ*`, `FermionSiteSpin`,
  `SpinfulVectorOperator`, `MetallicFerroModel`, `TanakaTasakiModel`,
  `GroundSubspaceAtFilling`, `SectorMinEnergy`, etc.).

Old `import LatticeSystem.Fermion.JordanWigner` continues to work
unchanged via this façade. Following the convention from
`docs/refactoring-conventions.md` §2 "Façade module policy".

(Refactor Phase 2 PR 14, plan v4 §3.1. JordanWigner extraction complete.
The former per-file overview table now lives in
`docs/jordan-wigner-overview.md`.)
-/

namespace LatticeSystem.Fermion

end LatticeSystem.Fermion
