import LatticeSystem.Tests.Foundation
import LatticeSystem.Tests.TestHelpers
import LatticeSystem.Tests.SpinDot
import LatticeSystem.Tests.TotalSpin
import LatticeSystem.Tests.SpinHalfRotation
import LatticeSystem.Tests.GibbsState
import LatticeSystem.Tests.MagnetizationSubspace
import LatticeSystem.Tests.SpinHalfFamily
import LatticeSystem.Tests.SpinOneFamily
import LatticeSystem.Tests.SpinSOperators
import LatticeSystem.Tests.SpinSAlgebra
import LatticeSystem.Tests.SpinSHermitian
import LatticeSystem.Tests.SpinSDiagProj
import LatticeSystem.Tests.SpinSLagrange
import LatticeSystem.Tests.SpinSLadderProj
import LatticeSystem.Tests.SpinSLadderRecursion
import LatticeSystem.Tests.SpinSLadderBoundary
import LatticeSystem.Tests.SpinSDiagProjProperties
import LatticeSystem.Tests.SpinSOffDiagUnit
import LatticeSystem.Tests.SpinSOp3Square
import LatticeSystem.Tests.SpinSPlusMinusDiag
import LatticeSystem.Tests.SpinSMinusPlusDiag
import LatticeSystem.Tests.SpinSCasimir
import LatticeSystem.Tests.SpinSEigenstates
import LatticeSystem.Tests.SpinSLadderStates
import LatticeSystem.Tests.SpinSCasimirEigenvalue
import LatticeSystem.Tests.SpinSCasimirInvariance
import LatticeSystem.Tests.SpinSCartan3
import LatticeSystem.Tests.SpinSCyclicCommutator
import LatticeSystem.Tests.SpinSCyclicCommutator23
import LatticeSystem.Tests.SpinSCyclicCommutator31
import LatticeSystem.Tests.SpinSDiagProjOrtho
import LatticeSystem.Tests.SpinSAevalDiagonal
import LatticeSystem.Tests.SpinSLagrangeFormula
import LatticeSystem.Tests.SpinSPMAsOneTwo
import LatticeSystem.Tests.SpinSProjMemAdjoin
import LatticeSystem.Tests.SpinSPMMemAdjoin
import LatticeSystem.Tests.SpinSNeighborUnitAdjoin
import LatticeSystem.Tests.SpinSOffsetUnitAdjoin
import LatticeSystem.Tests.SpinSAllUnitsAdjoin
import LatticeSystem.Tests.SpinSSpanningTheorem
import LatticeSystem.Tests.SpinSMultiSite
import LatticeSystem.Tests.SpinSMultiSiteDot
import LatticeSystem.Tests.SpinSHeisenberg
import LatticeSystem.Tests.SpinSTotalSpin
import LatticeSystem.Tests.SpinSMultiSiteCommutator
import LatticeSystem.Tests.SpinSMultiSiteDotComm
import LatticeSystem.Tests.SpinSTotalSquared
import LatticeSystem.Tests.SpinSMagnetization
import LatticeSystem.Tests.SpinSMarshallSign
import LatticeSystem.Tests.SpinSDressedHeisenberg
import LatticeSystem.Tests.SpinSRaiseLower
import LatticeSystem.Tests.SpinSHeisenbergRaiseLower
import LatticeSystem.Tests.SpinSDressedHeisenbergRaiseLower
import LatticeSystem.Tests.SpinSConfigDist
import LatticeSystem.Tests.SpinSRaiseLowerMatrixPow
import LatticeSystem.Tests.SU2Family
import LatticeSystem.Tests.Pauli
import LatticeSystem.Tests.Z2Z2
import LatticeSystem.Tests.Rotation3D
import LatticeSystem.Tests.Sanity
import LatticeSystem.Tests.Graph
import LatticeSystem.Tests.Heisenberg
import LatticeSystem.Tests.ManyBody
import LatticeSystem.Tests.Hubbard
import LatticeSystem.Tests.JordanWigner
import LatticeSystem.Tests.Ising
import LatticeSystem.Tests.JWAbstract
import LatticeSystem.Tests.Scale
import LatticeSystem.Tests.NeelState
import LatticeSystem.Tests.MarshallDressedBasis
import LatticeSystem.Tests.MarshallLiebMattisRealness
import LatticeSystem.Tests.MarshallLiebMattisMarshallSignTrick
import LatticeSystem.Tests.MarshallLiebMattisConnectivity
import LatticeSystem.Tests.MarshallLiebMattisH0Matrix
import LatticeSystem.Tests.MarshallLiebMattisEqMagnetization
import LatticeSystem.Tests.MarshallLiebMattisEqMagnetizationReachable
import LatticeSystem.Tests.MarshallLiebMattisH0Shifted
import LatticeSystem.Tests.MarshallLiebMattisSpinDotSwapEntry
import LatticeSystem.Tests.MarshallLiebMattisHeisenbergSwapEntry
import LatticeSystem.Tests.MarshallLiebMattisSpinDotOffBond
import LatticeSystem.Tests.MarshallLiebMattisHeisenbergSwapValue
import LatticeSystem.Tests.MarshallLiebMattisDressedSwapValue
import LatticeSystem.Tests.MarshallLiebMattisH0ShiftedSwap
import LatticeSystem.Tests.MarshallLiebMattisMatrixPowPath
import LatticeSystem.Tests.MarshallLiebMattisMatrixPowExtend
import LatticeSystem.Tests.MarshallLiebMattisToyHamiltonian
import LatticeSystem.Tests.MarshallLiebMattisBipartiteGraph
import LatticeSystem.Tests.MarshallLiebMattisSublatticeSpin
import LatticeSystem.Tests.MarshallLiebMattisSublatticeSpinDot
import LatticeSystem.Tests.MarshallLiebMattisToyHamiltonianCasimir
import LatticeSystem.Tests.MarshallLiebMattisSublatticeCasimirNeel
import LatticeSystem.Tests.TimeReversalSpinHalf
import LatticeSystem.Tests.TimeReversalMulti

/-!
# Test aggregator for the `lattice-system` library

Imports every regression-test module under
`LatticeSystem.Tests.*`. Loaded via the `lakefile.toml`'s
default-targets list so `lake build` exercises the full test
surface alongside the source library `LatticeSystem`.

Test methods (A-G) and the per-module Tests/source mapping
follow `docs/refactoring-conventions.md` §1
([project page](https://phasetr.github.io/lattice-system/refactoring-conventions/#1-test-methods-per-refactor-plan-v4-§21)).
-/
